Repository PrismLauncher/PrismLauncher, pull requests merged in 2022-12, with the labels that each got.

#538 A couple fixes for CF instance imports
  launcher/InstanceCreationTask.cpp
  launcher/InstanceImportTask.cpp
  launcher/MMCZip.cpp
  launcher/MMCZip.h
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
Labels: bug, simple change

#524 add windows on arm builds
  .github/workflows/build.yml
  .github/workflows/trigger_release.yml
  CMakeLists.txt
Labels: enhancement, actions, Windows, packaging

#481 Smart resource pack parsing for file drops / opens
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/minecraft/mod/ResourcePack.cpp
  launcher/minecraft/mod/ResourcePack.h
  launcher/minecraft/mod/TexturePack.cpp
  launcher/minecraft/mod/TexturePack.h
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.h
  launcher/minecraft/mod/tasks/LocalTexturePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalTexturePackParseTask.h
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/ImportResourcePackDialog.cpp
  launcher/ui/dialogs/ImportResourcePackDialog.h
  launcher/ui/dialogs/ImportResourcePackDialog.ui
Labels: enhancement

#423 Button to add agents
  launcher/minecraft/Agent.h
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile.h
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/VersionPage.h
  launcher/ui/pages/instance/VersionPage.ui
Labels: enhancement

#506 Remove blue-ish tint from flat white icons
  launcher/resources/flat_white/scalable/about.svg
  launcher/resources/flat_white/scalable/accounts.svg
  launcher/resources/flat_white/scalable/bug.svg
  launcher/resources/flat_white/scalable/cat.svg
  launcher/resources/flat_white/scalable/centralmods.svg
  launcher/resources/flat_white/scalable/checkupdate.svg
  launcher/resources/flat_white/scalable/copy.svg
  launcher/resources/flat_white/scalable/coremods.svg
  launcher/resources/flat_white/scalable/custom-commands.svg
  launcher/resources/flat_white/scalable/delete.svg
  launcher/resources/flat_white/scalable/discord.svg
  launcher/resources/flat_white/scalable/export.svg
  launcher/resources/flat_white/scalable/externaltools.svg
  launcher/resources/flat_white/scalable/help.svg
  launcher/resources/flat_white/scalable/instance-settings.svg
  launcher/resources/flat_white/scalable/jarmods.svg
  launcher/resources/flat_white/scalable/java.svg
  launcher/resources/flat_white/scalable/language.svg
  launcher/resources/flat_white/scalable/launch.svg
  launcher/resources/flat_white/scalable/launcher.svg
  launcher/resources/flat_white/scalable/loadermods.svg
  launcher/resources/flat_white/scalable/log.svg
  launcher/resources/flat_white/scalable/minecraft.svg
  launcher/resources/flat_white/scalable/multimc.svg
  launcher/resources/flat_white/scalable/new.svg
  launcher/resources/flat_white/scalable/news.svg
  launcher/resources/flat_white/scalable/notes.svg
  launcher/resources/flat_white/scalable/packages.svg
  launcher/resources/flat_white/scalable/patreon.svg
  launcher/resources/flat_white/scalable/proxy.svg
  launcher/resources/flat_white/scalable/quickmods.svg
  launcher/resources/flat_white/scalable/reddit-alien.svg
  launcher/resources/flat_white/scalable/refresh.svg
  launcher/resources/flat_white/scalable/rename.svg
  launcher/resources/flat_white/scalable/resourcepacks.svg
  launcher/resources/flat_white/scalable/screenshot-placeholder.svg
  launcher/resources/flat_white/scalable/screenshots.svg
  launcher/resources/flat_white/scalable/settings.svg
  launcher/resources/flat_white/scalable/shaderpacks.svg
  launcher/resources/flat_white/scalable/shortcut.svg
  launcher/resources/flat_white/scalable/star.svg
  launcher/resources/flat_white/scalable/status-bad.svg
  launcher/resources/flat_white/scalable/status-good.svg
  launcher/resources/flat_white/scalable/status-running.svg
  launcher/resources/flat_white/scalable/status-yellow.svg
  launcher/resources/flat_white/scalable/tag.svg
  launcher/resources/flat_white/scalable/viewfolder.svg
  launcher/resources/flat_white/scalable/worlds.svg
Labels: enhancement, simple change

#541 Warn before trashing instances
  launcher/ui/MainWindow.cpp
Labels: bug, enhancement, simple change

#547 Create FS::copy next to its usage in instance copying task
  launcher/InstanceCopyTask.cpp
Labels: bug, simple change

#560 Fix minutes unit
  launcher/MMCTime.cpp
Labels: enhancement, simple change

#557 Disable FS watcher after closing BlockedModsDialog
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.h
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.h
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
Labels: bug

#556 fix: make modrinth icon larger
  launcher/resources/multimc/scalable/instances/modrinth.svg
Labels: bug, simple change

#511 Improve usability in BlockedModsDialog
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
  launcher/ui/dialogs/BlockedModsDialog.ui
Labels: enhancement

#565 fix: add instance shortcut creation action to menubar
  launcher/ui/MainWindow.cpp
Labels: bug, simple change

#568 fix: fix creating instance shortcuts in flatpak
  launcher/FileSystem.cpp
  launcher/ui/MainWindow.cpp
Labels: bug, simple change

#571 fix(blockedmods): Track and use targetFolder for blocked files
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
Labels: bug, simple change

#572 feat: improve new.svg in breeze icon packs
  launcher/resources/breeze_dark/scalable/new.svg
  launcher/resources/breeze_light/scalable/new.svg
Labels: enhancement, simple change

#575 Prevent potental crash if droping non local files in BlockedModsDialog
  launcher/ui/dialogs/BlockedModsDialog.cpp
Labels: bug, simple change

#32 Add modpack update page in instance settings
  buildconfig/BuildConfig.h
  launcher/CMakeLists.txt
  launcher/InstanceImportTask.cpp
  launcher/InstanceImportTask.h
  launcher/InstanceList.cpp
  launcher/InstanceList.h
  launcher/InstancePageProvider.h
  launcher/InstanceTask.cpp
  launcher/InstanceTask.h
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.h
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.h
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.h
  launcher/ui/InstanceWindow.cpp
  launcher/ui/pages/BasePageContainer.h
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/instance/ManagedPackPage.h
  launcher/ui/pages/instance/ManagedPackPage.ui
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/widgets/PageContainer.cpp
  launcher/ui/widgets/PageContainer.h
Labels: enhancement

#461 Don't infinite loop when parsing big resource pack images
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/MTPixmapCache.h
  launcher/minecraft/mod/ResourcePack.cpp
Labels: bug

#486 Allow hiding buttons in WideBar
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.h
  launcher/ui/pages/instance/ScreenshotsPage.cpp
  launcher/ui/pages/instance/ScreenshotsPage.h
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/instance/ServersPage.h
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/VersionPage.h
  launcher/ui/pages/instance/WorldListPage.cpp
  launcher/ui/pages/instance/WorldListPage.h
  launcher/ui/widgets/WideBar.cpp
  launcher/ui/widgets/WideBar.h
Labels: enhancement

#584 fix breeze icon colors and matrix icon
  launcher/resources/breeze_dark/breeze_dark.qrc
  launcher/resources/breeze_dark/scalable/discord.svg
  launcher/resources/breeze_light/breeze_light.qrc
  launcher/resources/breeze_light/scalable/centralmods.svg
  launcher/resources/breeze_light/scalable/coremods.svg
  launcher/resources/breeze_light/scalable/discord.svg
  launcher/resources/breeze_light/scalable/jarmods.svg
Labels: bug, simple change

#569 Change mangohud detection and fix mangohud loading
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/MangoHud.cpp
  launcher/MangoHud.h
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug

#585 fix: remove leftover TODO
  launcher/ui/MainWindow.cpp
Labels: simple change

#587 Correct wording on libraries download task
  launcher/minecraft/update/LibrariesTask.cpp
Labels: enhancement, simple change

#600 Fix: Reset stylesheet before setting style
  launcher/ui/themes/ITheme.cpp
Labels: bug, simple change

#604 fix: crash with GTK2 theme due to QProxyStyle in ManagedPackPage
  launcher/ui/pages/instance/ManagedPackPage.cpp
Labels: bug, simple change

#601 Fix translation source strings
  launcher/ui/pages/instance/ManagedPackPage.cpp
Labels: simple change

#608 Bump version
  CMakeLists.txt
Labels: simple change

#561 Trash instance icons instead of deleting
  launcher/icons/IconList.cpp
  launcher/icons/IconList.h
  launcher/ui/dialogs/IconPickerDialog.cpp
  launcher/ui/dialogs/IconPickerDialog.h
Labels: enhancement

#605 fix: possible crash in mod and modpack downloaders with images
  launcher/ui/widgets/VariableSizedImageObject.cpp
Labels: bug, simple change

#593 Update installers-regex for winget releaser
  .github/workflows/winget.yml
Labels: simple change

#625 ApplicationMessage: Use QHash instead of QMap
  launcher/ApplicationMessage.cpp
  launcher/ApplicationMessage.h
Labels: enhancement, simple change

#631 improve msvc build flags
  CMakeLists.txt
Labels: enhancement, Windows

#630 fix: only show scrollbars when needed
  launcher/ui/dialogs/IconPickerDialog.cpp
  launcher/ui/dialogs/ImportResourcePackDialog.cpp
  launcher/ui/pages/instance/NotesPage.ui
  launcher/ui/pages/instance/OtherLogsPage.ui
  launcher/ui/pages/instance/VersionPage.ui
  launcher/ui/widgets/ModListView.cpp
Labels: enhancement, simple change

#636 Correctly set component versions in Modrinth pack updating
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.h
Labels: bug, simple change

#642 fix: exclude unused tls backends
  launcher/CMakeLists.txt
Labels: simple change

#628 Avoid deadlock when there's a lot of RPs in an instance
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/net/NetJob.cpp
  launcher/tasks/ConcurrentTask.cpp
  launcher/tasks/ConcurrentTask.h
  launcher/tasks/MultipleOptionsTask.cpp
  launcher/tasks/SequentialTask.cpp
Labels: bug

#647 Update Nix packaging
  flake.lock
  flake.nix
  nix/default.nix
Labels: simple change, packaging, Linux

#649 Update installers-regex for winget releaser again
  .github/workflows/winget.yml
Labels: actions, Windows

#644 Improve the README
  README.md
Labels: enhancement, simple change

#665 Use Qt logging facilities instead of our own
  launcher/Application.cpp
  program_info/prismlauncher.6.scd
Labels: enhancement

#666 assume builds are stable when git isn't installed
  buildconfig/BuildConfig.cpp.in
Labels: bug, simple change, packaging

#618 Safer destructive actions
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/minecraft/World.cpp
  launcher/minecraft/mod/Resource.cpp
  launcher/ui/GuiUtil.cpp
  launcher/ui/GuiUtil.h
  launcher/ui/MainWindow.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.h
  launcher/ui/pages/instance/LogPage.cpp
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  launcher/ui/pages/instance/OtherLogsPage.cpp
  launcher/ui/pages/instance/ScreenshotsPage.cpp
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/WorldListPage.cpp
  launcher/ui/pages/instance/WorldListPage.ui
Labels: enhancement

#680 Update metainfo
  program_info/org.prismlauncher.PrismLauncher.metainfo.xml.in
Labels: simple change

#684 Make use of logging categories for authentication data logging
  CMakeLists.txt
  launcher/CMakeLists.txt
  launcher/minecraft/auth/Parsers.cpp
  launcher/minecraft/auth/steps/EntitlementsStep.cpp
  launcher/minecraft/auth/steps/LauncherLoginStep.cpp
  launcher/minecraft/auth/steps/MSAStep.cpp
  launcher/minecraft/auth/steps/MinecraftProfileStep.cpp
  launcher/minecraft/auth/steps/MinecraftProfileStepMojang.cpp
  launcher/minecraft/auth/steps/XboxAuthorizationStep.cpp
  launcher/minecraft/auth/steps/XboxProfileStep.cpp
  libraries/katabasis/CMakeLists.txt
  libraries/katabasis/include/katabasis/DeviceFlow.h
  libraries/katabasis/src/DeviceFlow.cpp
Labels: enhancement

#626 feat: add a provider column to the mods page
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/Mod.h
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/Resource.h
  launcher/ui/widgets/ModListView.cpp
Labels: enhancement
