Repository PrismLauncher/PrismLauncher, pull requests merged in 2022-11, with the labels that each got.

#359 Removes erroneous space in APIPage.ui
  launcher/ui/pages/global/APIPage.ui
Labels: bug, simple change

#329 Only allow getting blocked mods from Modrinth when it's safe to do so
  launcher/modplatform/flame/FileResolvingTask.cpp
Labels: bug, simple change

#333 Fix ATL pack installation
  launcher/FileSystem.cpp
  tests/FileSystem_test.cpp
Labels: bug

#365 Fix logo name
  program_info/CMakeLists.txt
Labels: bug, simple change

#368 Update credits again
  launcher/ui/dialogs/AboutDialog.cpp
Labels: simple change

#346 fix: more user friendly Java warning text
  launcher/minecraft/launch/VerifyJavaInstall.cpp
Labels: enhancement, simple change

#372 Add Rory the Cat and a setting to change cats
  launcher/Application.cpp
  launcher/resources/backgrounds/backgrounds.qrc
  launcher/resources/backgrounds/kitteh-bday.png
  launcher/resources/backgrounds/kitteh-xmas.png
  launcher/resources/backgrounds/kitteh.png
  launcher/resources/backgrounds/rory-bday.png
  launcher/resources/backgrounds/rory-flat-bday.png
  launcher/resources/backgrounds/rory-flat-xmas.png
  launcher/resources/backgrounds/rory-flat.png
  launcher/resources/backgrounds/rory-xmas.png
  launcher/resources/backgrounds/rory.png
  launcher/ui/MainWindow.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement

#374 Fix LTO compilation with `-Werror=odr` flag
  launcher/BaseInstaller.h
  launcher/BaseVersion.h
  launcher/BaseVersionList.cpp
  launcher/BaseVersionList.h
  launcher/java/JavaInstallList.cpp
  launcher/java/JavaInstallList.h
  launcher/meta/Index.cpp
  launcher/meta/Index.h
  launcher/meta/JsonFormat.cpp
  launcher/meta/Version.cpp
  launcher/meta/Version.h
  launcher/meta/VersionList.cpp
  launcher/meta/VersionList.h
  launcher/minecraft/VanillaInstanceCreationTask.cpp
  launcher/minecraft/VanillaInstanceCreationTask.h
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.h
  launcher/ui/dialogs/VersionSelectDialog.cpp
  launcher/ui/dialogs/VersionSelectDialog.h
  launcher/ui/pages/modplatform/VanillaPage.cpp
  launcher/ui/pages/modplatform/VanillaPage.h
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.h
  launcher/ui/widgets/JavaSettingsWidget.cpp
  launcher/ui/widgets/JavaSettingsWidget.h
  launcher/ui/widgets/ModFilterWidget.h
  launcher/ui/widgets/VersionSelectWidget.cpp
  launcher/ui/widgets/VersionSelectWidget.h
Labels: bug

#294 Add a snapcraft.yml for building Snaps
  .github/workflows/build.yml
  .gitignore
  launcher/java/JavaUtils.cpp
  snap/snapcraft.yaml
Labels: packaging

#149 Multiple Custom Themes (searching the themes folder for directories with theme.json and lone qss files)
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/themes/CustomTheme.cpp
  launcher/ui/themes/CustomTheme.h
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
Labels: enhancement

#396 Spooky kitteh for halloween (again 💀)
  launcher/resources/backgrounds/backgrounds.qrc
  launcher/resources/backgrounds/kitteh-ween.png
  launcher/ui/MainWindow.cpp
Labels: enhancement, simple change

#229 Register as .zip/.mrpack handler on macOS and Linux
  CMakeLists.txt
  cmake/MacOSXBundleInfo.plist.in
  launcher/Application.cpp
  program_info/CMakeLists.txt
  program_info/modrinth-mrpack-mime.xml
  program_info/org.prismlauncher.PrismLauncher.desktop.in
Labels: enhancement

#399 fix(docs): use new format for adaptive images in README
  README.md
Labels: simple change

#400 chore: bump to 6.0
  CMakeLists.txt
Labels: simple change

#383 Add an option to lock the toolbars
  launcher/Application.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
Labels: enhancement, simple change

#242 Add more options to copy instance dialog
  launcher/CMakeLists.txt
  launcher/InstanceCopyPrefs.cpp
  launcher/InstanceCopyPrefs.h
  launcher/InstanceCopyTask.cpp
  launcher/InstanceCopyTask.h
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/CopyInstanceDialog.cpp
  launcher/ui/dialogs/CopyInstanceDialog.h
  launcher/ui/dialogs/CopyInstanceDialog.ui
Labels: enhancement

#405 add: Spooky Rory
  launcher/resources/backgrounds/backgrounds.qrc
  launcher/resources/backgrounds/kitteh-spooky.png
  launcher/resources/backgrounds/rory-flat-spooky.png
  launcher/resources/backgrounds/rory-spooky.png
  launcher/ui/MainWindow.cpp
Labels: enhancement, simple change

#411 Fix: Configuration-less config for Qt Install
  launcher/CMakeLists.txt
Labels: bug, simple change

#392 Assign java max mem based on system RAM
  launcher/Application.cpp
  launcher/Application.h
Labels: enhancement

#407 Update README.md
  README.md
Labels: documentation, simple change

#415 Fix warning in main function
  launcher/main.cpp
Labels: bug, simple change

#406 Save metacache after clearing
  launcher/ui/MainWindow.cpp
Labels: bug, simple change

#367 Implement "jumping" to other mods inside the mod browser
  launcher/ui/dialogs/ModDownloadDialog.cpp
  launcher/ui/dialogs/ModDownloadDialog.h
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/ModPage.ui
  launcher/ui/pages/modplatform/flame/FlameModPage.cpp
  launcher/ui/pages/modplatform/flame/FlameModPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthModPage.cpp
Labels: enhancement

#266 Windows file association
  program_info/win_install.nsi.in
Labels: enhancement

#304 Copy found blocked 3rd party mods to the new instance (ftb and curseforge)
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.h
  launcher/modplatform/helpers/HashUtils.cpp
  launcher/modplatform/helpers/HashUtils.h
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.h
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
  launcher/ui/dialogs/BlockedModsDialog.ui
Labels: enhancement

#445 Remove the clear button in the instance settings page's filter edits
  launcher/ui/pages/instance/ExternalResourcesPage.ui
  launcher/ui/pages/instance/VersionPage.ui
Labels: bug, simple change

#112 Support add to PATH on macOS
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
Labels: enhancement, macOS

#448 Fixup Warnings in MSVC build
  launcher/BaseInstance.h
  launcher/BaseVersionList.cpp
  launcher/VersionProxyModel.cpp
  launcher/icons/IconList.cpp
  launcher/meta/Index.cpp
  launcher/meta/JsonFormat.h
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/Rule.h
  launcher/minecraft/WorldList.cpp
  launcher/minecraft/WorldList.h
  launcher/minecraft/auth/AccountList.cpp
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/net/HttpMetaCache.cpp
  launcher/net/HttpMetaCache.h
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/atlauncher/AtlListModel.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/ftb/FtbListModel.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.h
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
Labels: enhancement, simple change

#428 Fixes to CI
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/trigger_builds.yml
  .github/workflows/trigger_release.yml
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/ui/pages/modplatform/ModPage.cpp
Labels: bug, enhancement, actions

#457 Bump 5.2
  CMakeLists.txt
Labels: simple change

#464 chore: use qt 6.4.1 on Windows-MSVC
  .github/workflows/build.yml
Labels: simple change, actions

#431 Add commit hash to `--version`
  launcher/Application.cpp
Labels: enhancement, simple change

#467 Fix serialization of components with custom metadata
  launcher/minecraft/MojangVersionFormat.cpp
  launcher/minecraft/OneSixVersionFormat.cpp
Labels: bug, simple change

#454 feat: Change the theme via alt menu
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
Labels: enhancement

#471 Fix AUR qt5-git and git having the wrong AUR links
  README.md
Labels: bug, simple change

#439 Better Blocked Mods Dialog
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
  launcher/ui/dialogs/BlockedModsDialog.ui
Labels: enhancement

#455 fix: Fix some stuff in the menu bar
  launcher/ui/MainWindow.cpp
Labels: bug, enhancement, simple change

#456 feat: add flatpak builds to the ci for testing
  .github/workflows/build.yml
  flatpak/org.prismlauncher.PrismLauncher.yml
  flatpak/prime-run
  flatpak/prismlauncher
Labels: enhancement, actions, packaging, Linux

#474 Improve display names of more languages
  launcher/translations/TranslationsModel.cpp
Labels: bug, simple change

#476 Update community links
  README.md
Labels: simple change

#482 fix(actions): fix cache on flatpak
  .github/workflows/build.yml
Labels: simple change

#483 Fix New Zealand English display name
  launcher/translations/TranslationsModel.cpp
Labels: bug, simple change

#243 Add migration dialog
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/DataMigrationTask.cpp
  launcher/DataMigrationTask.h
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/InstanceCopyTask.cpp
  launcher/pathmatcher/SimplePrefixMatcher.h
  launcher/ui/dialogs/ProgressDialog.cpp
  tests/FileSystem_test.cpp
Labels: enhancement

#498 fix file copy in migration task
  launcher/FileSystem.cpp
Labels: bug, simple change

#514 fix: force bundled libs on win msvc
  .github/workflows/build.yml
Labels: simple change, actions

#412 add the missing icons to the legacy icon theme
  launcher/resources/multimc/multimc.qrc
  launcher/resources/multimc/scalable/delete.svg
  launcher/resources/multimc/scalable/export.svg
  launcher/resources/multimc/scalable/launch.svg
  launcher/resources/multimc/scalable/rename.svg
  launcher/resources/multimc/scalable/tag.svg
Labels: enhancement

#227 Add 'Create shortcut' button to instance toolbar
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/resources/OSX/OSX.qrc
  launcher/resources/OSX/scalable/shortcut.svg
  launcher/resources/iOS/iOS.qrc
  launcher/resources/iOS/scalable/shortcut.svg
  launcher/resources/pe_blue/pe_blue.qrc
  launcher/resources/pe_blue/scalable/shortcut.svg
  launcher/resources/pe_colored/pe_colored.qrc
  launcher/resources/pe_colored/scalable/shortcut.svg
  launcher/resources/pe_dark/pe_dark.qrc
  launcher/resources/pe_dark/scalable/shortcut.svg
  launcher/resources/pe_light/pe_light.qrc
  launcher/resources/pe_light/scalable/shortcut.svg
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
Labels: enhancement

#492 refactor(nix): synchronize changes from nixpkgs
  flake.nix
  nix/default.nix
Labels: packaging, Linux

#521 Add missing shortcut icons
  launcher/resources/breeze_dark/breeze_dark.qrc
  launcher/resources/breeze_dark/scalable/shortcut.svg
  launcher/resources/breeze_light/breeze_light.qrc
  launcher/resources/breeze_light/scalable/shortcut.svg
  launcher/resources/flat/flat.qrc
  launcher/resources/flat/scalable/shortcut.svg
  launcher/resources/flat_white/flat_white.qrc
  launcher/resources/flat_white/scalable/shortcut.svg
  launcher/resources/multimc/multimc.qrc
  launcher/resources/multimc/scalable/shortcut.svg
Labels: enhancement

#528 Make resource buttons work when instance is running
  launcher/minecraft/MinecraftInstance.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.h
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
Labels: bug, simple change

#527 fix: use qt 6.4.0 on windows msvc for now
  .github/workflows/build.yml
Labels: simple change, actions, Windows

#436 Validate maximum memory allocation
  launcher/ui/pages/global/JavaPage.cpp
  launcher/ui/pages/global/JavaPage.h
  launcher/ui/pages/global/JavaPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.h
  launcher/ui/pages/instance/InstanceSettingsPage.ui
  launcher/ui/widgets/JavaSettingsWidget.cpp
  launcher/ui/widgets/JavaSettingsWidget.h
Labels: enhancement
