Repository PrismLauncher/PrismLauncher, pull requests merged in 2022-10, with the labels that each got.

#23 New CurseForge Key
  CMakeLists.txt
Labels: simple change

#25 Fix Data path
  launcher/Application.cpp
Labels: simple change

#26 Add armhf support
  launcher/RuntimeContext.h
Labels: enhancement, simple change

#29 Add clear metadata action
  launcher/net/HttpMetaCache.cpp
  launcher/net/HttpMetaCache.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
Labels: enhancement, simple change

#28 Fix instance copy on Linux and macOS :slightly_smiling_face:
  launcher/FileSystem.cpp
  tests/FileSystem_test.cpp
  tests/testdata/FileSystem/test_folder/.secret_folder/.secret_file.txt
Labels: bug

#68 Fix hosted weblate translation website URL
  CMakeLists.txt
Labels: bug, enhancement

#55 Import config from `polymc.cfg` if available
  launcher/Application.cpp
  launcher/settings/INISettingsObject.cpp
  launcher/settings/INISettingsObject.h
Labels: enhancement

#82 Fix polymc config fallback when no config exists
  launcher/settings/INISettingsObject.cpp
Labels: bug, simple change

#60 clean up README
  README.md
Labels: simple change

#88 Import config from `multimc.cfg` if available
  launcher/Application.cpp
Labels: enhancement, simple change

#75 Change discord invite to a banner
  README.md
Labels: enhancement, simple change

#54 Rename PolyMC to Prism
  launcher/java/JavaUtils.cpp
  launcher/minecraft/Library.h
  launcher/minecraft/VersionFile.h
  launcher/minecraft/auth/AccountList.h
  launcher/minecraft/auth/MinecraftAccount.h
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  launcher/minecraft/launch/MinecraftServerTarget.cpp
  launcher/settings/Setting.h
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/AboutDialog.cpp
  launcher/ui/dialogs/UpdateDialog.cpp
  launcher/updater/DownloadTask.h
  launcher/updater/GoUpdate.cpp
  libraries/README.md
  libraries/katabasis/README.md
  libraries/launcher/CMakeLists.txt
  libraries/launcher/org/prismlauncher/EntryPoint.java
  libraries/launcher/org/prismlauncher/Launcher.java
  libraries/launcher/org/prismlauncher/LauncherFactory.java
  libraries/launcher/org/prismlauncher/applet/LegacyFrame.java
  libraries/launcher/org/prismlauncher/exception/ParameterNotFoundException.java
  libraries/launcher/org/prismlauncher/exception/ParseException.java
  libraries/launcher/org/prismlauncher/impl/OneSixLauncher.java
  libraries/launcher/org/prismlauncher/utils/Parameters.java
  libraries/launcher/org/prismlauncher/utils/Utils.java
  nix/NIX.md
  program_info/prismlauncher.6.scd
Labels: branding

#92 New Logo
  README.md
  launcher/resources/OSX/scalable/launcher.svg
  launcher/resources/flat/scalable/launcher.svg
  launcher/resources/iOS/scalable/launcher.svg
  launcher/resources/multimc/multimc.qrc
  launcher/resources/multimc/scalable/instances/polymc.svg
  launcher/resources/multimc/scalable/instances/prismlauncher.svg
  launcher/resources/multimc/scalable/launcher.svg
  launcher/resources/pe_blue/scalable/launcher.svg
  launcher/resources/pe_colored/scalable/launcher.svg
  launcher/resources/pe_dark/scalable/launcher.svg
  launcher/resources/pe_light/scalable/launcher.svg
  launcher/ui/dialogs/AboutDialog.cpp
  program_info/org.prismlauncher.PrismLauncher.Social.svg
  program_info/org.prismlauncher.PrismLauncher.Source.svg
  program_info/org.prismlauncher.PrismLauncher.bigsur.svg
  program_info/org.prismlauncher.PrismLauncher.logo-darkmode.svg
  program_info/org.prismlauncher.PrismLauncher.logo.source.svg
  program_info/org.prismlauncher.PrismLauncher.logo.svg
  program_info/org.prismlauncher.PrismLauncher.svg
  program_info/prismlauncher-header-black.svg
  program_info/prismlauncher-header.Source.svg
  program_info/prismlauncher-header.svg
  program_info/prismlauncher-monochrome.Source.svg
  program_info/prismlauncher.icns
  program_info/prismlauncher.ico
Labels: enhancement, branding

#27 Fix and improve FTB modpack installation
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.h
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/dialogs/ProgressDialog.cpp
  launcher/ui/pages/modplatform/ftb/FtbListModel.cpp
  launcher/ui/pages/modplatform/ftb/FtbListModel.h
  launcher/ui/pages/modplatform/ftb/FtbPage.cpp
  launcher/ui/pages/modplatform/ftb/FtbPage.h
Labels: bug, enhancement

#31 Add image support for mod/modpack pages
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/ui/dialogs/NewsDialog.cpp
  launcher/ui/dialogs/NewsDialog.ui
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.ui
  launcher/ui/pages/modplatform/flame/FlameModPage.cpp
  launcher/ui/pages/modplatform/ftb/FtbPage.cpp
  launcher/ui/pages/modplatform/ftb/FtbPage.ui
  launcher/ui/pages/modplatform/modrinth/ModrinthModPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.ui
  launcher/ui/widgets/ProjectDescriptionPage.cpp
  launcher/ui/widgets/ProjectDescriptionPage.h
  launcher/ui/widgets/VariableSizedImageObject.cpp
  launcher/ui/widgets/VariableSizedImageObject.h
Labels: enhancement

#100 Improve approachability
  program_info/org.prismlauncher.PrismLauncher.desktop.in
  program_info/org.prismlauncher.PrismLauncher.metainfo.xml.in
Labels: enhancement

#123 Fix incorrect release titles
  .github/workflows/trigger_release.yml
Labels: bug, simple change

#148 Renamed inappropriate instances of "PrismLauncher" to "Prism Launcher"
  CMakeLists.txt
  program_info/README.md
Labels: bug, simple change

#47 Change branding in .github/ YAML files
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/rfc.yml
  .github/ISSUE_TEMPLATE/suggestion.yml
Labels: branding

#202 Fix typo
  launcher/ui/pages/global/LauncherPage.cpp
Labels: bug, simple change

#201 Add Netlify as sponsor
  README.md
Labels: simple change

#187 add icons to the instance context menu and 4 new icons
  launcher/resources/OSX/OSX.qrc
  launcher/resources/OSX/scalable/delete.svg
  launcher/resources/OSX/scalable/export.svg
  launcher/resources/OSX/scalable/rename.svg
  launcher/resources/OSX/scalable/tag.svg
  launcher/resources/flat/flat.qrc
  launcher/resources/flat/scalable/delete.svg
  launcher/resources/flat/scalable/export.svg
  launcher/resources/flat/scalable/rename.svg
  launcher/resources/flat/scalable/tag.svg
  launcher/resources/iOS/iOS.qrc
  launcher/resources/iOS/scalable/delete.svg
  launcher/resources/iOS/scalable/export.svg
  launcher/resources/iOS/scalable/rename.svg
  launcher/resources/iOS/scalable/tag.svg
  launcher/resources/pe_blue/pe_blue.qrc
  launcher/resources/pe_blue/scalable/delete.svg
  launcher/resources/pe_blue/scalable/export.svg
  launcher/resources/pe_blue/scalable/rename.svg
  launcher/resources/pe_blue/scalable/tag.svg
  launcher/resources/pe_colored/pe_colored.qrc
  launcher/resources/pe_colored/scalable/delete.svg
  launcher/resources/pe_colored/scalable/export.svg
  launcher/resources/pe_colored/scalable/rename.svg
  launcher/resources/pe_colored/scalable/tag.svg
  launcher/resources/pe_dark/pe_dark.qrc
  launcher/resources/pe_dark/scalable/delete.svg
  launcher/resources/pe_dark/scalable/export.svg
  launcher/resources/pe_dark/scalable/rename.svg
  launcher/resources/pe_dark/scalable/tag.svg
  launcher/resources/pe_light/pe_light.qrc
  launcher/resources/pe_light/scalable/delete.svg
  launcher/resources/pe_light/scalable/export.svg
  launcher/resources/pe_light/scalable/rename.svg
  launcher/resources/pe_light/scalable/tag.svg
  launcher/ui/MainWindow.cpp
Labels: enhancement, ui rework

#203 Don't build renovate branches
  .github/workflows/trigger_builds.yml
Labels: enhancement, simple change

#185 Tell Qt to hide the ProgressDialog when failing and succeeding jobs
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/ui/dialogs/ProgressDialog.cpp
Labels: bug, simple change

#218 make jars path specific to prism
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/Application.cpp
Labels: bug, simple change

#225 Fix segfault when resolving Flame resources
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FileResolvingTask.h
Labels: bug, simple change

#224 ATLauncher: Abort install if optional mods dialog is closed
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.h
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.h
Labels: bug, simple change

#230 Add PR template
  .github/pull_request_template.md
Labels: documentation, enhancement, simple change

#215 CurseForge modpack page improvements
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.ui
Labels: enhancement

#233 ATLauncher: Fix pack installation always aborting
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.cpp
Labels: bug, simple change

#234 Deduplicates java installs before passing it on
  launcher/java/JavaUtils.cpp
Labels: bug

#240 Fix version labels width
  launcher/ui/dialogs/AboutDialog.ui
Labels: enhancement, simple change

#228 Change C old style cast to C++ cast
  launcher/GZip.cpp
  launcher/HoeDown.h
  launcher/tasks/Task.cpp
  libraries/LocalPeer/src/LocalPeer.cpp
  libraries/katabasis/src/DeviceFlow.cpp
  libraries/murmur2/src/MurmurHash2.cpp
Labels: enhancement

#274 Better dark theme selection contrast
  launcher/ui/themes/DarkTheme.cpp
Labels: enhancement, simple change

#281 fix: use display name in NSIS
  program_info/win_install.nsi.in
Labels: bug, simple change, Windows

#211 Allow Prism to open an instance's window from command line
  launcher/Application.cpp
  launcher/Application.h
  program_info/prismlauncher.6.scd
Labels: enhancement

#283 Retry mod search job after aborting it
  launcher/modplatform/helpers/NetworkModAPI.cpp
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModModel.h
Labels: bug, simple change

#206 Use static height for changelogs in the mod updater dialog
  launcher/ui/dialogs/ModUpdateDialog.cpp
Labels: bug, simple change

#231 update macos plist contents (fixes #132 / #137)
  .github/workflows/build.yml
  CMakeLists.txt
  program_info/CMakeLists.txt
Labels: bug, documentation, macOS

#318 Fix: Don't specify x86 in manifest
  program_info/prismlauncher.manifest.in
Labels: bug, simple change, Windows

#301 feat(actions): use clang32 for building on windows
  .github/workflows/build.yml
  launcher/FileSystem.cpp
Labels: enhancement, actions, Windows, packaging

#319 Avoid segfault for unexpected Modrinth API response
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
Labels: bug

#322 feat: use clang64 on qt6 builds
  .github/workflows/build.yml
Labels: enhancement, actions, Windows, packaging

#65 Add flat white icons
  launcher/CMakeLists.txt
  launcher/main.cpp
  launcher/resources/flat_white/flat_white.qrc
  launcher/resources/flat_white/index.theme
  launcher/resources/flat_white/scalable/about.svg
  launcher/resources/flat_white/scalable/accounts.svg
  launcher/resources/flat_white/scalable/bug.svg
  launcher/resources/flat_white/scalable/cat.svg
  launcher/resources/flat_white/scalable/centralmods.svg
  launcher/resources/flat_white/scalable/checkupdate.svg
  launcher/resources/flat_white/scalable/copy.svg
  launcher/resources/flat_white/scalable/coremods.svg
  launcher/resources/flat_white/scalable/custom-commands.svg
  launcher/resources/flat_white/scalable/delete.svg
  launcher/resources/flat_white/scalable/discord.svg
  launcher/resources/flat_white/scalable/export.svg
  launcher/resources/flat_white/scalable/externaltools.svg
  launcher/resources/flat_white/scalable/help.svg
  launcher/resources/flat_white/scalable/instance-settings.svg
  launcher/resources/flat_white/scalable/jarmods.svg
  launcher/resources/flat_white/scalable/java.svg
  launcher/resources/flat_white/scalable/language.svg
  launcher/resources/flat_white/scalable/launcher.svg
  launcher/resources/flat_white/scalable/loadermods.svg
  launcher/resources/flat_white/scalable/log.svg
  launcher/resources/flat_white/scalable/minecraft.svg
  launcher/resources/flat_white/scalable/multimc.svg
  launcher/resources/flat_white/scalable/new.svg
  launcher/resources/flat_white/scalable/news.svg
  launcher/resources/flat_white/scalable/notes.svg
  launcher/resources/flat_white/scalable/packages.svg
  launcher/resources/flat_white/scalable/patreon.svg
  launcher/resources/flat_white/scalable/proxy.svg
  launcher/resources/flat_white/scalable/quickmods.svg
  launcher/resources/flat_white/scalable/reddit-alien.svg
  launcher/resources/flat_white/scalable/refresh.svg
  launcher/resources/flat_white/scalable/rename.svg
  launcher/resources/flat_white/scalable/resourcepacks.svg
  launcher/resources/flat_white/scalable/screenshot-placeholder.svg
  launcher/resources/flat_white/scalable/screenshots.svg
  launcher/resources/flat_white/scalable/settings.svg
  launcher/resources/flat_white/scalable/shaderpacks.svg
  launcher/resources/flat_white/scalable/star.svg
  launcher/resources/flat_white/scalable/status-bad.svg
  launcher/resources/flat_white/scalable/status-good.svg
  launcher/resources/flat_white/scalable/status-running.svg
  launcher/resources/flat_white/scalable/status-yellow.svg
  launcher/resources/flat_white/scalable/tag.svg
  launcher/resources/flat_white/scalable/viewfolder.svg
  launcher/resources/flat_white/scalable/worlds.svg
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement, blocked

#267 add icons to the instance toolbar
  launcher/resources/OSX/OSX.qrc
  launcher/resources/OSX/scalable/launch.svg
  launcher/resources/flat/flat.qrc
  launcher/resources/flat/scalable/launch.svg
  launcher/resources/flat_white/flat_white.qrc
  launcher/resources/flat_white/scalable/launch.svg
  launcher/resources/iOS/iOS.qrc
  launcher/resources/iOS/scalable/launch.svg
  launcher/resources/pe_blue/pe_blue.qrc
  launcher/resources/pe_blue/scalable/launch.svg
  launcher/resources/pe_colored/pe_colored.qrc
  launcher/resources/pe_colored/scalable/launch.svg
  launcher/resources/pe_dark/pe_dark.qrc
  launcher/resources/pe_dark/scalable/launch.svg
  launcher/resources/pe_light/pe_light.qrc
  launcher/resources/pe_light/scalable/launch.svg
  launcher/ui/MainWindow.cpp
Labels: enhancement

#173 fix: update icon generate script
  launcher/resources/OSX/scalable/launcher.svg
  launcher/resources/flat/scalable/launcher.svg
  launcher/resources/iOS/scalable/launcher.svg
  launcher/resources/multimc/scalable/launcher.svg
  launcher/resources/pe_blue/scalable/launcher.svg
  launcher/resources/pe_colored/scalable/launcher.svg
  launcher/resources/pe_dark/scalable/launcher.svg
  launcher/resources/pe_light/scalable/launcher.svg
  program_info/genicons.sh
  program_info/prismlauncher.ico
Labels: bug, Windows

#338 update credits
  launcher/ui/dialogs/AboutDialog.cpp
Labels: documentation, simple change

#342 Fix hardcoded icon
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/Application.cpp
  program_info/CMakeLists.txt
Labels: simple change

#353 Change Profiles to Accounts for consistency
  launcher/ui/MainWindow.cpp
Labels: bug

#352 Fix: Check if Windows 10 before calling setDarkWinTitlebar()
  launcher/Application.cpp
Labels: bug, simple change, Windows

#354 Improve display names of certain languages
  launcher/translations/TranslationsModel.cpp
Labels: bug, simple change

#351 Fix Trash issues
  launcher/Application.cpp
  launcher/Application.h
  launcher/DesktopServices.cpp
  launcher/DesktopServices.h
  launcher/FileSystem.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/pages/global/LauncherPage.cpp
Labels: bug
