Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-10, with the labels that each got.

#1656 Drop support for Mojang accounts
  launcher/CMakeLists.txt
  launcher/LaunchController.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/auth/AccountData.cpp
  launcher/minecraft/auth/AccountData.h
  launcher/minecraft/auth/AccountList.cpp
  launcher/minecraft/auth/AccountList.h
  launcher/minecraft/auth/AuthSession.h
  launcher/minecraft/auth/MinecraftAccount.cpp
  launcher/minecraft/auth/MinecraftAccount.h
  launcher/minecraft/auth/Yggdrasil.cpp
  launcher/minecraft/auth/Yggdrasil.h
  launcher/minecraft/auth/flows/AuthFlow.h
  launcher/minecraft/auth/flows/Mojang.cpp
  launcher/minecraft/auth/flows/Mojang.h
  launcher/minecraft/auth/steps/MigrationEligibilityStep.cpp
  launcher/minecraft/auth/steps/MigrationEligibilityStep.h
  launcher/minecraft/auth/steps/MinecraftProfileStep.cpp
  launcher/minecraft/auth/steps/MinecraftProfileStepMojang.cpp
  launcher/minecraft/auth/steps/MinecraftProfileStepMojang.h
  launcher/minecraft/auth/steps/YggdrasilStep.cpp
  launcher/minecraft/auth/steps/YggdrasilStep.h
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/LoginDialog.cpp
  launcher/ui/dialogs/LoginDialog.h
  launcher/ui/dialogs/LoginDialog.ui
  launcher/ui/pages/global/AccountListPage.cpp
  launcher/ui/pages/global/AccountListPage.h
  launcher/ui/pages/global/AccountListPage.ui
  launcher/ui/pages/instance/VersionPage.cpp
Labels: simple change, changelog:removed

#1090 Acknowledge version release types from mod platforms
  launcher/minecraft/auth/steps/XboxUserStep.cpp
  launcher/modplatform/CheckUpdateTask.h
  launcher/modplatform/ModIndex.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/flame/FlamePackIndex.cpp
  launcher/modplatform/flame/FlamePackIndex.h
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.h
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/dialogs/ReviewMessageBox.cpp
  launcher/ui/dialogs/ReviewMessageBox.h
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
Labels: enhancement, simple change, changelog:added

#1657 Don't display invalid shaders
  launcher/minecraft/mod/ShaderPack.cpp
  launcher/minecraft/mod/ShaderPack.h
  launcher/minecraft/mod/ShaderPackFolderModel.h
Labels: bug, simple change, changelog:fixed

#1672 Update default account when accounts change
  launcher/ui/MainWindow.cpp
Labels: bug, simple change, changelog:fixed

#1670 Don't update mods if no mod loader is installed
  launcher/ui/pages/instance/ModFolderPage.cpp
Labels: bug, simple change, changelog:fixed

#1676 revert back the release order
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
Labels: simple change, changelog:merged

#1537 added -Wno-gnu-zero-variadic-macro-arguments and fixed more warnings
  cmake/CompilerWarnings.cmake
  launcher/java/JavaInstall.h
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/ui/widgets/VersionSelectWidget.h
Labels: simple change, changelog:merged

#1678 fixed quilt dependencies
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
Labels: bug, simple change, changelog:merged

#1682 Add more Java installation dirs
  launcher/java/JavaUtils.cpp
Labels: changelog:added

#1658 Added version check for neoforge filter
  launcher/minecraft/PackProfile.cpp
  tests/Version_test.cpp
Labels: enhancement, simple change, changelog:changed

#1591 fix: make cached instead of file for ftb pack import
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
Labels: bug, simple change, changelog:fixed

#1405 Allow updating managed packs from local file
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/instance/ManagedPackPage.h
  launcher/ui/pages/instance/ManagedPackPage.ui
Labels: enhancement, simple change, changelog:added

#1563 Pack import fixes and improvements
  launcher/CMakeLists.txt
  launcher/modplatform/atlauncher/ATLPackIndex.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlamePackIndex.cpp
  launcher/modplatform/flame/PackManifest.h
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.h
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/pages/modplatform/OptionalModDialog.cpp
  launcher/ui/pages/modplatform/OptionalModDialog.h
  launcher/ui/pages/modplatform/OptionalModDialog.ui
  launcher/ui/pages/modplatform/atlauncher/AtlListModel.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.h
  launcher/ui/pages/modplatform/atlauncher/AtlPage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.cpp
  launcher/ui/pages/modplatform/legacy_ftb/Page.cpp
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
Labels: bug, enhancement, changelog:added, changelog:fixed

#1709 Fix compatibility with Qt 6.6
  launcher/translations/TranslationsModel.cpp
  launcher/translations/TranslationsModel.h
Labels: bug, simple change, Linux, changelog:fixed

#1684 removed windows legacy builds
  .github/workflows/build.yml
  .github/workflows/trigger_release.yml
Labels: simple change, actions, Windows, rfc, changelog:omit

#1706 removed the better release for modrinth modpacks
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
Labels: simple change, changelog:omit

#1673 fix folder attributes on windows copy
  launcher/FileSystem.cpp
Labels: bug, simple change, Windows, changelog:fixed

#1383 Renaming instance groups
  launcher/InstanceList.cpp
  launcher/InstanceList.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/dialogs/CopyInstanceDialog.cpp
  launcher/ui/dialogs/NewInstanceDialog.cpp
Labels: enhancement, changelog:added

#1549 added suport for atlauncher browser download
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
Labels: bug, simple change, changelog:fixed

#1268 Feat: Windows (And portable linux / appimage) Auto Updater
  .github/workflows/build.yml
  .github/workflows/trigger_builds.yml
  .github/workflows/trigger_release.yml
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/MMCZip.cpp
  launcher/MMCZip.h
  launcher/StringUtils.cpp
  launcher/StringUtils.h
  launcher/Version.h
  launcher/filelink/FileLink.cpp
  launcher/filelink/FileLink.h
  launcher/filelink/filelink_main.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.h
  launcher/net/Download.cpp
  launcher/net/NetJob.cpp
  launcher/net/NetRequest.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/ProgressDialog.ui
  launcher/ui/dialogs/UpdateAvailableDialog.cpp
  launcher/ui/dialogs/UpdateAvailableDialog.h
  launcher/ui/dialogs/UpdateAvailableDialog.ui
  launcher/updater/PrismExternalUpdater.cpp
  launcher/updater/PrismExternalUpdater.h
  launcher/updater/prismupdater/GitHubRelease.cpp
  launcher/updater/prismupdater/GitHubRelease.h
  launcher/updater/prismupdater/PrismUpdater.cpp
  launcher/updater/prismupdater/PrismUpdater.h
  launcher/updater/prismupdater/SelectReleaseDialog.ui
  launcher/updater/prismupdater/UpdaterDialogs.cpp
  launcher/updater/prismupdater/UpdaterDialogs.h
  launcher/updater/prismupdater/updater.exe.manifest
  launcher/updater/prismupdater/updater_main.cpp
  program_info/win_install.nsi.in
Labels: enhancement, actions, Windows, packaging, Linux, changelog:added

#1717 chore: bump Qt to Qt 6.6.0
  .github/workflows/build.yml
Labels: simple change, actions

#1724 Only build updater when correct conditions are met
  CMakeLists.txt
  launcher/CMakeLists.txt
Labels: bug, simple change, changelog:fixed

#1722 Allow loading themes with missing resources folder
  launcher/ui/themes/CustomTheme.cpp
Labels: simple change, changelog:fixed

#1726 Added Trial97 as maintainer in about dialog
  launcher/ui/dialogs/AboutDialog.cpp
Labels: simple change, changelog:omit

#1374 Added welcome screen
  launcher/ui/instanceview/InstanceView.cpp
Labels: enhancement, ui rework, changelog:added

#1692 Fix wrong account selection
  launcher/LaunchController.cpp
Labels: bug, simple change, changelog:fixed

#1737 Fixed FTBApp import icon
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.cpp
Labels: bug, simple change, changelog:merged

#1290 Refactor ImgurUpload
  launcher/CMakeLists.txt
  launcher/minecraft/AssetsUtils.cpp
  launcher/net/NetRequest.cpp
  launcher/net/StaticHeaderProxy.h
  launcher/screenshots/ImgurAlbumCreation.cpp
  launcher/screenshots/ImgurAlbumCreation.h
  launcher/screenshots/ImgurUpload.cpp
  launcher/screenshots/ImgurUpload.h
  launcher/ui/pages/instance/ScreenshotsPage.cpp
Labels: bug, changelog:fixed

#1515 More system properties
  launcher/BaseInstance.cpp
  launcher/minecraft/MinecraftInstance.cpp
  libraries/launcher/org/prismlauncher/EntryPoint.java
  libraries/launcher/org/prismlauncher/launcher/impl/AbstractLauncher.java
Labels: enhancement, changelog:added

#1747 fix: java memory not set on initial setup
  launcher/ui/setupwizard/JavaWizardPage.cpp
Labels: bug, simple change, changelog:fixed

#1355 Custom environment variables
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/minecraft/MinecraftInstance.cpp
  launcher/resources/breeze_dark/breeze_dark.qrc
  launcher/resources/breeze_dark/scalable/environment-variables.svg
  launcher/resources/breeze_light/breeze_light.qrc
  launcher/resources/breeze_light/scalable/environment-variables.svg
  launcher/resources/flat/flat.qrc
  launcher/resources/flat/scalable/custom-commands.svg
  launcher/resources/flat/scalable/environment-variables.svg
  launcher/resources/flat_white/flat_white.qrc
  launcher/resources/flat_white/scalable/custom-commands.svg
  launcher/resources/flat_white/scalable/environment-variables.svg
  launcher/resources/multimc/multimc.qrc
  launcher/resources/multimc/scalable/custom-commands.svg
  launcher/resources/multimc/scalable/environment-variables.svg
  launcher/resources/pe_blue/pe_blue.qrc
  launcher/resources/pe_blue/scalable/environment-variables.svg
  launcher/resources/pe_colored/pe_colored.qrc
  launcher/resources/pe_colored/scalable/environment-variables.svg
  launcher/resources/pe_dark/pe_dark.qrc
  launcher/resources/pe_dark/scalable/environment-variables.svg
  launcher/resources/pe_light/pe_light.qrc
  launcher/resources/pe_light/scalable/environment-variables.svg
  launcher/ui/pages/global/EnvironmentVariablesPage.cpp
  launcher/ui/pages/global/EnvironmentVariablesPage.h
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.ui
  launcher/ui/widgets/EnvironmentVariables.cpp
  launcher/ui/widgets/EnvironmentVariables.h
  launcher/ui/widgets/EnvironmentVariables.ui
Labels: enhancement, changelog:added

#1742 fix switch/case fallthrough in resource parse tasks
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalTexturePackParseTask.cpp
Labels: bug, simple change, changelog:fixed

#1691 Add no_color env variable
  launcher/minecraft/MinecraftInstance.cpp
Labels: enhancement, simple change, changelog:added

#1758 [Windows] Remove Windows 7/8 support from app manifest
  program_info/prismlauncher.manifest.in
Labels: simple change, Windows, changelog:removed

#1685 Autodetect Java bundled with official launcher
  launcher/java/JavaUtils.cpp
  launcher/java/JavaUtils.h
Labels: enhancement, simple change, changelog:added
