Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-01, with the labels that each got.

#713 Skip HTML in markdown rendering
  launcher/ui/pages/modplatform/ModPage.cpp
Labels: bug

#710 Fix 1.16+ Forge Technic Launcher imports
  launcher/modplatform/technic/TechnicPackProcessor.cpp
Labels: bug, simple change

#716 chore: update windows msvc to qt 6.4.2
  .github/workflows/build.yml
Labels: bug, enhancement, simple change, actions, Windows, packaging

#715 add teawie as a cat
  launcher/resources/backgrounds/backgrounds.qrc
  launcher/resources/backgrounds/teawie-bday.png
  launcher/resources/backgrounds/teawie-spooky.png
  launcher/resources/backgrounds/teawie-xmas.png
  launcher/resources/backgrounds/teawie.png
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement

#726 ui: Let Qt 6.4.2 handle dark mode titlebar
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/ui/WinDarkmode.cpp
  launcher/ui/WinDarkmode.h
  launcher/ui/themes/ThemeManager.cpp
Labels: enhancement

#729 fix: just use github runner's openssl 1.1 instead of installing 3 on …
  .github/workflows/build.yml
Labels: actions

#249 add theme selection to setup wizard
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/ui/MainWindow.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
  launcher/ui/setupwizard/SetupWizard.cpp
  launcher/ui/setupwizard/ThemeWizardPage.cpp
  launcher/ui/setupwizard/ThemeWizardPage.h
  launcher/ui/setupwizard/ThemeWizardPage.ui
  launcher/ui/themes/CustomTheme.cpp
  launcher/ui/themes/ITheme.cpp
  launcher/ui/themes/ITheme.h
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/SystemTheme.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
  launcher/ui/widgets/ThemeCustomizationWidget.cpp
  launcher/ui/widgets/ThemeCustomizationWidget.h
  launcher/ui/widgets/ThemeCustomizationWidget.ui
Labels: enhancement

#730 Revert "Merge pull request #729 from DioEgizio/fix-mac-openssl3-failing"
  .github/workflows/build.yml
Labels: actions

#731 Fix random ResourceFolderModel test failures on some Windows builds
  launcher/FileSystem.cpp
Labels: bug, simple change, actions, Windows

#685 Allow selecting a default account to use with an instance
  launcher/LaunchController.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.h
  launcher/ui/pages/instance/InstanceSettingsPage.ui
Labels: enhancement

#743 Don't fail mod parsing when encountering invalid modListVersion
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
Labels: bug, simple change

#746 2023 :)
  COPYING.md
Labels: simple change

#766 make MainWindow cat update instantly
  launcher/Application.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/pages/global/LauncherPage.cpp
Labels: enhancement

#772 Fix: zlib fallback not working
  CMakeLists.txt
Labels: bug

#758 fix crash when a lot of tasks get ran concurrently
  launcher/tasks/ConcurrentTask.cpp
  tests/Task_test.cpp
Labels: bug, simple change

#781 fix: let jars be found from inside build dir for debug builds
  launcher/Application.cpp
Labels: enhancement

#458 Remove old updater code
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/UpdateController.cpp
  launcher/UpdateController.h
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/modrinth/ModrinthAPI.cpp
  launcher/net/MetaCacheSink.cpp
  launcher/net/PasteUpload.cpp
  launcher/ui/GuiUtil.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/ExportInstanceDialog.cpp
  launcher/ui/dialogs/UpdateDialog.cpp
  launcher/ui/dialogs/UpdateDialog.h
  launcher/ui/dialogs/UpdateDialog.ui
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.h
  launcher/ui/pages/global/LauncherPage.ui
  launcher/ui/pages/instance/LogPage.cpp
  launcher/ui/pages/instance/ScreenshotsPage.h
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/instance/WorldListPage.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.h
  launcher/updater/DownloadTask.cpp
  launcher/updater/DownloadTask.h
  launcher/updater/GoUpdate.cpp
  launcher/updater/GoUpdate.h
  launcher/updater/MacSparkleUpdater.h
  launcher/updater/MacSparkleUpdater.mm
  launcher/updater/UpdateChecker.cpp
  launcher/updater/UpdateChecker.h
Labels: enhancement

#784 Don't create two smart pointers for the same raw pointer in ResourceFolderModel
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/tasks/ConcurrentTask.cpp
Labels: bug, simple change

#779 fix: Undo zlibs file rename when using bundled zlib
  CMakeLists.txt
Labels: enhancement

#724 Port the MainWindow ui to a .ui file
  launcher/CMakeLists.txt
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
  launcher/ui/widgets/WideBar.cpp
  launcher/ui/widgets/WideBar.h
Labels: bug, enhancement

#795 Fix: fix some regressions in the main window
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.ui
Labels: bug, simple change
