Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-07, with the labels that each got.

#1292 Removed logs from instance export
  launcher/FileIgnoreProxy.cpp
  launcher/FileIgnoreProxy.h
  launcher/ui/dialogs/ExportInstanceDialog.cpp
  launcher/ui/dialogs/ExportMrPackDialog.cpp
Labels: enhancement

#1298 Fix compiling on OpenBSD
  launcher/FileSystem.cpp
Labels: bug

#1232 ScreenshotsPage fixes
  launcher/ui/pages/instance/ScreenshotsPage.cpp
Labels: bug

#1304 flake.lock: Update
  flake.lock
Labels: simple change, Linux

#1284 fix(filesystem): track failed copies and clones
  launcher/FileSystem.cpp
  launcher/FileSystem.h
Labels: bug, simple change

#1310 feat(actions): add update-flake-lock
  .github/workflows/update-flake.yml
Labels: simple change, actions, Linux

#1128 Fix implicit fallthrough issues in codebase
  launcher/LaunchController.cpp
  launcher/VersionProxyModel.cpp
  launcher/meta/Index.cpp
  launcher/minecraft/auth/AccountList.cpp
  launcher/minecraft/auth/Yggdrasil.cpp
  launcher/minecraft/mod/DataPack.cpp
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/Resource.cpp
  launcher/minecraft/mod/ResourcePack.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/translations/TranslationsModel.cpp
  launcher/ui/instanceview/AccessibleInstanceView.cpp
  launcher/ui/pages/instance/WorldListPage.cpp
  launcher/ui/setupwizard/JavaWizardPage.cpp
  libraries/murmur2/src/MurmurHash2.cpp
Labels: enhancement

#1325 Validate Meta URL
  launcher/Application.cpp
  launcher/ui/pages/global/APIPage.cpp
Labels: enhancement, simple change

#1120 Added visit mod's page
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/Mod.h
  launcher/modplatform/ModIndex.cpp
  launcher/modplatform/ModIndex.h
  launcher/ui/pages/instance/ExternalResourcesPage.ui
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  launcher/ui/widgets/InfoFrame.cpp
  launcher/ui/widgets/InfoFrame.h
Labels: enhancement, ui rework

#1302 fix: segfault in progress dialog
  launcher/ui/dialogs/ProgressDialog.cpp
Labels: bug, simple change

#1329 fix(progress dialog): if there is a parent center on creation
  launcher/ui/dialogs/ProgressDialog.cpp
  launcher/ui/dialogs/ProgressDialog.h
Labels: bug, simple change

#1321 Optional mods in mrpack export
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
Labels: enhancement

#1332 Fix crash when editing instance and prevent similar crashes in future
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/widgets/WideBar.cpp
Labels: bug

#1241 Allow editing of running instances
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.h
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.h
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  launcher/ui/pages/instance/ResourcePackPage.cpp
  launcher/ui/pages/instance/ShaderPackPage.cpp
  launcher/ui/pages/instance/TexturePackPage.cpp
Labels: enhancement

#1337 fix(actions): give update-flake content write perms
  .github/workflows/update-flake.yml
Labels: simple change, actions

#1334 LiteMod downloading
  launcher/minecraft/PackProfile.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
Labels: enhancement

#1081 Shortcuts on macOS
  launcher/FileSystem.cpp
  launcher/ui/MainWindow.cpp
Labels: enhancement, macOS

#1331 Fix updating trashing resources
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/Mod.h
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/Resource.cpp
  launcher/minecraft/mod/Resource.h
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp
Labels: bug

#1333 Don't allow edit of NullInstances
  launcher/ui/MainWindow.cpp
Labels: bug, simple change

#1350 fixed crash if no version is loaded on managed page
  launcher/ui/pages/instance/ManagedPackPage.cpp
Labels: bug, simple change

#1345 feat:Added option to use system locale
  launcher/Application.cpp
  launcher/translations/TranslationsModel.cpp
  launcher/translations/TranslationsModel.h
  launcher/ui/widgets/LanguageSelectionWidget.cpp
  launcher/ui/widgets/LanguageSelectionWidget.h
Labels: enhancement

#1352 Do not reset shared pointer if it's already empty
  launcher/modplatform/EnsureMetadataTask.cpp
Labels: bug, simple change

#1335 fix(flame install): don't assume .zip is a resource pack. default to mod
  launcher/minecraft/mod/tasks/LocalResourceParse.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/PackManifest.cpp
Labels: bug, simple change

#1306 Enable address sanitizer in debug builds
  CMakeLists.txt
  tests/FileSystem_test.cpp
  tests/ResourceModel_test.cpp
  tests/Task_test.cpp
  tests/Version_test.cpp
Labels: bug, enhancement, simple change

#1336 packaging: fix duplicate share directories (use only lowercase)
  CMakeLists.txt
  launcher/Application.cpp
Labels: simple change, packaging

#1351 fixed substatus on ftb_import
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.h
Labels: bug, simple change

#1368 make FileResolvingTask accept empty modlist
  launcher/modplatform/flame/FileResolvingTask.cpp
Labels: bug

#1369 auto focus search line on resource download
  launcher/ui/pages/modplatform/ResourcePage.cpp
Labels: enhancement, simple change

#1246 Mod List Export To Text
  launcher/CMakeLists.txt
  launcher/modplatform/helpers/ExportToModList.cpp
  launcher/modplatform/helpers/ExportToModList.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
  launcher/ui/dialogs/ExportToModListDialog.cpp
  launcher/ui/dialogs/ExportToModListDialog.h
  launcher/ui/dialogs/ExportToModListDialog.ui
Labels: enhancement, needs-testing

#1010 add global .editorconfig for doxygen comment style
  .editorconfig
Labels: simple change

#1373 Add Backport action
  .github/workflows/backport.yml
Labels: actions

#1276 Print build platform on launch
  .github/workflows/build.yml
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/Application.cpp
  launcher/LaunchController.cpp
  launcher/ui/pages/global/AccountListPage.cpp
Labels: enhancement, actions, packaging, backport release-7.x

#1357 feat: add toggle for quilt beacon
  launcher/Application.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/ui/pages/global/MinecraftPage.cpp
  launcher/ui/pages/global/MinecraftPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.ui
Labels: enhancement, upstream, backport release-7.x

#1286 update instanceView group header to more modern style
  launcher/Application.cpp
  launcher/Application.h
  launcher/ui/instanceview/VisualGroup.cpp
  launcher/ui/instanceview/VisualGroup.h
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/setupwizard/ThemeWizardPage.cpp
  launcher/ui/setupwizard/ThemeWizardPage.h
  launcher/ui/themes/CustomTheme.cpp
  launcher/ui/themes/CustomTheme.h
  launcher/ui/themes/ITheme.cpp
  launcher/ui/themes/ITheme.h
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/SystemTheme.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
  launcher/ui/widgets/ThemeCustomizationWidget.cpp
  launcher/ui/widgets/ThemeCustomizationWidget.h
Labels: enhancement, simple change, ui rework

#1387 Check if any modloader is installed
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change, backport release-7.x

#1378 Added progress bar to Prism instance export
  launcher/MMCZip.cpp
  launcher/MMCZip.h
  launcher/ui/dialogs/ExportInstanceDialog.cpp
  launcher/ui/dialogs/ExportInstanceDialog.h
Labels: enhancement

#1362 Fix warning
  launcher/BaseVersion.h
  launcher/java/JavaInstall.cpp
  launcher/java/JavaInstall.h
Labels: simple change, backport release-7.x

#1397 Make Launch Offline not launch online in 1.6+
  launcher/minecraft/auth/AuthSession.cpp
Labels: bug, backport release-7.x

#1372 chore(nix): update lockfile
  flake.lock
Labels: simple change, packaging, Linux, backport release-7.x

#1253 Added CatPacks
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/ui/instanceview/InstanceView.cpp
  launcher/ui/setupwizard/ThemeWizardPage.cpp
  launcher/ui/themes/CatPack.cpp
  launcher/ui/themes/CatPack.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
  launcher/ui/widgets/ThemeCustomizationWidget.cpp
  launcher/ui/widgets/ThemeCustomizationWidget.h
Labels: enhancement

#1426 Fix token "0" being replaced
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/auth/AccountData.cpp
  launcher/minecraft/auth/MinecraftAccount.cpp
Labels: bug, backport release-7.x

#1427 Add some missing strings to translations
  launcher/ui/pages/global/APIPage.ui
  launcher/ui/pages/global/JavaPage.ui
  launcher/ui/pages/global/LauncherPage.h
  launcher/ui/pages/global/MinecraftPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.ui
Labels: bug, simple change, backport release-7.x

#1434 start using garnix ci for nix
  .github/workflows/build.yml
  garnix.yaml
Labels: actions, packaging, Linux

#1447 fix: typo in task.h
  launcher/InstanceImportTask.cpp
  launcher/InstanceList.cpp
  launcher/ResourceDownloadTask.cpp
  launcher/launch/steps/Update.cpp
  launcher/minecraft/MinecraftLoadAndCheck.cpp
  launcher/minecraft/MinecraftUpdate.cpp
  launcher/minecraft/update/AssetUpdateTask.cpp
  launcher/minecraft/update/FMLLibrariesTask.cpp
  launcher/minecraft/update/LibrariesTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlamePackExportTask.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/technic/SingleZipPackInstallTask.cpp
  launcher/modplatform/technic/SolderPackInstallTask.cpp
  launcher/tasks/Task.cpp
  launcher/tasks/Task.h
Labels: simple change, backport release-7.x

#1446 disable darwin in flake + cleanup garnix.yaml + fix markdownlint warnings
  CONTRIBUTING.md
  garnix.yaml
  libraries/README.md
  nix/NIX.md
  nix/default.nix
Labels: documentation, simple change, actions, packaging, Linux, backport release-7.x

#1437 Ignore cache files by default when exporting instances
  launcher/ui/dialogs/ExportInstanceDialog.cpp
  launcher/ui/dialogs/ExportPackDialog.cpp
Labels: enhancement, backport release-7.x

#1449 Reintroduce parsing of INI files
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/settings/INIFile.cpp
  launcher/settings/INIFile.h
Labels: enhancement, changelog:fixed
