Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-05, with the labels that each got.

#950 fix: divide minecraftpage into tabs
  launcher/ui/pages/global/MinecraftPage.cpp
  launcher/ui/pages/global/MinecraftPage.ui
Labels: bug, simple change

#961 Better Tasks
  CMakeLists.txt
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/InstanceImportTask.cpp
  launcher/InstanceList.cpp
  launcher/MMCTime.cpp
  launcher/MMCTime.h
  launcher/ResourceDownloadTask.cpp
  launcher/StringUtils.cpp
  launcher/StringUtils.h
  launcher/launch/steps/Update.cpp
  launcher/minecraft/MinecraftLoadAndCheck.cpp
  launcher/minecraft/MinecraftUpdate.cpp
  launcher/minecraft/update/AssetUpdateTask.cpp
  launcher/minecraft/update/FMLLibrariesTask.cpp
  launcher/minecraft/update/LibrariesTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/technic/SingleZipPackInstallTask.cpp
  launcher/modplatform/technic/SolderPackInstallTask.cpp
  launcher/net/Download.cpp
  launcher/net/Download.h
  launcher/net/FileSink.cpp
  launcher/net/FileSink.h
  launcher/net/HttpMetaCache.cpp
  launcher/net/HttpMetaCache.h
  launcher/net/Logging.cpp
  launcher/net/Logging.h
  launcher/net/MetaCacheSink.cpp
  launcher/net/MetaCacheSink.h
  launcher/net/NetAction.h
  launcher/net/NetJob.cpp
  launcher/net/NetJob.h
  launcher/net/PasteUpload.cpp
  launcher/net/PasteUpload.h
  launcher/net/Upload.cpp
  launcher/net/Upload.h
  launcher/qtlogging.ini
  launcher/tasks/ConcurrentTask.cpp
  launcher/tasks/ConcurrentTask.h
  launcher/tasks/MultipleOptionsTask.cpp
  launcher/tasks/MultipleOptionsTask.h
  launcher/tasks/SequentialTask.cpp
  launcher/tasks/SequentialTask.h
  launcher/tasks/Task.cpp
  launcher/tasks/Task.h
  launcher/ui/dialogs/ProgressDialog.cpp
  launcher/ui/dialogs/ProgressDialog.h
  launcher/ui/dialogs/ProgressDialog.ui
  launcher/ui/widgets/ProgressWidget.cpp
  launcher/ui/widgets/SubTaskProgressBar.cpp
  launcher/ui/widgets/SubTaskProgressBar.h
  launcher/ui/widgets/SubTaskProgressBar.ui
  program_info/win_install.nsi.in
  tests/Task_test.cpp
Labels: enhancement

#1007 Fix: signal/slot macro -> func pointer & network fixes
  launcher/JavaCommon.cpp
  launcher/LoggedProcess.cpp
  launcher/icons/IconList.cpp
  launcher/java/JavaChecker.cpp
  launcher/java/JavaCheckerJob.cpp
  launcher/launch/steps/Update.cpp
  launcher/minecraft/WorldList.cpp
  launcher/minecraft/auth/AuthRequest.cpp
  launcher/minecraft/auth/MinecraftAccount.cpp
  launcher/minecraft/auth/steps/XboxUserStep.cpp
  launcher/minecraft/services/CapeChange.cpp
  launcher/minecraft/services/CapeChange.h
  launcher/minecraft/services/SkinDelete.cpp
  launcher/minecraft/services/SkinDelete.h
  launcher/minecraft/services/SkinUpload.cpp
  launcher/minecraft/services/SkinUpload.h
  launcher/net/Download.cpp
  launcher/net/Download.h
  launcher/net/HttpMetaCache.cpp
  launcher/net/NetAction.h
  launcher/net/Upload.cpp
  launcher/net/Upload.h
  launcher/screenshots/ImgurAlbumCreation.cpp
  launcher/screenshots/ImgurUpload.cpp
  launcher/settings/SettingsObject.cpp
  launcher/tools/JProfiler.cpp
  launcher/tools/JVisualVM.cpp
  launcher/ui/pages/instance/VersionPage.cpp
Labels: bug, simple change

#1080 Update social links
  CMakeLists.txt
  README.md
  program_info/org.prismlauncher.PrismLauncher.metainfo.xml.in
Labels: simple change

#1088 chore: update to Qt 6.5.1
  .github/workflows/build.yml
Labels: simple change

#1083 Fix: memory leaks in develop
  launcher/InstanceCreationTask.h
  launcher/InstanceImportTask.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/minecraft/WorldList.cpp
  launcher/minecraft/WorldList.h
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/ResourcePackFolderModel.h
  launcher/minecraft/mod/ShaderPackFolderModel.h
  launcher/minecraft/mod/TexturePackFolderModel.cpp
  launcher/minecraft/mod/TexturePackFolderModel.h
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FileResolvingTask.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/helpers/NetworkResourceAPI.cpp
  launcher/net/Download.cpp
  launcher/tasks/ConcurrentTask.cpp
  launcher/tasks/Task.cpp
  launcher/tasks/Task.h
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/ResourceModel.cpp
  launcher/ui/pages/modplatform/ResourceModel.h
  launcher/ui/pages/modplatform/ResourcePackModel.cpp
  launcher/ui/pages/modplatform/ResourcePackPage.h
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/ShaderPackModel.cpp
  launcher/ui/pages/modplatform/ShaderPackPage.h
  launcher/ui/widgets/PageContainer.cpp
  libraries/katabasis/src/Reply.cpp
  tests/ResourceFolderModel_test.cpp
  tests/ResourceModel_test.cpp
Labels: enhancement

#1034 fix: remove poly from desktop tags
  program_info/org.prismlauncher.PrismLauncher.desktop.in
Labels: enhancement, simple change
