Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-11, with the labels that each got.

#1766 Fix group issues
  launcher/InstanceList.cpp
  launcher/InstanceList.h
Labels: bug

#1782 Add warning when removing an account
  launcher/ui/pages/global/AccountListPage.cpp
Labels: enhancement, simple change, changelog:added

#1783 Fixed visual bug with Modlist export
  launcher/ui/dialogs/ExportToModListDialog.cpp
  launcher/ui/dialogs/ExportToModListDialog.ui
Labels: bug, simple change, changelog:merged

#1797 [Linux] Fix loading MangoHud
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change, changelog:fixed

#1788 Updated the readme
  README.md
Labels: documentation, simple change, changelog:omit

#1772 Fix crash with mod icon caching
  launcher/MTPixmapCache.h
Labels: bug, simple change, changelog:fixed

#1760 Localize sorting options for resource and shader packs
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/modrinth/ModrinthAPI.cpp
Labels: bug, simple change, changelog:fixed

#1796 Added Global Dependenicies toggle
  launcher/Application.cpp
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
  launcher/ui/pages/instance/ModFolderPage.cpp
Labels: enhancement, simple change, changelog:added

#1739 fixed squished mod icons
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/TexturePackFolderModel.cpp
Labels: bug, simple change, changelog:fixed

#1799 simplify microsoft login
  launcher/ui/dialogs/MSALoginDialog.cpp
Labels: enhancement, simple change, changelog:added

#1821 Only open/close groups on left button
  launcher/ui/instanceview/InstanceView.cpp
Labels: bug, changelog:fixed

#1828 Fixed modrinth sort swap
  launcher/modplatform/modrinth/ModrinthAPI.cpp
Labels: bug, simple change, changelog:fixed

#1798 [Windows] Autodetect Java from the Microsoft Store version of the official launcher
  launcher/java/JavaUtils.cpp
Labels: bug, simple change, changelog:merged

#1704 Add game category to generated Linux shortcuts
  launcher/FileSystem.cpp
Labels: enhancement, simple change, changelog:added

#1849 Made resource columns resizable
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/TexturePackFolderModel.cpp
  launcher/ui/pages/global/AccountListPage.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/widgets/ModListView.cpp
Labels: enhancement, simple change, changelog:added

#1746 separated dependecy check from mod update
  launcher/ui/dialogs/ChooseProviderDialog.h
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/dialogs/ModUpdateDialog.h
  launcher/ui/pages/instance/ExternalResourcesPage.ui
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
Labels: enhancement, simple change, changelog:changed

#1860 Add custom env vars to pre/post launch commands
  launcher/minecraft/MinecraftInstance.cpp
Labels: enhancement, simple change, changelog:added

#1869 Added more open folder actions
  launcher/DesktopServices.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
Labels: enhancement, simple change, changelog:added, changelog:changed

#1347 Reduce minimum memory amounts
  launcher/ui/pages/global/JavaPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.ui
  launcher/ui/widgets/JavaSettingsWidget.cpp
Labels: enhancement, simple change, changelog:changed

#1880 Fixed open link on settings page
  launcher/ui/pages/global/APIPage.ui
Labels: bug, simple change, changelog:fixed

#1762 Remove top-level `const` qualifiers in function declarations
  .clang-tidy
  launcher/DataMigrationTask.h
  launcher/InstanceImportTask.cpp
  launcher/InstanceImportTask.h
  launcher/MMCZip.cpp
  launcher/MMCZip.h
  launcher/RecursiveFileSystemWatcher.h
  launcher/ResourceDownloadTask.h
  launcher/VersionProxyModel.h
  launcher/icons/IconList.h
  launcher/meta/Index.h
  launcher/meta/Version.h
  launcher/meta/VersionList.h
  launcher/minecraft/OneSixVersionFormat.h
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile.h
  launcher/minecraft/ProfileUtils.cpp
  launcher/minecraft/ProfileUtils.h
  launcher/minecraft/auth/AccountList.h
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/minecraft/mod/tasks/GetModDependenciesTask.h
  launcher/modplatform/modrinth/ModrinthPackExportTask.h
  launcher/modplatform/technic/TechnicPackProcessor.h
  launcher/ui/dialogs/ModUpdateDialog.h
  launcher/ui/dialogs/ResourceDownloadDialog.h
  launcher/ui/instanceview/InstanceView.h
  launcher/ui/pages/instance/OtherLogsPage.h
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/ResourceModel.h
  launcher/ui/pages/modplatform/ResourcePage.h
  launcher/ui/pages/modplatform/ShaderPackPage.h
  launcher/ui/pages/modplatform/flame/FlameModel.h
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.h
  launcher/ui/widgets/LanguageSelectionWidget.cpp
  launcher/ui/widgets/LanguageSelectionWidget.h
Labels: changelog:fixed

#1589 Fully reload the instance list once the folder is changed
  launcher/InstanceList.cpp
Labels: bug, simple change, changelog:fixed

#1815 Make sure MangoHud libs are present
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change, changelog:fixed, changelog:merged

#1852 Added warning on mods update while running
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ModFolderPage.cpp
Labels: enhancement, simple change, changelog:added

#1843 Remove the dep if it fails for any reason
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
Labels: bug, simple change, changelog:fixed

#1871 changed prism aniversary
  launcher/ui/themes/CatPack.cpp
Labels: enhancement, simple change, changelog:omit

#1882 [Linux] Added warning when /tmp directory is mounted with noexec
  launcher/Application.cpp
Labels: changelog:added
