Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-08, with the labels that each got.

#1474 Update copyright year
  CMakeLists.txt
  launcher/ui/dialogs/AboutDialog.cpp
Labels: changelog:fixed

#1445 feat: removed flame quilt warning
  launcher/ui/MainWindow.cpp
Labels: enhancement, needs-testing

#1294 Add Snap Support
  launcher/Application.cpp
  launcher/DesktopServices.cpp
  launcher/DesktopServices.h
Labels: enhancement, actions, packaging, Linux

#1359 Add FTB App import
  flatpak/org.prismlauncher.PrismLauncher.yml
  launcher/CMakeLists.txt
  launcher/modplatform/import_ftb/PackHelpers.cpp
  launcher/modplatform/import_ftb/PackHelpers.h
  launcher/modplatform/import_ftb/PackInstallTask.cpp
  launcher/modplatform/import_ftb/PackInstallTask.h
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.cpp
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.h
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.ui
  launcher/ui/pages/modplatform/import_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/import_ftb/ListModel.h
Labels: enhancement, changelog:added

#1476 Don't reset meta URL on launch
  launcher/Application.cpp
Labels: bug, simple change, changelog:fixed

#1391 Simplify flame and modrinth exports
  launcher/modplatform/flame/FlamePackExportTask.cpp
  launcher/modplatform/flame/FlamePackExportTask.h
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
  launcher/modplatform/modrinth/ModrinthPackExportTask.h
Labels: enhancement, changelog:changed

#1452 Allow disabling bundling and Sparkle updater when building
  CMakeLists.txt
  launcher/Application.cpp
  launcher/CMakeLists.txt
Labels: enhancement, macOS, packaging, changelog:changed

#1483 [macOS,Windows] Update to Qt 6.5.2
  .github/workflows/build.yml
Labels: actions, changelog:changed

#1370 Fix links and add images to modpack changelogs
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/instance/ManagedPackPage.ui
Labels: simple change, ui rework, changelog:changed

#1456 Preserve file extension of instance icon when importing
  launcher/icons/IconList.cpp
  launcher/icons/IconList.h
  launcher/icons/IconUtils.cpp
  launcher/icons/IconUtils.h
  launcher/icons/MMCIcon.cpp
  launcher/icons/MMCIcon.h
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlListModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
Labels: bug, changelog:fixed

#1464 [Windows] Fix attaching logs to console
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/WindowsConsole.cpp
  launcher/WindowsConsole.h
  launcher/filelink/FileLink.cpp
Labels: bug, Windows, changelog:fixed

#1324 Some random small ui tweaks :p
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/TexturePackFolderModel.cpp
  launcher/ui/dialogs/SkinUploadDialog.ui
  launcher/ui/pages/global/ExternalToolsPage.ui
  launcher/ui/pages/global/JavaPage.ui
  launcher/ui/pages/global/LauncherPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.ui
  launcher/ui/widgets/PageContainer_p.h
  launcher/ui/widgets/WideBar.cpp
Labels: enhancement, ui rework

#1230 Revamp loader installation UI
  launcher/CMakeLists.txt
  launcher/Filter.cpp
  launcher/Filter.h
  launcher/resources/multimc/128x128/instances/forge.png
  launcher/resources/multimc/128x128/instances/liteloader.png
  launcher/resources/multimc/multimc.qrc
  launcher/resources/multimc/scalable/instances/fabricmc.svg
  launcher/resources/multimc/scalable/instances/quiltmc.svg
  launcher/ui/InstanceWindow.cpp
  launcher/ui/InstanceWindow.h
  launcher/ui/dialogs/InstallLoaderDialog.cpp
  launcher/ui/dialogs/InstallLoaderDialog.h
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.h
  launcher/ui/dialogs/VersionSelectDialog.cpp
  launcher/ui/dialogs/VersionSelectDialog.h
  launcher/ui/pages/BasePageContainer.h
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/VersionPage.h
  launcher/ui/pages/instance/VersionPage.ui
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/widgets/JavaSettingsWidget.cpp
  launcher/ui/widgets/PageContainer.cpp
  launcher/ui/widgets/PageContainer.h
  launcher/ui/widgets/VersionSelectWidget.cpp
  launcher/ui/widgets/VersionSelectWidget.h
Labels: enhancement, question, changelog:changed

#1512 Fix importing Quilt/Fabric packs from CurseForge
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
Labels: bug, simple change, changelog:fixed

#1517 Don't enable address sanitizer in debug builds by default
  CMakeLists.txt
Labels: changelog:changed

#1518 Don't enable address sanitizer in debug builds by default (develop)
  CMakeLists.txt
Labels: simple change, changelog:merged

#1467 Update Nix docs
  nix/NIX.md
  nix/README.md
Labels: packaging, Linux, changelog:merged

#1462 chore(actions): add new labels to update-flake
  .github/workflows/update-flake.yml
Labels: simple change, actions, changelog:omit

#1516 Connect the aborted signal in concurent task
  launcher/tasks/ConcurrentTask.cpp
Labels: bug, simple change, changelog:fixed

#1407 Add support for multiple custom icon themes and improve UX around themes
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/DesktopServices.cpp
  launcher/resources/multimc/index.theme
  launcher/resources/pe_blue/index.theme
  launcher/resources/pe_colored/index.theme
  launcher/resources/pe_dark/index.theme
  launcher/resources/pe_light/index.theme
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
  launcher/ui/instanceview/InstanceView.cpp
  launcher/ui/setupwizard/ThemeWizardPage.cpp
  launcher/ui/themes/IconTheme.cpp
  launcher/ui/themes/IconTheme.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
  launcher/ui/widgets/ThemeCustomizationWidget.cpp
  launcher/ui/widgets/ThemeCustomizationWidget.h
  launcher/ui/widgets/ThemeCustomizationWidget.ui
Labels: enhancement, changelog:changed

#1508 Don't omit empty lines in log output
  launcher/LoggedProcess.cpp
Labels: bug, changelog:fixed

#1513 Fix transparency in skin icon
  launcher/SkinUtils.cpp
  launcher/minecraft/auth/MinecraftAccount.cpp
Labels: bug, changelog:fixed

#1523 Fix crash when installing some ATLauncher packs
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
Labels: bug, simple change, changelog:fixed

#981 CurseForge URL handling
  cmake/MacOSXBundleInfo.plist.in
  launcher/Application.cpp
  launcher/Application.h
  launcher/InstanceImportTask.cpp
  launcher/InstanceImportTask.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/dialogs/NewInstanceDialog.h
  launcher/ui/pages/modplatform/ImportPage.cpp
  launcher/ui/pages/modplatform/ImportPage.h
  launcher/ui/pages/modplatform/ImportPage.ui
  program_info/org.prismlauncher.PrismLauncher.desktop.in
  program_info/win_install.nsi.in
Labels: bug, enhancement, changelog:added

#1392 Implement GLFW/OpenAL override by defining and auto-detecting paths to library files
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/Application.cpp
  launcher/Application.h
  launcher/MangoHud.cpp
  launcher/MangoHud.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/launch/ExtractNatives.cpp
  launcher/ui/pages/global/MinecraftPage.cpp
  launcher/ui/pages/global/MinecraftPage.h
  launcher/ui/pages/global/MinecraftPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.h
  launcher/ui/pages/instance/InstanceSettingsPage.ui
Labels: enhancement, needs-testing, changelog:changed

#1535 Fix browse button size in Skin Upload dialog
  launcher/ui/dialogs/SkinUploadDialog.ui
Labels: bug, simple change, changelog:merged

#1498 Add NeoForge support
  launcher/minecraft/PackProfile.cpp
  launcher/modplatform/ResourceAPI.h
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlamePackExportTask.cpp
  launcher/modplatform/import_ftb/PackHelpers.cpp
  launcher/modplatform/import_ftb/PackInstallTask.cpp
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.h
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
  launcher/resources/multimc/multimc.qrc
  launcher/resources/multimc/scalable/instances/neoforged.svg
  launcher/ui/dialogs/InstallLoaderDialog.cpp
  launcher/ui/pages/modplatform/CustomPage.cpp
  launcher/ui/pages/modplatform/CustomPage.ui
Labels: enhancement, blocked, changelog:added

#1320 Combine launch buttons in instance window, persist profiler
  launcher/Application.cpp
  launcher/Application.h
  launcher/BaseInstance.cpp
  launcher/BaseInstance.h
  launcher/LaunchController.cpp
  launcher/NullInstance.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/ui/InstanceWindow.cpp
  launcher/ui/InstanceWindow.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
  launcher/ui/pages/instance/ServersPage.cpp
Labels: enhancement, changelog:changed

#1541 feat:neoforge can download forge mods
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/modrinth/ModrinthAPI.h
Labels: enhancement, simple change, changelog:changed

#1547 Remove Quilt Beacon toggle
  launcher/Application.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/ui/pages/global/MinecraftPage.cpp
  launcher/ui/pages/global/MinecraftPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.ui
Labels: changelog:removed

#1485 [macOS] Add macOS support to Nix
  nix/default.nix
  nix/distribution.nix
  nix/package.nix
Labels: macOS, packaging, changelog:added

#1551 Replace references to "Minecraft account"
  launcher/ui/MainWindow.cpp
  launcher/ui/pages/global/AccountListPage.cpp
  launcher/ui/pages/instance/VersionPage.cpp
Labels: changelog:fixed

#1557 added check for valid query items in curse url install
  launcher/ui/MainWindow.cpp
Labels: bug, simple change, changelog:merged

#1556 Gracefully handle invalid cache metadata
  launcher/net/HttpMetaCache.cpp
Labels: bug, simple change, changelog:fixed

#1548 Reset status label when deleting instance
  launcher/ui/MainWindow.cpp
Labels: bug, simple change, changelog:fixed

#1552 Don't update Java minimum memory based on maximum memory allocation
  launcher/ui/pages/global/JavaPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/widgets/JavaSettingsWidget.cpp
Labels: bug, simple change, changelog:changed

#1561 Miscellaneous Nix changes
  .envrc
  launcher/Version.h
  launcher/launch/LogModel.h
  launcher/ui/MainWindow.h
  launcher/ui/pages/instance/ServersPage.cpp
  libraries/LocalPeer/src/LocalPeer.cpp
  nix/dev.nix
  tests/FileSystem_test.cpp
Labels: changelog:omit

#1532 feat:added flame install mod metadata
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/ui/MainWindow.cpp
Labels: enhancement, simple change, changelog:merged

#1536 Allow showing playtime in hours
  launcher/Application.cpp
  launcher/MMCTime.cpp
  launcher/MMCTime.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/pages/global/MinecraftPage.cpp
  launcher/ui/pages/global/MinecraftPage.ui
Labels: enhancement, simple change, changelog:added

#1560 Add suport for flame multiple loaders
  launcher/minecraft/ComponentUpdateTask.cpp
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile.h
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/minecraft/mod/tasks/GetModDependenciesTask.h
  launcher/modplatform/CheckUpdateTask.h
  launcher/modplatform/ModIndex.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/ResourceAPI.h
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/modplatform/flame/FlameCheckUpdate.h
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/flame/FlameModIndex.h
  launcher/modplatform/helpers/NetworkResourceAPI.cpp
  launcher/modplatform/import_ftb/PackHelpers.cpp
  launcher/modplatform/import_ftb/PackHelpers.h
  launcher/modplatform/import_ftb/PackInstallTask.cpp
  launcher/modplatform/modrinth/ModrinthAPI.cpp
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/modplatform/modrinth/ModrinthCheckUpdate.h
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.h
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/ShaderPackPage.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.cpp
  launcher/ui/pages/modplatform/flame/FlameResourcePages.cpp
  launcher/ui/pages/modplatform/flame/FlameResourcePages.h
  launcher/ui/pages/modplatform/modrinth/ModrinthResourceModels.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.h
Labels: bug, changelog:changed

#1575 More pack fixes
  launcher/FileIgnoreProxy.cpp
  launcher/ui/dialogs/ExportPackDialog.cpp
Labels: bug

#1539 Improvements to modpack UX
  launcher/modplatform/ResourceAPI.h
  launcher/modplatform/helpers/NetworkResourceAPI.cpp
  launcher/ui/pages/modplatform/ResourceModel.cpp
  launcher/ui/pages/modplatform/ResourceModel.h
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlFilterModel.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlListModel.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlPage.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlPage.ui
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.h
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.h
  launcher/ui/pages/modplatform/flame/FlamePage.ui
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.cpp
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.h
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.ui
  launcher/ui/pages/modplatform/import_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/import_ftb/ListModel.h
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.h
  launcher/ui/pages/modplatform/legacy_ftb/Page.cpp
  launcher/ui/pages/modplatform/legacy_ftb/Page.h
  launcher/ui/pages/modplatform/legacy_ftb/Page.ui
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.ui
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
  launcher/ui/pages/modplatform/technic/TechnicModel.h
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
  launcher/ui/pages/modplatform/technic/TechnicPage.h
  launcher/ui/pages/modplatform/technic/TechnicPage.ui
  launcher/ui/widgets/ProjectItem.cpp
Labels: enhancement, ui rework, changelog:changed
