Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-02, with the labels that each got.

#810 Better check file paths in mrpack import and json components
  launcher/minecraft/OneSixVersionFormat.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
Labels: bug

#804 Improve the reliability of the Task's stack overflow test
  tests/Task_test.cpp
Labels: bug, simple change

#813 Bump to 6.2
  CMakeLists.txt
Labels: simple change

#815 Fix component uid regex
  launcher/minecraft/OneSixVersionFormat.cpp
Labels: bug, simple change

#816 Bump to 6.3
  CMakeLists.txt
Labels: simple change

#803 fix: Improve MinGW ccache
  .github/workflows/build.yml
Labels: enhancement, actions, Windows

#802 Make the logger thread-safe
  launcher/Application.cpp
Labels: bug, simple change

#751 Improve Version Parsing to handle more separators
  launcher/Version.cpp
  launcher/Version.h
  tests/CMakeLists.txt
  tests/Version_test.cpp
  tests/testdata/Version/test_vectors.txt
Labels: bug, enhancement

#825 ensure command env vars use native path seperators
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change

#823 Java installations detection fix for Linux
  launcher/java/JavaUtils.cpp
Labels: bug, simple change, Linux

#819 Use /usr/bin/env bash in launch script
  launcher/Launcher.in
Labels: simple change

#832 Fix README.md typo
  README.md
Labels: simple change

#834 Replace potentially ReDOSable regex
  launcher/InstanceImportTask.cpp
Labels: bug, simple change

#841 Link license in the shield badge (README)
  README.md
Labels: simple change

#859 Add missing header to Application.cpp: Fix build failure on KISS Linux
  launcher/Application.cpp
Labels: simple change

#865 Add Windows codesigning
  .github/workflows/build.yml
  .github/workflows/trigger_builds.yml
  .github/workflows/trigger_release.yml
Labels: actions, Windows
