Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-09, with the labels that each got.

#1592 Fix opening files from curseforge:// and file:// links etc on linux
  program_info/org.prismlauncher.PrismLauncher.desktop.in
Labels: simple change, Linux, changelog:merged

#1574 Don't instantiate nixpkgs in Flake
  flake.nix
  nix/default.nix
  nix/dev.nix
  nix/distribution.nix
  nix/pkg/default.nix
  nix/pkg/wrapper.nix
Labels: packaging, Linux, changelog:changed

#1581 fix: remove -Wextra-semi
  cmake/CompilerWarnings.cmake
Labels: simple change

#1578 Enable antialiasing for mod and pack icons
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/ResourcePack.cpp
  launcher/minecraft/mod/TexturePack.cpp
Labels: bug, simple change, changelog:fixed

#1605 CurseForge shader downloading
  launcher/modplatform/flame/FlameAPI.h
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.h
  launcher/ui/pages/modplatform/flame/FlameResourcePages.cpp
  launcher/ui/pages/modplatform/flame/FlameResourcePages.h
Labels: enhancement

#1572 Added catpacks tests
  launcher/ui/themes/CatPack.cpp
  launcher/ui/themes/CatPack.h
  tests/CMakeLists.txt
  tests/CatPack_test.cpp
  tests/testdata/CatPacks/index.json
Labels: simple change, changelog:merged

#1618 filter source in flake & add controller support
  flake.lock
  flake.nix
  nix/distribution.nix
  nix/pkg/default.nix
  nix/pkg/wrapper.nix
Labels: packaging, Linux, changelog:added

#1655 Update links to Minecraft Wiki
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/mod/DataPack.cpp
  launcher/minecraft/mod/DataPack.h
  launcher/minecraft/mod/ResourcePack.cpp
  launcher/minecraft/mod/ResourcePack.h
  launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.cpp
  launcher/ui/widgets/InfoFrame.cpp
Labels: simple change, changelog:omit

#1643 Skip folders when updating mods
  launcher/ui/dialogs/ModUpdateDialog.cpp
Labels: changelog:changed

#1363 made the number of concurrent tasks configurable
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/modplatform/flame/FlamePackExportTask.cpp
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/net/NetJob.cpp
  launcher/net/NetJob.h
  launcher/tasks/ConcurrentTask.h
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ResourcePackPage.cpp
  launcher/ui/pages/instance/ShaderPackPage.cpp
  launcher/ui/pages/instance/TexturePackPage.cpp
  launcher/ui/pages/modplatform/ResourceModel.cpp
Labels: enhancement, changelog:added

#1263 feat:Update mods now fills missing dependencies
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/minecraft/mod/tasks/GetModDependenciesTask.h
  launcher/modplatform/CheckUpdateTask.h
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/dialogs/ModUpdateDialog.h
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
Labels: enhancement, changelog:added

#1666 [Linux] Use addOpenGLRunpath.driverLink in Nix wrapper
  nix/pkg/wrapper.nix
Labels: simple change, packaging, Linux, changelog:changed
