Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-12, with the labels that each got.

#1923 Add subtle line to instance group separator
  launcher/ui/instanceview/VisualGroup.cpp
Labels: simple change, changelog:changed

#1908 chore: update qt to qt 6.6.1
  .github/workflows/build.yml
Labels: actions, packaging, changelog:changed, backport release-8.x

#1857 fixed settings not reseting on save
  launcher/InstanceCopyTask.cpp
  launcher/settings/INIFile.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#1694 Improvements to concurrent task
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/modplatform/ResourceAPI.h
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/modplatform/flame/FlameCheckUpdate.h
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlamePackExportTask.cpp
  launcher/modplatform/helpers/NetworkResourceAPI.cpp
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/net/NetJob.cpp
  launcher/net/NetJob.h
  launcher/screenshots/ImgurUpload.cpp
  launcher/tasks/ConcurrentTask.cpp
  launcher/tasks/ConcurrentTask.h
  launcher/tasks/MultipleOptionsTask.cpp
  launcher/tasks/MultipleOptionsTask.h
  launcher/tasks/SequentialTask.cpp
  launcher/tasks/SequentialTask.h
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/pages/modplatform/ResourceModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
  launcher/ui/widgets/VariableSizedImageObject.cpp
  tests/Task_test.cpp
Labels: bug, needs-testing, changelog:fixed, backport release-8.x

#1732 feat: added managed pack page for packs created from file
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/ui/pages/instance/ManagedPackPage.cpp
Labels: bug, simple change, changelog:merged, backport release-8.x

#1738 removed some unused stuff
  launcher/ui/dialogs/AboutDialog.h
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/VersionPage.h
Labels: simple change, changelog:omit, backport release-8.x

#1712 ensure totalTimePlayed is always greater than 0
  launcher/BaseInstance.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#1960 Minor spelling fixes
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/modplatform/ResourceModel.cpp
Labels: simple change, changelog:fixed

#1964 Don't log Microsoft refresh tokens
  launcher/qtlogging.ini
Labels: bug, simple change, changelog:fixed, backport release-8.x

#1978 Fixed openURL cast for resource
  launcher/ui/pages/modplatform/ResourcePage.cpp
Labels: bug, simple change, changelog:fixed
