Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-04, with the labels that each got.

#966 use ninja in nix builds
  nix/default.nix
Labels: enhancement, simple change, packaging

#965 fix: search for newer mangohud vulkan layers
  launcher/MangoHud.cpp
Labels: bug, simple change

#972 chore: update to qt 6.5.0 on macos
  .github/workflows/build.yml
Labels: simple change, actions, macOS

#968 Synchronize changes from Nixpkgs
  nix/default.nix
Labels: enhancement, simple change, packaging

#982 Do not apply system theme on launch
  launcher/Application.cpp
  launcher/Application.h
  launcher/ui/themes/ITheme.cpp
  launcher/ui/themes/ITheme.h
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/SystemTheme.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
Labels: bug, simple change

#983 chore: update Qt to 6.5.0 on Windows
  .github/workflows/build.yml
Labels: simple change, actions

#946 Watch Subdirectories of Watched folders in Blocked Mods Dialog
  launcher/Application.cpp
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement

#1025 Instance Description displays the last launch date
  launcher/minecraft/MinecraftInstance.cpp
Labels: enhancement, simple change

#1040 Remove FTB modpack support
  launcher/CMakeLists.txt
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.h
  launcher/modplatform/modpacksch/FTBPackManifest.cpp
  launcher/modplatform/modpacksch/FTBPackManifest.h
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/pages/modplatform/ftb/FtbFilterModel.cpp
  launcher/ui/pages/modplatform/ftb/FtbFilterModel.h
  launcher/ui/pages/modplatform/ftb/FtbListModel.cpp
  launcher/ui/pages/modplatform/ftb/FtbListModel.h
  launcher/ui/pages/modplatform/ftb/FtbPage.cpp
  launcher/ui/pages/modplatform/ftb/FtbPage.h
  launcher/ui/pages/modplatform/ftb/FtbPage.ui
Labels: simple change
