Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-03, with the labels that each got.

#735 Add button to import component JSONs
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile.h
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/VersionPage.h
  launcher/ui/pages/instance/VersionPage.ui
Labels: enhancement

#889 Fix failing zip extractions on develop
  launcher/InstanceImportTask.cpp
  launcher/InstanceImportTask.h
  launcher/MMCZip.cpp
Labels: bug

#895 Use makeShared for importing components
  launcher/minecraft/PackProfile.cpp
Labels: bug, simple change

#788 Add resource pack, texture pack and shader pack downloaders
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/meta/Version.cpp
  launcher/meta/Version.h
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.h
  launcher/ui/pages/instance/ResourcePackPage.cpp
  launcher/ui/pages/instance/ResourcePackPage.h
  launcher/ui/pages/instance/ShaderPackPage.cpp
  launcher/ui/pages/instance/ShaderPackPage.h
  launcher/ui/pages/instance/TexturePackPage.cpp
  launcher/ui/pages/instance/TexturePackPage.h
  launcher/ui/pages/modplatform/ResourceModel.h
  launcher/ui/pages/modplatform/ResourcePackModel.cpp
  launcher/ui/pages/modplatform/ResourcePackModel.h
  launcher/ui/pages/modplatform/ResourcePackPage.cpp
  launcher/ui/pages/modplatform/ResourcePackPage.h
  launcher/ui/pages/modplatform/ShaderPackModel.cpp
  launcher/ui/pages/modplatform/ShaderPackModel.h
  launcher/ui/pages/modplatform/ShaderPackPage.cpp
  launcher/ui/pages/modplatform/ShaderPackPage.h
  launcher/ui/pages/modplatform/TexturePackModel.cpp
  launcher/ui/pages/modplatform/TexturePackModel.h
  launcher/ui/pages/modplatform/TexturePackPage.h
  launcher/ui/pages/modplatform/flame/FlameResourceModels.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.h
  launcher/ui/pages/modplatform/flame/FlameResourcePages.cpp
  launcher/ui/pages/modplatform/flame/FlameResourcePages.h
  launcher/ui/pages/modplatform/modrinth/ModrinthResourceModels.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourceModels.h
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.h
Labels: enhancement

#857 Fix windows default apps
  program_info/win_install.nsi.in
Labels: bug, Windows

#853 NilLoader mod metadata support
  CMakeLists.txt
  launcher/CMakeLists.txt
  launcher/InstancePageProvider.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/minecraft/launch/ScanModFolders.cpp
  launcher/minecraft/launch/ScanModFolders.h
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/Resource.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  libraries/README.md
  libraries/qdcss/CMakeLists.txt
  libraries/qdcss/LICENSE
  libraries/qdcss/include/qdcss.h
  libraries/qdcss/src/qdcss.cpp
Labels: enhancement

#918 Switch to Qt 6 by default
  CMakeLists.txt
  flatpak/org.prismlauncher.PrismLauncher.yml
  nix/default.nix
  snap/snapcraft.yaml
Labels: simple change, packaging

#896 Allow custom Modrinth API token
  launcher/Application.cpp
  launcher/Application.h
  launcher/net/Download.cpp
  launcher/net/Upload.cpp
  launcher/ui/pages/global/APIPage.cpp
  launcher/ui/pages/global/APIPage.ui
Labels: enhancement, simple change

#929 Drop Snap packaging
  .github/workflows/build.yml
  snap/snapcraft.yaml
Labels: actions

#888 Improvements around Nix tooling
  .envrc
  .gitignore
  BUILD.md
  flake.lock
  flake.nix
  libraries/katabasis/acknowledgements.md
  nix/default.nix
  nix/flake-compat.nix
Labels: enhancement, packaging

#931 Add setting for downloads directory
  launcher/Application.cpp
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.h
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement

#937 chore: update qt6 to 6.4.3 on windows and macos
  .github/workflows/build.yml
Labels: simple change, actions, macOS, Windows, packaging

#945 Handle partial lines in LoggedProcess
  .gitignore
  launcher/LoggedProcess.cpp
  launcher/LoggedProcess.h
Labels: bug, simple change
