Repository PrismLauncher/PrismLauncher, pull requests merged in 2023-06, with the labels that each got.

#1086 fix: System theme colors on windows
  launcher/ui/themes/SystemTheme.cpp
Labels: bug, simple change, Windows

#1109 Validate input lengths on mrpack export
  launcher/ui/dialogs/ExportMrPackDialog.cpp
  launcher/ui/dialogs/ExportMrPackDialog.h
  launcher/ui/dialogs/ExportMrPackDialog.ui
Labels: simple change

#1100 Packaging: make windows nsis installer run the uninstaller for previous install
  program_info/win_install.nsi.in
Labels: packaging

#1108 fix(memory leak): cyclic refrence in translations model dl task
  launcher/translations/TranslationsModel.cpp
Labels: bug, simple change

#1093 Refactor Nix Flake
  default.nix
  flake.lock
  flake.nix
  nix/default.nix
  nix/dev.nix
  nix/distribution.nix
  nix/flake-compat.nix
  nix/package.nix
  renovate.json
Labels: packaging, Linux

#1101 Packaging: file manifest in portable install
  .github/workflows/build.yml
Labels: enhancement, packaging

#1115 fix: fix crash when selecting resource/texture/shader packs
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
Labels: bug, simple change

#1125 fix #1118 : use `filePath` not `path` on `QFileInfo`
  launcher/InstanceCopyTask.cpp
Labels: bug, simple change

#1111 Renamed requires
  launcher/meta/JsonFormat.cpp
  launcher/meta/Version.cpp
  launcher/meta/Version.h
  launcher/meta/VersionList.cpp
  launcher/minecraft/Component.cpp
  launcher/minecraft/OneSixVersionFormat.cpp
  launcher/minecraft/VersionFile.h
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.cpp
Labels: enhancement

#1151 feat: Make Konami Code a *bit* more obvious
  launcher/ui/MainWindow.cpp
Labels: enhancement

#1162 Add icons to export menu
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.ui
Labels: enhancement, simple change

#1140 CI: Exclude `.git` directory from the source code tarball
  .github/workflows/trigger_release.yml
Labels: enhancement, actions, packaging

#1174 Added migration for INI files
  launcher/settings/INIFile.cpp
  tests/INIFile_test.cpp
Labels: bug

#1145 Fixes some crashes regarding high network usage
  launcher/net/ByteArraySink.h
  launcher/tasks/ConcurrentTask.cpp
  launcher/ui/pages/modplatform/ResourcePage.cpp
Labels: bug, simple change

#1099 store logs in seperate directory
  launcher/Application.cpp
Labels: enhancement, simple change

#1067 feat: Don't hide the settings tab when an instance is running
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.h
Labels: enhancement, simple change

#1063 feat: Add the launcher root folder to the Folders menu
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
Labels: enhancement, simple change

#1159 fix(nix): use prismlauncher-unwrapped in devShell
  nix/dev.nix
Labels: bug, simple change, packaging

#1195 Add JavaVendor as an instance override
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change

#1198 Fix trailing space in instance name
  launcher/InstanceTask.cpp
Labels: bug, simple change

#1192 Added new migration for special characters
  launcher/settings/INIFile.cpp
  tests/INIFile_test.cpp
Labels: bug

#1135 Higlight installed mods in download dialog
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/ResourceModel.cpp
  launcher/ui/pages/modplatform/ResourceModel.h
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.h
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourceModels.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourceModels.h
  launcher/ui/widgets/ProjectItem.cpp
  launcher/ui/widgets/ProjectItem.h
Labels: enhancement

#1187 chore: bump to 8.0
  CMakeLists.txt
Labels: simple change

#1110 Add a search bar to version lists
  launcher/VersionProxyModel.cpp
  launcher/VersionProxyModel.h
  launcher/java/JavaInstallList.cpp
  launcher/ui/dialogs/VersionSelectDialog.cpp
  launcher/ui/widgets/JavaSettingsWidget.cpp
  launcher/ui/widgets/VersionListView.cpp
  launcher/ui/widgets/VersionSelectWidget.cpp
  launcher/ui/widgets/VersionSelectWidget.h
Labels: enhancement

#1210 fix(appimage): bundle generic opengl lib
  .github/workflows/build.yml
Labels: bug, actions, packaging, Linux

#1224 chore: install appstream in appimage
  .github/workflows/build.yml
Labels: bug, actions, packaging, Linux

#1233 Remove inconsistent/unneeded question marks in UI
  launcher/minecraft/auth/AccountList.cpp
  launcher/ui/pages/global/LauncherPage.ui
  launcher/ui/pages/global/MinecraftPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.ui
Labels: enhancement, simple change

#1234 Fix compiling on FreeBSD
  launcher/FileSystem.cpp
Labels: bug, simple change

#1184 Fix bugs when updating curseforge modpacks
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
Labels: bug, simple change

#1119 Added dynamic page extra info
  launcher/ui/pages/BasePage.h
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.h
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/widgets/PageContainer.cpp
Labels: enhancement, simple change

#1228 Fixes #1212
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ResourcePage.cpp
Labels: bug

#1243 Added regex expresion to exclude .DS_Store files
  launcher/ui/dialogs/ExportMrPackDialog.cpp
Labels: enhancement, simple change

#1235 Add missing space in java checker debug message
  launcher/java/JavaChecker.cpp
Labels: enhancement, simple change

#1252 chore: avoid confusion in file/url import dialog
  launcher/ui/pages/modplatform/ImportPage.h
Labels: simple change

#1251 chore: add 'suggest a feature' message in help
  launcher/ui/MainWindow.ui
Labels: simple change

#1200 Made ByteSynkArray to use shared_ptr
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/modplatform/ResourceAPI.h
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.h
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/helpers/HashUtils.cpp
  launcher/modplatform/helpers/HashUtils.h
  launcher/modplatform/helpers/NetworkResourceAPI.cpp
  launcher/modplatform/helpers/NetworkResourceAPI.h
  launcher/modplatform/legacy_ftb/PackFetchTask.cpp
  launcher/modplatform/legacy_ftb/PackFetchTask.h
  launcher/modplatform/modrinth/ModrinthAPI.cpp
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
  launcher/modplatform/modrinth/ModrinthPackExportTask.h
  launcher/modplatform/technic/SolderPackInstallTask.cpp
  launcher/modplatform/technic/SolderPackInstallTask.h
  launcher/net/ByteArraySink.h
  launcher/net/Download.cpp
  launcher/net/Download.h
  launcher/net/Upload.cpp
  launcher/net/Upload.h
  launcher/news/NewsChecker.cpp
  launcher/news/NewsChecker.h
  launcher/ui/dialogs/NewsDialog.cpp
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlListModel.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlListModel.h
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.h
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.h
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.h
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
  launcher/ui/pages/modplatform/technic/TechnicModel.h
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
  launcher/ui/pages/modplatform/technic/TechnicPage.h
Labels: bug

#1256 Fixed hashers
  launcher/modplatform/helpers/HashUtils.cpp
Labels: bug

#1259 Update developers
  launcher/ui/dialogs/AboutDialog.cpp
Labels: simple change

#1258 fix: fix crash when hiding columns on resource packs page
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
Labels: bug, simple change

#1255 Added Thumbs.db to excluded files in MrPackExport
  launcher/ui/dialogs/ExportMrPackDialog.cpp
Labels: enhancement

#1261 modrinth: use encoded url when exporting pack
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
Labels: bug, simple change

#986 Mod dependencies
  launcher/CMakeLists.txt
  launcher/ResourceDownloadTask.h
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/minecraft/mod/tasks/GetModDependenciesTask.h
  launcher/minecraft/mod/tasks/LocalModUpdateTask.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/ResourceAPI.h
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/flame/FlameModIndex.h
  launcher/modplatform/flame/FlamePackIndex.h
  launcher/modplatform/helpers/NetworkResourceAPI.cpp
  launcher/modplatform/helpers/NetworkResourceAPI.h
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.h
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.h
  launcher/ui/dialogs/ReviewMessageBox.cpp
  launcher/ui/dialogs/ReviewMessageBox.h
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/flame/FlameResourceModels.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.h
  launcher/ui/pages/modplatform/modrinth/ModrinthResourceModels.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourceModels.h
Labels: enhancement, needs-testing

#1270 Fix unsafe usage of std::optional::value in FlameAPI
  launcher/modplatform/flame/FlameAPI.h
Labels: bug

#1272 fix: Page container extra info set on logs page
  launcher/ui/pages/BasePage.h
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/widgets/PageContainer.cpp
Labels: bug

#1275 Add Git Blame ignore file
  .git-blame-ignore-revs
Labels: simple change

#1274 Fix for JavaVersion & friends not updating
  launcher/Application.cpp
  launcher/launch/steps/CheckJava.cpp
  launcher/launch/steps/CheckJava.h
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change

#1281 Added more information to the screenshot upload warning
  launcher/ui/pages/instance/ScreenshotsPage.cpp
Labels: enhancement, simple change
