Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-12, with the labels that each got.

#3152 Fix system icons on Linux
  launcher/resources/multimc/index.theme
  launcher/ui/themes/ThemeManager.cpp
Labels: bug, changelog:fixed, backport release-9.x

#3135 Make FTB Import note italic to match others
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.ui
Labels: simple change, changelog:omit, backport release-9.x

#3119 Sync Flatpak manifest with Flathub's
  .github/workflows/build.yml
  flatpak/org.prismlauncher.PrismLauncher.yml
Labels: bug, simple change, packaging, Linux, changelog:omit, backport release-9.x

#2800 Add search and support for subdirectories to icon picker
  launcher/icons/IconList.cpp
  launcher/icons/IconList.h
  launcher/ui/dialogs/IconPickerDialog.cpp
  launcher/ui/dialogs/IconPickerDialog.h
Labels: enhancement, simple change, changelog:added

#3170 [Linux] Don't use fallback icon search paths
  launcher/ui/themes/ThemeManager.cpp
Labels: bug, simple change, changelog:merged, backport release-9.x

#3181 fix crash with invalid mrpack format
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3198 [macOS] Add local network usage description
  cmake/MacOSXBundleInfo.plist.in
Labels: simple change, macOS, changelog:omit, backport release-9.x

#3199 Fix tab order in launcher settings
  launcher/ui/pages/global/LauncherPage.ui
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3214 Correct symbolic link destination on manifest (Mojang) Java download
  launcher/java/download/ManifestDownloadTask.cpp
Labels: bug, simple change, macOS, Linux, changelog:fixed, backport release-9.x

#3197 Do not fail curseforge import if modrinth file check fails
  launcher/modplatform/flame/FileResolvingTask.cpp
Labels: bug, simple change, backport release-9.x

#3043 fix the flame loaders match
  launcher/minecraft/mod/Mod.cpp
  launcher/modplatform/ModIndex.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameCheckUpdate.h
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/modplatform/packwiz/Packwiz.cpp
  launcher/ui/dialogs/ResourceUpdateDialog.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3216 Fix automatically choose mod provider option
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/modplatform/EnsureMetadataTask.h
  launcher/ui/dialogs/ResourceUpdateDialog.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x
