Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-04, with the labels that each got.

#2263 chore: update to Qt 6.7.0
  .github/workflows/build.yml
Labels: enhancement, packaging, changelog:changed

#2268 [Linux] Add jdk21 to Nix packages
  nix/pkg/wrapper.nix
Labels: packaging, changelog:fixed, backport release-8.x

#2275 Replace invalid characters when extracting ZIP
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/MMCZip.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#2247 Fixed crash on non-latin instance name
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/InstanceImportTask.h
  launcher/java/JavaChecker.cpp
  launcher/minecraft/launch/ExtractNatives.cpp
  launcher/minecraft/launch/ExtractNatives.h
  launcher/minecraft/launch/LauncherPartLaunch.cpp
Labels: bug, simple change, Windows, changelog:fixed, backport release-8.x

#2277 Fix unicode characters being invalid in filenames
  launcher/FileSystem.cpp
Labels: bug, changelog:merged, backport release-8.x

#2225 Use UTF-8 for ZIP creation
  launcher/MMCZip.cpp
  launcher/MMCZip.h
Labels: bug, needs-testing, changelog:fixed, backport release-8.x

#2291 Fixed crash on invalid curseforge link on import
  launcher/ui/pages/modplatform/ImportPage.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#2286 Update to Qt 6.6.3
  .github/workflows/build.yml
Labels: manual backport, changelog:changed

#2304 Fixed modrinth pack update
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.h
Labels: bug, simple change, changelog:fixed

#2294 Fixed application close on open file dialog
  launcher/Application.cpp
Labels: bug, simple change, needs-testing, changelog:fixed, backport release-8.x

#2319 Support mod info for NeoForge 20.5
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
Labels: simple change, changelog:added, backport release-8.x

#2327 Add Gradle Toolchains to java scan list
  launcher/java/JavaUtils.cpp
Labels: enhancement, simple change, changelog:added, backport release-8.x

#2328 Removed java from appimage
  .github/scripts/prepare_JREs.sh
  .github/workflows/build.yml
Labels: simple change, actions, changelog:removed, backport release-8.x

#2333 Fix Minecraft Launcher runtime detection on Windows and macOS
  launcher/java/JavaUtils.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#2337 Fixed windows bundled java path
  launcher/java/JavaUtils.cpp
Labels: bug, simple change, Windows, changelog:fixed, changelog:merged, backport release-8.x

#2292 Remove old version variants in instance creation
  launcher/ui/pages/modplatform/CustomPage.cpp
  launcher/ui/pages/modplatform/CustomPage.ui
Labels: enhancement, changelog:removed, backport release-8.x

#2345 Remove server side decorations FIXME and document why it's needed
  launcher/ui/MainWindow.cpp
Labels: simple change, changelog:omit

#2348 Use proxy style to force ActivateItemOnSingleClick off
  launcher/CMakeLists.txt
  launcher/ui/themes/HintOverrideProxyStyle.cpp
  launcher/ui/themes/HintOverrideProxyStyle.h
  launcher/ui/themes/ITheme.cpp
  launcher/ui/themes/SystemTheme.cpp
Labels: bug, needs-testing, changelog:fixed, backport release-8.x
