Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-05, with the labels that each got.

#2311 Rename object name "userInterfaceTab" from "generalTab"
  launcher/ui/pages/global/LauncherPage.ui
Labels: simple change, changelog:changed

#2341 Fix image width in project description
  launcher/ui/widgets/VariableSizedImageObject.cpp
  launcher/ui/widgets/VariableSizedImageObject.h
Labels: bug, simple change, changelog:fixed, backport release-8.x

#2366 Fix download packs with invalid characters
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/net/HttpMetaCache.cpp
  launcher/net/NetRequest.cpp
Labels: bug, simple change, Windows, changelog:fixed, backport release-8.x

#2379 Improve blocked mods dialog (permissions prompt, misc. fixes) on macOS
  cmake/MacOSXBundleInfo.plist.in
  launcher/ui/dialogs/BlockedModsDialog.cpp
Labels: enhancement, simple change, macOS, changelog:added, backport release-8.x

#2358 Remove prebuilt system tarballs on Linux, bundle Qt with Linux portable
  .github/workflows/build.yml
  .github/workflows/trigger_release.yml
  CMakeLists.txt
  launcher/CMakeLists.txt
  launcher/install_prereqs.cmake.in
Labels: packaging, changelog:removed

#2382 Add neoforge support for technic packs and atlauncher packs
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/technic/TechnicPackProcessor.cpp
Labels: enhancement, simple change, changelog:added, backport release-8.x

#1827 fixed shader packs detection
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ShaderPack.cpp
  launcher/minecraft/mod/ShaderPack.h
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalShaderPackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalTexturePackParseTask.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
Labels: bug, needs-testing, changelog:merged

#2377 Adding sdkman java location to MacOs
  launcher/java/JavaUtils.cpp
Labels: enhancement, simple change, macOS, changelog:added, backport release-8.x

#1525 Add wait profiler
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/tools/GenericProfiler.cpp
  launcher/tools/GenericProfiler.h
Labels: enhancement, simple change, changelog:added

#1365 Ask user to retry if netjob fails
  launcher/net/NetJob.cpp
  launcher/net/NetJob.h
Labels: enhancement, simple change, changelog:fixed

#2438 Added support for bcachefs
  launcher/FileSystem.h
Labels: enhancement, simple change, changelog:added, backport release-8.x

#2423 fix incorrect launch time
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#1847 Improvements to modlist export
  launcher/modplatform/helpers/ExportToModList.cpp
  launcher/modplatform/helpers/ExportToModList.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
  launcher/ui/dialogs/ExportToModListDialog.cpp
  launcher/ui/dialogs/ExportToModListDialog.h
  launcher/ui/dialogs/ExportToModListDialog.ui
  launcher/ui/pages/instance/ExternalResourcesPage.ui
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
Labels: enhancement, changelog:added
