Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-01, with the labels that each got.

#1979 Mod downloader page improvements
  launcher/modplatform/ModIndex.h
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.h
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/widgets/ProjectItem.cpp
Labels: bug, simple change, changelog:fixed

#2005 Format java code
  libraries/launcher/legacy/org/prismlauncher/legacy/fix/online/OnlineModeFix.java
Labels: simple change, changelog:merged, backport release-8.x

#1983 remove legacy processArguments code
  launcher/minecraft/MojangVersionFormat.cpp
Labels: simple change, changelog:changed, legacy minecraft, backport release-8.x

#1972 Add a cat opacity option
  launcher/Application.cpp
  launcher/ui/instanceview/InstanceView.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement, simple change, changelog:added

#2012 Fixed openAL placeholder
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
Labels: bug, simple change, changelog:fixed

#1771 Try refreshing account on launch if needed
  launcher/LaunchController.cpp
  launcher/minecraft/auth/AccountList.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#2024 Deduplicate nixpkgs input & add Garnix cache to nixConfig
  flake.lock
  flake.nix
  nix/README.md
Labels: documentation, simple change, packaging, changelog:changed, backport release-8.x

#2034 [macOS] Add code signing and notarization
  .github/workflows/build.yml
  .github/workflows/trigger_builds.yml
  .github/workflows/trigger_release.yml
Labels: macOS, packaging, backport release-8.x

#1825 Added button to select the FTBApp instances directory
  launcher/Application.cpp
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.cpp
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.ui
  launcher/ui/pages/modplatform/import_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/import_ftb/ListModel.h
Labels: enhancement, simple change, changelog:added, backport release-8.x

#1913 Fixed askIfShouldUpdate dialog on mac
  launcher/InstanceTask.cpp
Labels: bug, simple change, changelog:fixed

#2053 Fixed open path a second time
  launcher/DesktopServices.cpp
Labels: simple change, changelog:merged

#2040 [Linux/MacOS] Replace nix-filter with lib.fileset
  flake.lock
  flake.nix
  nix/distribution.nix
  nix/pkg/default.nix
Labels: changelog:changed, backport release-8.x
