Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-08, with the labels that each got.

#1526 feat:Removed update disabled warning
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/Resource.cpp
  launcher/minecraft/mod/Resource.h
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
Labels: enhancement, simple change, changelog:changed

#2692 Fix a typo in comment
  launcher/FileSystem.h
Labels: simple change, changelog:omit

#2694 ensure minimal folder permissions when extracting files
  launcher/MMCZip.cpp
Labels: bug, simple change, changelog:merged

#2617 remove duplicate code from net folder
  launcher/CMakeLists.txt
  launcher/minecraft/auth/steps/EntitlementsStep.cpp
  launcher/minecraft/auth/steps/LauncherLoginStep.cpp
  launcher/minecraft/auth/steps/MSADeviceCodeStep.cpp
  launcher/minecraft/auth/steps/MinecraftProfileStep.cpp
  launcher/minecraft/auth/steps/XboxAuthorizationStep.cpp
  launcher/minecraft/auth/steps/XboxProfileStep.cpp
  launcher/minecraft/auth/steps/XboxUserStep.cpp
  launcher/minecraft/skins/CapeChange.cpp
  launcher/minecraft/skins/CapeChange.h
  launcher/minecraft/skins/SkinDelete.cpp
  launcher/minecraft/skins/SkinDelete.h
  launcher/minecraft/skins/SkinUpload.cpp
  launcher/minecraft/skins/SkinUpload.h
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/net/ApiDownload.cpp
  launcher/net/ApiDownload.h
  launcher/net/ApiUpload.cpp
  launcher/net/ApiUpload.h
  launcher/net/NetRequest.cpp
  launcher/net/NetRequest.h
  launcher/net/RawHeaderProxy.h
  launcher/net/StaticHeaderProxy.h
  launcher/screenshots/ImgurAlbumCreation.cpp
  launcher/screenshots/ImgurAlbumCreation.h
  launcher/screenshots/ImgurUpload.cpp
  launcher/screenshots/ImgurUpload.h
  launcher/ui/dialogs/ProfileSetupDialog.cpp
Labels: changelog:omit

#2639 chore: update Qt to 6.7.2
  .github/workflows/build.yml
Labels: changelog:omit

#2706 Restore connect line for device authorization in MSADeviceCodeStep
  launcher/minecraft/auth/steps/MSADeviceCodeStep.cpp
Labels: bug, simple change, changelog:merged

#2714 [Windows] Search for Javas in Registry `HKEY_CURRENT_USER`
  launcher/java/JavaUtils.cpp
Labels: simple change, Windows, changelog:added

#2716 add setting for quickplay singleplayer
  launcher/Application.cpp
  launcher/Application.h
  launcher/BaseInstance.h
  launcher/CMakeLists.txt
  launcher/InstancePageProvider.h
  launcher/LaunchController.cpp
  launcher/LaunchController.h
  launcher/NullInstance.h
  launcher/launch/steps/LookupServerAddress.cpp
  launcher/launch/steps/LookupServerAddress.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  launcher/minecraft/launch/LauncherPartLaunch.h
  launcher/minecraft/launch/MinecraftTarget.cpp
  launcher/minecraft/launch/MinecraftTarget.h
  launcher/minecraft/launch/PrintInstanceInfo.cpp
  launcher/minecraft/launch/PrintInstanceInfo.h
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.h
  launcher/ui/pages/instance/InstanceSettingsPage.ui
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/instance/WorldListPage.cpp
  launcher/ui/pages/instance/WorldListPage.h
  launcher/ui/pages/instance/WorldListPage.ui
  launcher/ui/widgets/WideBar.cpp
  launcher/ui/widgets/WideBar.h
  libraries/launcher/org/prismlauncher/launcher/impl/AbstractLauncher.java
  libraries/launcher/org/prismlauncher/launcher/impl/StandardLauncher.java
Labels: enhancement, changelog:added

#2718 mangohud support: MangoHud::getLibraryString should return absolute path
  launcher/MangoHud.cpp
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change, changelog:fixed

#2633 refactor MinecraftUpdate Task
  launcher/minecraft/MinecraftUpdate.cpp
  launcher/minecraft/MinecraftUpdate.h
Labels: enhancement, simple change, changelog:changed

#2729 replaced currentTextChanged with currentIndexChanged
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/ResourcePage.h
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.h
  launcher/ui/pages/modplatform/flame/FlameResourcePages.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.cpp
Labels: bug, simple change, changelog:fixed

#2735 allways load java list on autodetect
  launcher/ui/dialogs/VersionSelectDialog.cpp
  launcher/ui/dialogs/VersionSelectDialog.h
  launcher/ui/widgets/VersionSelectWidget.cpp
  launcher/ui/widgets/VersionSelectWidget.h
Labels: enhancement, simple change, changelog:added

#2745 Fix invalid Java path message
  launcher/launch/steps/CheckJava.cpp
Labels: bug, changelog:fixed

#2740 Allow themes to modify log colours
  launcher/CMakeLists.txt
  launcher/ui/ColorCache.cpp
  launcher/ui/ColorCache.h
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.h
  launcher/ui/pages/instance/LogPage.cpp
  launcher/ui/themes/BrightTheme.cpp
  launcher/ui/themes/BrightTheme.h
  launcher/ui/themes/CustomTheme.cpp
  launcher/ui/themes/CustomTheme.h
  launcher/ui/themes/DarkTheme.cpp
  launcher/ui/themes/DarkTheme.h
  launcher/ui/themes/ITheme.cpp
  launcher/ui/themes/ITheme.h
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/SystemTheme.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
Labels: enhancement, changelog:added

#2738 [Linux/macOS] Cleanup Nix documentation and flake
  default.nix
  flake.lock
  flake.nix
  garnix.yaml
  nix/README.md
  nix/checks.nix
  nix/dev.nix
  nix/distribution.nix
  nix/pkg/default.nix
  nix/pkg/wrapper.nix
  nix/unwrapped.nix
  nix/wrapper.nix
Labels: macOS, packaging, Linux, changelog:changed

#2751 Prefer stronger hashes from Modrinth
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
Labels: simple change, changelog:fixed

#2748 Improve Java checking speed by using startsWith for gentoo paths
  launcher/java/JavaUtils.cpp
Labels: bug, changelog:fixed

#2749 Fix system theme detection
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/SystemTheme.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
Labels: bug, changelog:fixed

#2753 Stop accepting malformed hashes object
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
Labels: bug, changelog:fixed

#2018 Ensure that core mods tab is visible on correct versions
  launcher/ui/pages/instance/ModFolderPage.cpp
Labels: bug, simple change, changelog:fixed

#2755 fix java 64 bit condition
  launcher/ui/widgets/JavaSettingsWidget.cpp
Labels: bug, simple change, changelog:merged

#2757 Add checksum validator to resource download
  launcher/ResourceDownloadTask.cpp
Labels: enhancement, simple change, changelog:added

#2758 Improve left and right cursor navigation in Instances
  launcher/ui/instanceview/InstanceView.cpp
Labels: enhancement, simple change, changelog:added

#2760 fix mangohud detection for absolute path
  launcher/MangoHud.cpp
Labels: bug, simple change, changelog:merged
