Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-10, with the labels that each got.

#2843 Fix Nix CI
  .git-blame-ignore-revs
  .github/workflows/build.yml
  .github/workflows/trigger_builds.yml
  .github/workflows/trigger_release.yml
  flake.nix
  garnix.yaml
  launcher/Application.cpp
  launcher/ui/MainWindow.cpp
  nix/README.md
  nix/checks.nix
Labels: actions, macOS, packaging, Linux, changelog:omit

#2859 add prefix to non-standard packwiz fields
  launcher/modplatform/packwiz/Packwiz.cpp
Labels: simple change, changelog:omit

#2857 fix some transtaions warnings
  launcher/MMCZip.h
  launcher/modplatform/flame/FlamePackExportTask.h
  launcher/modplatform/modrinth/ModrinthPackExportTask.h
  launcher/ui/dialogs/InstallLoaderDialog.cpp
  launcher/ui/pages/instance/ModFolderPage.h
Labels: simple change, changelog:omit

#2863 fix search term not remaining the same between providers on resource …
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
Labels: bug, simple change, changelog:fixed

#2893 Disable retry for private pack fetch
  launcher/modplatform/legacy_ftb/PackFetchTask.cpp
Labels: bug

#2865 add vc_redist as a NSIS install section
  .github/workflows/build.yml
  program_info/CMakeLists.txt
  program_info/win_install.nsi.in
Labels: enhancement, simple change, Windows, changelog:changed

#2890 Keep libGLU in Flatpak
  flatpak/org.prismlauncher.PrismLauncher.yml
Labels: bug, simple change, packaging, Linux, changelog:fixed

#2897 fix crash when no resorce version is available
  launcher/ui/pages/modplatform/ResourcePage.cpp
Labels: bug, simple change, changelog:fixed

#2900 Use UTF-8 to decode logs on Java 18 or newer
  launcher/LoggedProcess.cpp
  launcher/LoggedProcess.h
  launcher/java/JavaVersion.cpp
  launcher/java/JavaVersion.h
  launcher/launch/LaunchTask.cpp
  launcher/launch/LaunchTask.h
  launcher/minecraft/launch/AutoInstallJava.cpp
  launcher/minecraft/launch/CreateGameFolders.cpp
  launcher/minecraft/launch/ExtractNatives.cpp
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  launcher/minecraft/launch/ModMinecraftJar.cpp
  launcher/minecraft/launch/ReconstructAssets.cpp
  launcher/minecraft/launch/ScanModFolders.cpp
  launcher/minecraft/launch/VerifyJavaInstall.cpp
Labels: bug, needs-testing

#2887 Add filters for modpack search
  launcher/Version.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlamePackIndex.cpp
  launcher/modplatform/flame/FlamePackIndex.h
  launcher/modplatform/modrinth/ModrinthAPI.cpp
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.h
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.h
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.h
  launcher/ui/pages/modplatform/flame/FlamePage.ui
  launcher/ui/pages/modplatform/flame/FlameResourcePages.cpp
  launcher/ui/pages/modplatform/flame/FlameResourcePages.h
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.ui
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.h
Labels: enhancement, changelog:added

#2908 remove client overrides instead of double deleting the normal ones
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
Labels: bug, simple change, changelog:fixed

#2913 Fix tab order on custom command inputs
  launcher/ui/widgets/CustomCommands.ui
Labels: simple change, ui rework, changelog:omit

#2916 fix: ensure all connections to the ProgressDialogs's Task the dialog made are disconnected
  launcher/ui/dialogs/ProgressDialog.cpp
  launcher/ui/dialogs/ProgressDialog.h
Labels: bug, simple change, changelog:fixed

#2917 fix heap-use-after-free in modrinth creation task
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
Labels: bug, simple change, changelog:omit

#2929 Replace http with https on skins
  launcher/minecraft/auth/Parsers.cpp
Labels: bug, simple change, needs-testing, changelog:fixed

#2930 Fix tests segfault
  CMakeLists.txt
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/net/NetJob.cpp
  launcher/ui/pages/modplatform/ResourceModel.cpp
Labels: bug, simple change, actions, changelog:omit

#2932 Enable checks in Nix package
  nix/unwrapped.nix
Labels: simple change, macOS, packaging, Linux, changelog:omit

#2933 Don't bundle JREs in Flatpak
  flatpak/org.prismlauncher.PrismLauncher.yml
Labels: simple change, packaging, Linux, changelog:changed

#2831 split the auth loading screen
  launcher/ui/dialogs/MSALoginDialog.cpp
  launcher/ui/dialogs/MSALoginDialog.h
  launcher/ui/dialogs/MSALoginDialog.ui
Labels: enhancement, simple change, changelog:merged, Auth

#2938 fix sparkle signature
  .github/workflows/build.yml
Labels: changelog:omit, backport release-8.x

#2948 Fix /norestart
  program_info/CMakeLists.txt
Labels: bug, simple change, changelog:fixed, backport release-9.x

#2947 do not require java if auto-download is enabled
  launcher/Application.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#2953 Fix removing portable.txt on Linux portable build
  launcher/Launcher.in
Labels: bug, backport release-9.x

#2954 do not try to import skin if path is empty
  launcher/ui/dialogs/skins/SkinManageDialog.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#2958 skip parsing open QSaveFile temprary files as resources
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/FileSystem.cpp
  launcher/PSaveFile.h
  launcher/minecraft/World.cpp
  launcher/minecraft/mod/tasks/BasicFolderLoadTask.h
  launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp
  launcher/modplatform/packwiz/Packwiz.cpp
  launcher/net/FileSink.cpp
  launcher/net/FileSink.h
  launcher/settings/INIFile.cpp
  launcher/ui/dialogs/ExportInstanceDialog.cpp
  launcher/ui/pages/instance/ModFolderPage.cpp
Labels: bug, Windows, changelog:fixed

#2972 Fix launching Minecraft in portable Linux
  launcher/java/JavaUtils.cpp
Labels: bug, backport release-9.x

#2975 fix: don't hang the ui for a full version load
  launcher/minecraft/Component.cpp
  launcher/minecraft/Component.h
  launcher/ui/pages/instance/VersionPage.cpp
Labels: bug, backport release-9.x

#2982 Use Launcher log level in AutoInstallJava
  launcher/minecraft/launch/AutoInstallJava.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#2987 Bump 9.2
  CMakeLists.txt
Labels: simple change, changelog:omit

#2992 Sync Flake with Nixpkgs
  flake.nix
  nix/unwrapped.nix
  nix/wrapper.nix
Labels: simple change, macOS, packaging, Linux, changelog:omit, backport release-9.x

#3008 change contributors name
  launcher/ui/dialogs/AboutDialog.cpp
Labels: simple change, changelog:omit, backport release-9.x

#3009 swap search with filter button for modpacks
  launcher/ui/pages/modplatform/flame/FlamePage.ui
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.ui
Labels: enhancement, simple change, ui rework, changelog:changed, backport release-9.x

#3002 fix unzipping typo
  launcher/MMCZip.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
Labels: simple change, changelog:omit, backport release-9.x

#3006 add release_type filer for mod/modpacks
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.h
  launcher/ui/widgets/ModFilterWidget.ui
Labels: enhancement, simple change, changelog:added

#1894 Fixed the maximized option on the newer Minecraft versions
  launcher/BaseInstance.cpp
  launcher/BaseInstance.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/ui/pages/global/MinecraftPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.ui
  libraries/launcher/org/prismlauncher/launcher/impl/StandardLauncher.java
Labels: bug, simple change, needs-testing, changelog:fixed

#2989 add extra protection against empty download link
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ResourcePackPage.cpp
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/ResourcePage.h
  launcher/ui/pages/modplatform/ShaderPackPage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlameResourcePages.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.cpp
  launcher/ui/widgets/ThemeCustomizationWidget.cpp
Labels: bug, simple change, changelog:fixed

#2986 bump develop to 10
  CMakeLists.txt
Labels: simple change, changelog:omit

#1953 Auto reauthenticate account if expired
  launcher/LaunchController.cpp
  launcher/LaunchController.h
Labels: enhancement, simple change, changelog:added

#3010 lock m_instanceExtras
  launcher/Application.cpp
  launcher/Application.h
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3035 Remove BasicFolderLoadTask
  launcher/minecraft/mod/tasks/BasicFolderLoadTask.h
Labels: simple change, changelog:omit
