Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-06, with the labels that each got.

#2346 List image append
  launcher/StringUtils.cpp
  launcher/StringUtils.h
  launcher/ui/dialogs/AboutDialog.cpp
  launcher/ui/dialogs/ExportToModListDialog.cpp
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/dialogs/UpdateAvailableDialog.cpp
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlPage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/legacy_ftb/Page.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
  launcher/updater/prismupdater/UpdaterDialogs.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#1409 feat: refactored Instance ImportTask
  launcher/Application.cpp
  launcher/BaseInstaller.cpp
  launcher/FileSystem.cpp
  launcher/InstanceCreationTask.cpp
  launcher/InstanceImportTask.cpp
  launcher/InstanceImportTask.h
  launcher/InstanceList.cpp
  launcher/MMCZip.cpp
  launcher/MMCZip.h
  launcher/icons/IconList.cpp
  launcher/icons/IconUtils.cpp
  launcher/meta/BaseEntity.cpp
  launcher/minecraft/Component.cpp
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/helpers/OverrideUtils.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/ui/pages/modplatform/ImportPage.cpp
  launcher/updater/prismupdater/PrismUpdater.cpp
Labels: enhancement, changelog:changed

#2471 replace auth server ping
  buildconfig/BuildConfig.h
  launcher/LaunchController.cpp
Labels: enhancement, simple change, changelog:changed, backport release-8.x

#2383 Made Custom New Instance scrollable
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/pages/modplatform/CustomPage.cpp
  launcher/ui/pages/modplatform/CustomPage.ui
Labels: bug, simple change, changelog:fixed, backport release-8.x

#2428 add detection for IBM Semeru Java runtime and fix x86 detection on 64 bit Windows
  launcher/java/JavaUtils.cpp
Labels: backport release-8.x

#2055 Display minecraft version if not mentioned for modrinth/curse packs
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.h
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
Labels: enhancement, simple change, changelog:added

#1823 Added button to refresh themes and catpacks
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
  launcher/ui/widgets/ThemeCustomizationWidget.cpp
  launcher/ui/widgets/ThemeCustomizationWidget.h
  launcher/ui/widgets/ThemeCustomizationWidget.ui
Labels: enhancement, simple change, changelog:added

#1617 added functionality for components in resource pack descriptions.
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.h
  launcher/ui/widgets/InfoFrame.cpp
  tests/CMakeLists.txt
  tests/MetaComponentParse_test.cpp
  tests/testdata/MetaComponentParse/component_basic.json
  tests/testdata/MetaComponentParse/component_with_extra.json
  tests/testdata/MetaComponentParse/component_with_format.json
  tests/testdata/MetaComponentParse/component_with_link.json
  tests/testdata/MetaComponentParse/component_with_mixed.json
Labels: enhancement, changelog:added

#2390 Delete instaces tmp diectory on startup
  launcher/Application.cpp
Labels: enhancement, simple change, changelog:added

#1554 updated instance copy
  launcher/FileSystem.h
  launcher/InstanceCopyTask.cpp
  launcher/InstanceCopyTask.h
Labels: bug, simple change, changelog:fixed

#1032 refactor: shorten desktop entry comment field
  program_info/org.prismlauncher.PrismLauncher.desktop.in
Labels: enhancement, simple change, changelog:changed, backport release-8.x

#2166 Updated ftb app import instance detection
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.cpp
  launcher/ui/pages/modplatform/import_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/import_ftb/ListModel.h
Labels: enhancement, simple change, changelog:fixed, backport release-8.x

#1776 feat:added size column
  launcher/minecraft/World.cpp
  launcher/minecraft/mod/DataPack.cpp
  launcher/minecraft/mod/DataPack.h
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/Mod.h
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/Resource.cpp
  launcher/minecraft/mod/Resource.h
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ResourcePack.cpp
  launcher/minecraft/mod/ResourcePack.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/ResourcePackFolderModel.h
  launcher/minecraft/mod/TexturePackFolderModel.cpp
  launcher/minecraft/mod/TexturePackFolderModel.h
Labels: enhancement, changelog:added

#2054 Made updater interval configurable
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
  launcher/updater/PrismExternalUpdater.cpp
Labels: enhancement, simple change, changelog:added

#2450 remove search button
  launcher/ui/pages/modplatform/atlauncher/AtlPage.ui
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.ui
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.ui
  launcher/ui/pages/modplatform/legacy_ftb/Page.ui
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.ui
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
  launcher/ui/pages/modplatform/technic/TechnicPage.ui
Labels: simple change, ui rework, changelog:removed

#2425 improve invalid path name
  launcher/FileSystem.cpp
  launcher/MMCZip.cpp
  launcher/minecraft/Library.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/net/HttpMetaCache.cpp
Labels: bug, changelog:changed, backport release-8.x

#2498 fix(SkinManageDialog.cpp): typo
  launcher/ui/dialogs/skins/SkinManageDialog.cpp
Labels: bug, simple change, changelog:merged

#2499 update imgur upload
  launcher/screenshots/ImgurAlbumCreation.cpp
  launcher/screenshots/ImgurUpload.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#2439 fix vanilla technic modpacks
  launcher/modplatform/technic/TechnicPackProcessor.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#2405 Fix portable if manifest is missing
  launcher/updater/prismupdater/PrismUpdater.cpp
Labels: bug, simple change, changelog:fixed, backport release-8.x

#2509 fix(flatpak): disable docs for glfw
  flatpak/org.prismlauncher.PrismLauncher.yml
Labels: bug, packaging, changelog:omit, backport release-8.x

#1829 Fixed demo mode
  launcher/LaunchController.cpp
  launcher/LaunchController.h
  launcher/minecraft/auth/AuthSession.cpp
  launcher/minecraft/auth/AuthSession.h
  launcher/minecraft/auth/MinecraftAccount.cpp
  launcher/minecraft/auth/MinecraftAccount.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
Labels: bug, changelog:fixed

#1728 feat: add more filters to the mod download dialog
  launcher/CMakeLists.txt
  launcher/minecraft/mod/MetadataHandler.h
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/Mod.h
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/Resource.h
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/modplatform/ModIndex.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/ResourceAPI.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/modrinth/ModrinthAPI.cpp
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/packwiz/Packwiz.cpp
  launcher/modplatform/packwiz/Packwiz.h
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/ResourceModel.cpp
  launcher/ui/pages/modplatform/ResourceModel.h
  launcher/ui/pages/modplatform/ResourcePackPage.cpp
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/ResourcePage.h
  launcher/ui/pages/modplatform/ResourcePage.ui
  launcher/ui/pages/modplatform/ShaderPackPage.cpp
  launcher/ui/pages/modplatform/TexturePackPage.h
  launcher/ui/pages/modplatform/flame/FlameResourceModels.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.h
  launcher/ui/pages/modplatform/flame/FlameResourcePages.cpp
  launcher/ui/pages/modplatform/flame/FlameResourcePages.h
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.h
  launcher/ui/widgets/CheckComboBox.cpp
  launcher/ui/widgets/CheckComboBox.h
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.h
  launcher/ui/widgets/ModFilterWidget.ui
Labels: enhancement, ui rework, changelog:added

#2533 Spelling mistake for Minecraft
  launcher/minecraft/mod/ModFolderModel.cpp
Labels: bug, simple change, changelog:merged

#2531 relax fat FS filename restrictions
  launcher/FileSystem.cpp
Labels: bug, simple change, changelog:merged, backport release-8.x

#2534 fix: update datapack and resourcepack versions
  launcher/minecraft/mod/DataPack.cpp
  launcher/minecraft/mod/ResourcePack.cpp
Labels: simple change, changelog:fixed, backport release-8.x

#2361 [Linux] Drop unsupported Qt 5 Nix package
  flake.lock
  flake.nix
  nix/distribution.nix
Labels: changelog:removed, backport release-8.x

#2536 Refactor hash task
  launcher/MMCZip.h
  launcher/minecraft/mod/Mod.cpp
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/modplatform/ModIndex.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/flame/FlamePackExportTask.cpp
  launcher/modplatform/helpers/HashUtils.cpp
  launcher/modplatform/helpers/HashUtils.h
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/packwiz/Packwiz.cpp
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/ChooseProviderDialog.cpp
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  libraries/murmur2/src/MurmurHash2.cpp
  libraries/murmur2/src/MurmurHash2.h
Labels: enhancement, changelog:changed

#2553 don't translate file types on file save/open, etc. dialogs
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/ExportPackDialog.cpp
  launcher/ui/dialogs/ExportToModListDialog.cpp
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/WorldListPage.cpp
Labels: bug, simple change, changelog:fixed

#2542 perf: print api servers asynchronously on instance launch
  launcher/CMakeLists.txt
  launcher/LaunchController.cpp
  launcher/launch/steps/PrintServers.cpp
  launcher/launch/steps/PrintServers.h
Labels: bug, simple change, changelog:fixed

#2429 [Linux] Auto-detect Gentoo installed JDKs
  launcher/java/JavaUtils.cpp
Labels: Linux, changelog:fixed

#2515 force aspect ratio for skin preview
  launcher/ui/dialogs/skins/SkinManageDialog.cpp
  launcher/ui/dialogs/skins/SkinManageDialog.h
  launcher/ui/dialogs/skins/SkinManageDialog.ui
Labels: bug, simple change, changelog:merged

#2481 chore: update Qt to 6.7.1
  .github/workflows/build.yml
Labels: changelog:changed

#2562 fix update message
  launcher/Application.cpp
Labels: simple change, changelog:omit

#2561 fix missing curseforge logo
  launcher/modplatform/flame/FlameModIndex.cpp
Labels: bug, simple change, changelog:fixed

#2570 add ~/Library/Java/JavaVirtualMachines/* to java installation detection
  launcher/java/JavaUtils.cpp
Labels: enhancement, simple change, macOS, changelog:added

#2566 add warnning when user closes the resource download dialog with selec…
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
Labels: enhancement, simple change, changelog:added

#1892 Added mod reinstall dialog
  launcher/minecraft/mod/TexturePackFolderModel.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.h
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/ResourceModel.h
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/ResourcePage.h
  launcher/ui/widgets/PageContainer.h
Labels: enhancement, changelog:added

#2574 fix non-persistent user icon selection in NewInstanceDialog.cpp
  launcher/ui/dialogs/NewInstanceDialog.cpp
Labels: simple change, changelog:fixed

#2572 fix sdkman on macos
  launcher/java/JavaUtils.cpp
Labels: bug, simple change, macOS, changelog:fixed

#2520 completly remove metadata on refresh
  launcher/Application.cpp
  launcher/net/HttpMetaCache.cpp
Labels: enhancement, simple change, changelog:added

#2571 refresh account if it should refresh on instance launch
  launcher/LaunchController.cpp
Labels: simple change, changelog:changed

#2580 do not display message that no update is avvailable if the check was …
  launcher/updater/PrismExternalUpdater.cpp
  launcher/updater/PrismExternalUpdater.h
Labels: enhancement, simple change, needs-testing, changelog:changed

#2504 update login flow
  cmake/MacOSXBundleInfo.plist.in
  launcher/Application.h
  launcher/minecraft/auth/AuthFlow.cpp
  launcher/minecraft/auth/AuthFlow.h
  launcher/minecraft/auth/AuthStep.h
  launcher/minecraft/auth/steps/GetSkinStep.cpp
  launcher/minecraft/auth/steps/MSADeviceCodeStep.cpp
  launcher/minecraft/auth/steps/MSADeviceCodeStep.h
  launcher/minecraft/auth/steps/MSAStep.cpp
  launcher/minecraft/auth/steps/MinecraftProfileStep.cpp
  launcher/resources/documents/documents.qrc
  launcher/resources/documents/login-qr.svg
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/MSALoginDialog.cpp
  launcher/ui/dialogs/MSALoginDialog.h
  launcher/ui/dialogs/MSALoginDialog.ui
  launcher/ui/pages/global/AccountListPage.cpp
  program_info/org.prismlauncher.PrismLauncher.desktop.in
  program_info/win_install.nsi.in
Labels: enhancement, ui rework, changelog:merged, Auth

#2592 trim input from import page
  launcher/ui/pages/modplatform/ImportPage.cpp
Labels: bug, simple change, changelog:fixed

#2589 make sure updater take into consideration UserData
  launcher/updater/prismupdater/PrismUpdater.cpp
Labels: bug, simple change, changelog:fixed

#2588 Fix linux non portable update
  launcher/updater/prismupdater/PrismUpdater.cpp
Labels: bug, simple change, Linux

#2590 control Prism data directory via env variable
  launcher/Application.cpp
  launcher/updater/prismupdater/PrismUpdater.cpp
Labels: enhancement, simple change, changelog:added

#2173 Remove dependencies if review mods is rejected
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
Labels: bug, simple change, changelog:fixed

#2415 Add config for transfer timeout
  launcher/Application.cpp
  launcher/net/NetRequest.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement, simple change, changelog:added
