Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-03, with the labels that each got.

#2160 Fixes to instance staging
  launcher/InstanceList.cpp
  program_info/prismlauncher.manifest.in
Labels: bug, changelog:fixed, backport release-8.x

#2178 (More) mrpack export fixes
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
  launcher/ui/dialogs/ExportPackDialog.cpp
  launcher/ui/dialogs/ExportPackDialog.ui
Labels: bug, changelog:fixed, backport release-8.x

#1866 Added all supported files filter
  launcher/ui/pages/modplatform/ImportPage.cpp
Labels: enhancement, simple change, changelog:added

#1837 Fixed inconsistent Ok in instance import
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
Labels: bug, simple change, changelog:fixed

#2231 fix: include libbz2.so.1.0
  .github/workflows/build.yml
Labels: packaging, changelog:fixed

#1786 Make dependency checking more lax
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/minecraft/mod/tasks/GetModDependenciesTask.h
  launcher/modplatform/CheckUpdateTask.h
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/dialogs/ReviewMessageBox.cpp
  launcher/ui/dialogs/ReviewMessageBox.h
Labels: enhancement, changelog:added

#1529 Added UserData as another posible path for portable builds
  launcher/Application.cpp
Labels: enhancement, simple change, needs-testing, changelog:added

#1977 Force clear the resource selection
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ResourcePackPage.cpp
  launcher/ui/pages/modplatform/ShaderPackPage.cpp
Labels: bug, simple change, changelog:fixed
