Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-07, with the labels that each got.

#2567 feat(instanceList) persist "ungrouped" hidden state
  launcher/InstanceList.cpp
Labels: enhancement, simple change, changelog:added

#2609 fix crash with hash task
  launcher/modplatform/helpers/HashUtils.cpp
Labels: bug, simple change, changelog:merged

#2607 Add ModpackUpdatePromptDisabled setting
  launcher/Application.cpp
  launcher/InstanceTask.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement, simple change, changelog:added

#2612 add docs to Library.cpp
  launcher/minecraft/Library.cpp
Labels: documentation, changelog:omit

#2626 remove some poly mentions from the code
  launcher/InstanceList.cpp
  launcher/InstanceList.h
Labels: changelog:omit

#2596 Display all system themes in widget theme selector
  launcher/ui/themes/BrightTheme.cpp
  launcher/ui/themes/BrightTheme.h
  launcher/ui/themes/CustomTheme.cpp
  launcher/ui/themes/CustomTheme.h
  launcher/ui/themes/DarkTheme.cpp
  launcher/ui/themes/DarkTheme.h
  launcher/ui/themes/ITheme.h
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/SystemTheme.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
  launcher/ui/widgets/ThemeCustomizationWidget.cpp
Labels: enhancement, changelog:changed

#2635 FIX launcher/java/JavaUtils.cpp to properly autodetect JVM paths on …
  launcher/java/JavaUtils.cpp
Labels: simple change, changelog:added

#2653 Fix dead link to Modrinth authentication docs
  launcher/ui/pages/global/APIPage.ui
Labels: bug, simple change, changelog:fixed

#2660 Fix a few typos
  launcher/Application.cpp
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/ProfileUtils.cpp
  launcher/net/NetRequest.cpp
  launcher/settings/OverrideSetting.h
  launcher/settings/PassthroughSetting.h
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
Labels: changelog:fixed

#2650 fix a few missing help pages
  launcher/ui/pages/global/AccountListPage.h
  launcher/ui/pages/instance/ManagedPackPage.h
  launcher/ui/pages/instance/OtherLogsPage.h
  launcher/ui/pages/instance/ShaderPackPage.h
  launcher/ui/pages/modplatform/ResourcePackPage.h
  launcher/ui/pages/modplatform/ShaderPackPage.h
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.h
  launcher/ui/pages/modplatform/legacy_ftb/Page.h
Labels: bug, simple change, changelog:fixed

#2558 Resolve issue with multiple loaders during mod update
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile.h
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/modplatform/CheckUpdateTask.h
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/modplatform/flame/FlameCheckUpdate.h
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/modplatform/modrinth/ModrinthCheckUpdate.h
  launcher/screenshots/ImgurAlbumCreation.cpp
  launcher/screenshots/ImgurUpload.cpp
  launcher/ui/dialogs/ModUpdateDialog.cpp
Labels: bug, simple change, changelog:fixed

#2440 update retry netjob dialog
  launcher/Application.cpp
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/net/ApiDownload.cpp
  launcher/net/ApiUpload.cpp
  launcher/net/NetJob.cpp
  launcher/net/NetJob.h
  launcher/news/NewsChecker.cpp
  launcher/translations/TranslationsModel.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
  launcher/ui/pages/modplatform/ResourceModel.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlListModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
  launcher/ui/widgets/VariableSizedImageObject.cpp
Labels: simple change, changelog:merged

#2662 ui: swap timeoutSecondsLabel and numberOfManualRetriesLabel order
  launcher/ui/pages/global/LauncherPage.ui
Labels: changelog:merged
