Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-09, with the labels that each got.

#2784 ensure that the shortcut destination exists
  launcher/FileSystem.cpp
Labels: bug, simple change, changelog:fixed

#2547 Component version resolusion on Minecraft version change
  launcher/CMakeLists.txt
  launcher/meta/VersionList.cpp
  launcher/meta/VersionList.h
  launcher/minecraft/Component.cpp
  launcher/minecraft/Component.h
  launcher/minecraft/ComponentUpdateTask.cpp
  launcher/minecraft/ComponentUpdateTask.h
  launcher/minecraft/ComponentUpdateTask_p.h
  launcher/minecraft/Logging.cpp
  launcher/minecraft/Logging.h
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile_p.h
  launcher/ui/pages/instance/VersionPage.cpp
Labels: changelog:fixed, minecraft

#2798 Sort screenshots chronologically in descending order
  launcher/ui/pages/instance/ScreenshotsPage.cpp
Labels: enhancement, simple change, changelog:added

#2771 Add webp to validIconExtensions
  launcher/icons/IconUtils.cpp
Labels: enhancement, simple change, changelog:added

#2795 Fix launch when no java is loaded
  launcher/BaseInstance.h
  launcher/CMakeLists.txt
  launcher/NullInstance.h
  launcher/RuntimeContext.h
  launcher/launch/LaunchStep.cpp
  launcher/launch/LaunchStep.h
  launcher/launch/LaunchTask.cpp
  launcher/launch/LaunchTask.h
  launcher/launch/TaskStepWrapper.cpp
  launcher/launch/TaskStepWrapper.h
  launcher/launch/steps/CheckJava.cpp
  launcher/launch/steps/CheckJava.h
  launcher/launch/steps/QuitAfterGameStop.h
  launcher/launch/steps/Update.cpp
  launcher/launch/steps/Update.h
  launcher/minecraft/LaunchProfile.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/minecraft/MinecraftLoadAndCheck.cpp
  launcher/minecraft/MinecraftLoadAndCheck.h
  launcher/minecraft/MinecraftUpdate.cpp
  launcher/minecraft/PackProfile.h
  launcher/minecraft/launch/AutoInstallJava.h
  launcher/minecraft/launch/ClaimAccount.h
  launcher/minecraft/update/AssetUpdateTask.cpp
  launcher/minecraft/update/AssetUpdateTask.h
  launcher/minecraft/update/FMLLibrariesTask.h
  launcher/minecraft/update/FoldersTask.cpp
  launcher/minecraft/update/FoldersTask.h
  launcher/minecraft/update/LibrariesTask.h
  launcher/ui/pages/instance/VersionPage.cpp
Labels: bug, changelog:merged

#2803 Improve wizzard page
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/ui/setupwizard/AutoJavaWizardPage.cpp
  launcher/ui/setupwizard/AutoJavaWizardPage.h
  launcher/ui/setupwizard/AutoJavaWizardPage.ui
  launcher/ui/setupwizard/JavaWizardPage.cpp
  launcher/ui/setupwizard/JavaWizardPage.h
  launcher/ui/setupwizard/LoginWizardPage.cpp
  launcher/ui/setupwizard/LoginWizardPage.h
  launcher/ui/setupwizard/LoginWizardPage.ui
  launcher/ui/widgets/JavaSettingsWidget.cpp
  launcher/ui/widgets/JavaSettingsWidget.h
Labels: enhancement, simple change, changelog:changed

#2789 Remove all the slowdown code from CocurrentTask
  launcher/tasks/ConcurrentTask.cpp
  launcher/tasks/ConcurrentTask.h
Labels: bug, simple change, changelog:fixed

#2808 fix java crash on refresh
  launcher/Filter.h
Labels: bug, simple change, changelog:merged

#2811 fix download java abort being stuck
  launcher/launch/TaskStepWrapper.cpp
  launcher/minecraft/MinecraftLoadAndCheck.cpp
  launcher/minecraft/launch/AutoInstallJava.cpp
Labels: bug, simple change, changelog:merged

#2813 fix java autodetect when instance settings are open
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
Labels: bug, simple change, changelog:merged

#2827 add Launcher_ prefix to enable java option
  .github/workflows/build.yml
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
Labels: simple change, changelog:omit

#2807 fix server launch
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change, changelog:omit

#2826 Use macOS 14 in CI
  .github/workflows/build.yml
Labels: macOS, packaging, changelog:omit

#2819 add open java folder action
  launcher/Application.cpp
  launcher/LaunchController.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
  launcher/ui/themes/ThemeManager.h
Labels: enhancement, simple change, changelog:added

#2820 Add extra step to macos java install
  launcher/CMakeLists.txt
  launcher/java/download/SymlinkTask.cpp
  launcher/java/download/SymlinkTask.h
  launcher/minecraft/launch/AutoInstallJava.cpp
  launcher/ui/java/InstallJavaDialog.cpp
Labels: bug, changelog:omit

#2828 Allow configuring more URLs through CMake
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/minecraft/auth/steps/MSAStep.cpp
  launcher/translations/TranslationsModel.cpp
Labels: enhancement, simple change, changelog:omit

#2830 Show login dialog again if account login fails
  launcher/ui/setupwizard/LoginWizardPage.cpp
Labels: enhancement, simple change, changelog:merged

#2583 Generate updater metadata for mods added/updated using modpack updater/installer
  launcher/minecraft/mod/tasks/LocalModUpdateTask.h
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/modplatform/EnsureMetadataTask.h
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FileResolvingTask.h
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.h
  launcher/modplatform/flame/PackManifest.cpp
  launcher/modplatform/flame/PackManifest.h
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.h
Labels: enhancement, changelog:added

#2825 Skin fix
  launcher/InstanceCopyTask.cpp
  launcher/minecraft/skins/SkinList.cpp
  launcher/minecraft/skins/SkinModel.cpp
  launcher/ui/dialogs/ExportToModListDialog.cpp
  launcher/ui/dialogs/skins/SkinManageDialog.cpp
Labels: bug, simple change, changelog:merged

#2844 fix folder duplication for modrinth
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
Labels: bug, simple change, changelog:omit

#2845 fix updater typo
  launcher/java/download/ArchiveDownloadTask.cpp
  launcher/updater/prismupdater/PrismUpdater.cpp
Labels: simple change, changelog:omit

#2806 Add support for custom Technic client IDs
  launcher/Application.cpp
  launcher/ui/pages/global/APIPage.cpp
  launcher/ui/pages/global/APIPage.ui
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
Labels: enhancement, simple change, changelog:added

#2838 Always display Minecraft log tab
  launcher/ui/pages/instance/LogPage.cpp
Labels: enhancement, simple change, changelog:changed

#2861 Fix case for Java strings
  launcher/VersionProxyModel.cpp
  launcher/java/download/ArchiveDownloadTask.cpp
  launcher/ui/MainWindow.ui
  launcher/ui/java/InstallJavaDialog.cpp
  launcher/ui/pages/global/JavaPage.cpp
  launcher/ui/setupwizard/AutoJavaWizardPage.ui
  launcher/ui/setupwizard/JavaWizardPage.cpp
Labels: simple change, changelog:omit

#2867 fix: don't annoy when java tmpdir jvmarg is set & /tmp is noexec
  launcher/Application.cpp
Labels: changelog:fixed
