Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-02, with the labels that each got.

#2050 Use `minecraft` instead of `.minecraft` for better accessibility
  launcher/InstanceCopyTask.cpp
  launcher/InstanceImportTask.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/modplatform/import_ftb/PackInstallTask.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/technic/SingleZipPackInstallTask.cpp
  launcher/modplatform/technic/SolderPackInstallTask.cpp
  launcher/modplatform/technic/TechnicPackProcessor.cpp
Labels: enhancement, changelog:changed, backport release-8.x

#2116 Fix a few use-after-free bugs
  launcher/Exception.h
  launcher/modplatform/helpers/NetworkResourceAPI.cpp
  launcher/ui/pages/modplatform/ResourceModel.cpp
Labels: bug

#2112 Use QTextFragment for inserting log lines
  launcher/ui/widgets/LogView.cpp
Labels: enhancement, needs-testing, backport release-8.x

#2126 Use absolute path to load MangoHUD library
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, changelog:fixed, backport release-8.x

#2110 Fixed curseforge neoforge import for 1.20.1 versions
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlamePackExportTask.cpp
Labels: bug, simple change, changelog:fixed

#2137 feat: add "use zink" button
  launcher/Application.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/ui/pages/global/MinecraftPage.cpp
  launcher/ui/pages/global/MinecraftPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.ui
Labels: enhancement, Linux, changelog:added

#2152 ci: fix permissions for backport workflow
  .github/workflows/backport.yml
Labels: simple change, actions, changelog:omit, backport release-8.x

#2141 Use empty list label code for welcome screen
  launcher/ui/instanceview/InstanceView.cpp
Labels: simple change, ui rework, changelog:changed, backport release-8.x
