Repository PrismLauncher/PrismLauncher, pull requests merged in 2024-11, with the labels that each got.

#3045 disable retry for modrinth currentVersions API
  launcher/modplatform/modrinth/ModrinthAPI.cpp
Labels: bug, simple change, changelog:omit, backport release-9.x

#3042 use isPortable to determine if the MSAStep should check for url handler
  launcher/minecraft/auth/steps/MSAStep.cpp
Labels: simple change, changelog:omit, backport release-9.x

#3060 ci: bump linux qt version
  .github/workflows/build.yml
Labels: packaging, changelog:fixed, backport release-9.x

#3036 Fix installed typo
  launcher/ui/dialogs/ResourceUpdateDialog.cpp
  launcher/ui/dialogs/ReviewMessageBox.cpp
Labels: simple change, changelog:omit, backport release-9.x

#3031 do not capture by default all values in lambdas
  launcher/Application.cpp
  launcher/DataMigrationTask.cpp
  launcher/FileSystem.cpp
  launcher/InstanceCopyTask.cpp
  launcher/InstanceList.cpp
  launcher/Version.cpp
  launcher/filelink/FileLink.cpp
  launcher/java/JavaUtils.cpp
  launcher/launch/steps/PostLaunchCommand.cpp
  launcher/launch/steps/PreLaunchCommand.cpp
  launcher/meta/VersionList.cpp
  launcher/minecraft/Library.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/OneSixVersionFormat.cpp
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/minecraft/update/LibrariesTask.cpp
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/helpers/NetworkResourceAPI.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/translations/TranslationsModel.cpp
  launcher/ui/GuiUtil.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/dialogs/ResourceUpdateDialog.cpp
  launcher/ui/pages/instance/LogPage.cpp
  launcher/ui/pages/instance/OtherLogsPage.cpp
  launcher/ui/pages/modplatform/ResourceModel.cpp
  launcher/ui/setupwizard/SetupWizard.cpp
  launcher/ui/themes/CustomTheme.cpp
  tests/DummyResourceAPI.h
  tests/FileSystem_test.cpp
  tests/Task_test.cpp
Labels: enhancement, changelog:omit

#3074 Close the window using the invokeMethod to not block
  launcher/Application.cpp
Labels: bug, simple change, changelog:omit

#3081 fix CONTRIBUTING.md formating
  CONTRIBUTING.md
Labels: simple change, changelog:omit

#3096 Fix file remaingin open after program closure
  launcher/InstanceCreationTask.cpp
  launcher/InstanceImportTask.cpp
  launcher/InstanceImportTask.h
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3098 Fix crash caused by invalid resource pointer
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
Labels: bug, simple change, blocked, changelog:fixed

#3094 Fix warnings regarding Resource static cast
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/Resource.h
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ResourcePackPage.cpp
Labels: changelog:omit

#3070 Add scrollbar to Settings -> Launcher -> Features
  launcher/ui/pages/global/LauncherPage.ui
Labels: bug, changelog:fixed, backport release-9.x

#3024 fix leak on resource search
  launcher/modplatform/helpers/NetworkResourceAPI.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3019 fixed double deletion for tasks
  launcher/Application.cpp
  launcher/DataMigrationTask.cpp
  launcher/DataMigrationTask.h
  launcher/JavaCommon.cpp
  launcher/LaunchController.cpp
  launcher/LaunchController.h
  launcher/java/JavaChecker.cpp
  launcher/java/JavaChecker.h
  launcher/java/JavaInstallList.cpp
  launcher/launch/LaunchStep.cpp
  launcher/launch/steps/CheckJava.cpp
  launcher/meta/Index.cpp
  launcher/meta/VersionList.cpp
  launcher/minecraft/ComponentUpdateTask.cpp
  launcher/minecraft/ComponentUpdateTask.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftLoadAndCheck.cpp
  launcher/minecraft/MinecraftLoadAndCheck.h
  launcher/minecraft/auth/AuthFlow.cpp
  launcher/minecraft/auth/AuthFlow.h
  launcher/minecraft/auth/MinecraftAccount.cpp
  launcher/minecraft/launch/AutoInstallJava.cpp
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/minecraft/mod/tasks/GetModDependenciesTask.h
  launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalShaderPackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalTexturePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp
  launcher/minecraft/mod/tasks/ResourceFolderLoadTask.cpp
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlamePackExportTask.cpp
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/net/NetJob.cpp
  launcher/tasks/ConcurrentTask.cpp
  launcher/tasks/ConcurrentTask.h
  launcher/tasks/MultipleOptionsTask.cpp
  launcher/tasks/MultipleOptionsTask.h
  launcher/tasks/SequentialTask.cpp
  launcher/tasks/SequentialTask.h
  launcher/tasks/Task.cpp
  launcher/tasks/Task.h
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/MSALoginDialog.cpp
  launcher/ui/dialogs/ResourceDownloadDialog.cpp
  launcher/ui/dialogs/ResourceUpdateDialog.cpp
  launcher/ui/java/InstallJavaDialog.cpp
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ResourcePackPage.cpp
  launcher/ui/pages/instance/ShaderPackPage.cpp
  launcher/ui/pages/instance/TexturePackPage.cpp
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/widgets/JavaSettingsWidget.cpp
  tests/Task_test.cpp
Labels: bug, changelog:fixed, backport release-9.x

#3083 Fix resource search
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
Labels: bug, simple change, changelog:omit

#3068 [Linux] Update Nix README
  nix/README.md
Labels: changelog:omit

#3130 Improve MANIFEST.MF parsing
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#2875 [Linux] Integrate switcheroo-control for discrete GPU support
  CMakeLists.txt
  launcher/CMakeLists.txt
  launcher/minecraft/MinecraftInstance.cpp
Labels: enhancement, Linux, changelog:added
