Repository PrismLauncher/PrismLauncher, pull requests merged in 2025-05, with the labels that each got.

#3707 Split build workflow into composite actions
  .github/actions/package/linux/action.yml
  .github/actions/package/macos/action.yml
  .github/actions/package/windows/action.yml
  .github/actions/setup-dependencies/action.yml
  .github/actions/setup-dependencies/linux/action.yml
  .github/actions/setup-dependencies/macos/action.yml
  .github/actions/setup-dependencies/windows/action.yml
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/trigger_builds.yml
Labels: actions, packaging, changelog:merged, blocking

#3724 Build MinGW binaries for ARM64
  .github/actions/setup-dependencies/windows/action.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: actions, Windows, packaging, needs-testing, changelog:added

#3611 [macOS] Remove support for macOS 11
  .github/workflows/build.yml
Labels: simple change, actions, macOS, packaging, changelog:removed

#3744 jq if statements need parens
  .github/workflows/blocked-prs.yml
Labels: simple change, actions, changelog:omit

#3747 Fix jq blocked
  .github/workflows/blocked-prs.yml
Labels: simple change, actions, changelog:omit

#3746 Replace deprecated unique_qobject_ptr::swap with unique_ptr
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.h
  launcher/ui/pages/modplatform/flame/FlameResourcePages.cpp
  launcher/ui/pages/modplatform/flame/FlameResourcePages.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.h
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.h
Labels: changelog:omit, blocking

#3756 Don't re-define structs for newer MinGW versions
  launcher/FileSystem.cpp
Labels: simple change, Windows, changelog:fixed

#3757 MinGW CI improvements
  .github/actions/setup-dependencies/windows/action.yml
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
Labels: simple change, actions, Windows, changelog:omit

#3752 feat: search for pack icon in the actual file
  launcher/InstanceImportTask.cpp
Labels: changelog:added

#2966 Allow the user to create a shortcut on the desktop and/or application folder
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
Labels: enhancement, changelog:changed

#1872 Improvements to upload logs
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/logs/AnonymizeLog.cpp
  launcher/logs/AnonymizeLog.h
  launcher/net/PasteUpload.cpp
  launcher/net/PasteUpload.h
  launcher/ui/GuiUtil.cpp
  launcher/ui/GuiUtil.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.ui
Labels: enhancement, changelog:added, blocking

#3768 chore(readme): update Jetbrains logo
  README.md
Labels: simple change, changelog:omit

#3773 chore: replace foreach macro
  launcher/java/JavaUtils.cpp
  launcher/ui/widgets/CheckComboBox.cpp
  launcher/ui/widgets/InfoFrame.cpp
  launcher/updater/MacSparkleUpdater.mm
Labels: changelog:omit

#3767 Allow creating shortcuts to individual worlds and servers with Quick Play
  launcher/CMakeLists.txt
  launcher/minecraft/ShortcutUtils.cpp
  launcher/minecraft/ShortcutUtils.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/MainWindow.ui
  launcher/ui/dialogs/CreateShortcutDialog.cpp
  launcher/ui/dialogs/CreateShortcutDialog.h
  launcher/ui/dialogs/CreateShortcutDialog.ui
Labels: enhancement, changelog:added

#3761 feat(skin manager): add elytra preview
  launcher/ui/dialogs/skins/SkinManageDialog.cpp
  launcher/ui/dialogs/skins/SkinManageDialog.ui
  launcher/ui/dialogs/skins/draw/BoxGeometry.cpp
  launcher/ui/dialogs/skins/draw/BoxGeometry.h
  launcher/ui/dialogs/skins/draw/Scene.cpp
  launcher/ui/dialogs/skins/draw/Scene.h
  launcher/ui/dialogs/skins/draw/SkinOpenGLWindow.cpp
  launcher/ui/dialogs/skins/draw/SkinOpenGLWindow.h
Labels: enhancement, simple change, changelog:added

#2631 feat: propagate Sink error handling
  launcher/net/ByteArraySink.h
  launcher/net/FileSink.cpp
  launcher/net/NetRequest.cpp
  launcher/net/PasteUpload.cpp
  launcher/net/PasteUpload.h
  launcher/net/Sink.h
  launcher/screenshots/ImgurAlbumCreation.cpp
  launcher/screenshots/ImgurUpload.cpp
  launcher/tasks/ConcurrentTask.cpp
  launcher/ui/GuiUtil.cpp
Labels: changelog:changed
