Repository PrismLauncher/PrismLauncher, pull requests merged in 2025-06, with the labels that each got.

#3820 Hopefully fix segfault with HintOverrideProxyStyle
  launcher/ui/themes/HintOverrideProxyStyle.cpp
Labels: bug, changelog:merged

#3659 feat: add setting to control the loaders for mod search
  launcher/Json.cpp
  launcher/Json.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/ui/widgets/MinecraftSettingsWidget.cpp
  launcher/ui/widgets/MinecraftSettingsWidget.h
  launcher/ui/widgets/MinecraftSettingsWidget.ui
  launcher/ui/widgets/ModFilterWidget.cpp
Labels: enhancement, simple change, changelog:added

#3378 improve blocked mods dialog
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
  launcher/ui/dialogs/BlockedModsDialog.ui
Labels: enhancement, simple change, changelog:changed

#3826 fix: warning with different signedness
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
Labels: changelog:omit

#3740 remove: unused files
  launcher/CMakeLists.txt
  launcher/ui/widgets/ErrorFrame.cpp
  launcher/ui/widgets/ErrorFrame.h
  launcher/ui/widgets/ErrorFrame.ui
  launcher/ui/widgets/FocusLineEdit.cpp
  launcher/ui/widgets/FocusLineEdit.h
  launcher/ui/widgets/InstanceCardWidget.ui
  launcher/ui/widgets/LineSeparator.cpp
  launcher/ui/widgets/LineSeparator.h
Labels: changelog:omit

#3827 Fix crash and make loader override more consistent
  launcher/ui/widgets/MinecraftSettingsWidget.cpp
  launcher/ui/widgets/MinecraftSettingsWidget.h
Labels: bug, enhancement, changelog:merged

#3842 Remove reliance on SIGNAL/SLOT macros
  launcher/Application.cpp
  launcher/LoggedProcess.cpp
  launcher/java/JavaChecker.cpp
  launcher/meta/Index.cpp
  launcher/meta/VersionList.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/legacy_ftb/PackFetchTask.cpp
  launcher/news/NewsChecker.cpp
  launcher/settings/SettingsObject.cpp
  launcher/tools/JProfiler.cpp
  launcher/tools/JVisualVM.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/AboutDialog.cpp
  launcher/ui/dialogs/ExportInstanceDialog.cpp
  launcher/ui/dialogs/ExportToModListDialog.cpp
  launcher/ui/dialogs/IconPickerDialog.cpp
  launcher/ui/dialogs/ImportResourceDialog.cpp
  launcher/ui/dialogs/ProfileSelectDialog.cpp
  launcher/ui/dialogs/skins/SkinManageDialog.cpp
  launcher/ui/pages/global/ProxyPage.cpp
  launcher/ui/pages/instance/LogPage.cpp
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/instance/ScreenshotsPage.cpp
  launcher/ui/pages/instance/ServerPingTask.cpp
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlListModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlameResourcePages.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourcePages.cpp
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
  launcher/ui/widgets/AppearanceWidget.cpp
  launcher/ui/widgets/CheckComboBox.cpp
  launcher/ui/widgets/InfoFrame.cpp
  launcher/ui/widgets/JavaSettingsWidget.cpp
  launcher/ui/widgets/JavaWizardWidget.cpp
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/PageContainer.cpp
  libraries/LocalPeer/src/LocalPeer.cpp
  tests/FileSystem_test.cpp
  tests/Task_test.cpp
Labels: changelog:omit

#3840 chore: fix some codeql warnings
  launcher/minecraft/mod/ResourcePack.h
  launcher/modplatform/atlauncher/ATLPackIndex.h
  launcher/modplatform/flame/FlamePackIndex.h
  launcher/modplatform/modrinth/ModrinthPackManifest.h
  launcher/ui/pages/instance/McResolver.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlFilterModel.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlPage.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.cpp
  launcher/ui/pages/modplatform/import_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/legacy_ftb/Page.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/technic/TechnicData.h
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
  tests/FileSystem_test.cpp
Labels: changelog:omit

#3753 fix: qr code overlaping with text when adding account
  launcher/ui/dialogs/MSALoginDialog.cpp
Labels: bug, needs-testing, changelog:fixed

#3846 Fix MessageLevel.h error when compiling on Debian Stable
  launcher/MessageLevel.h
Labels: enhancement, changelog:omit

#3851 Auth abort fixes
  launcher/LaunchController.cpp
  launcher/minecraft/auth/MinecraftAccount.cpp
Labels: bug, changelog:fixed

#3848 chore: move opacity after checkbox draw
  launcher/ui/widgets/ProjectItem.cpp
Labels: changelog:merged

#3304 Build Linux binaries for ARM64
  .github/actions/package/linux/action.yml
  .github/actions/setup-dependencies/action.yml
  .github/actions/setup-dependencies/linux/action.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  cmake/commonPresets.json
  cmake/linuxPreset.json
  cmake/macosPreset.json
  cmake/windowsMSVCPreset.json
  cmake/windowsMinGWPreset.json
Labels: enhancement, actions, packaging, Linux, changelog:added, blocking

#3884 Improve the message when component metadata fails to download
  launcher/minecraft/ComponentUpdateTask.cpp
  launcher/minecraft/ComponentUpdateTask_p.h
Labels: enhancement, changelog:changed

#3868 Fix crash wrong component
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
Labels: changelog:fixed, blocking

#3897 fix: nightly link
  README.md
Labels: changelog:omit

#3909 fix: escape quotes in shorcut creation arguments
  launcher/FileSystem.cpp
Labels: changelog:fixed

#3916 fix typo in APIPage.ui
  launcher/ui/pages/global/APIPage.ui
Labels: changelog:fixed

#3919 fix: icon import with dot in name
  launcher/InstanceImportTask.cpp
  launcher/icons/IconList.cpp
Labels: changelog:fixed
