Repository PrismLauncher/PrismLauncher, pull requests merged in 2025-09, with the labels that each got.

#4040 Simplify Rule class
  launcher/minecraft/Library.cpp
  launcher/minecraft/Library.h
  launcher/minecraft/MojangVersionFormat.cpp
  launcher/minecraft/Rule.cpp
  launcher/minecraft/Rule.h
Labels: changelog:omit

#4157 Fix crash in Rule::apply
  launcher/minecraft/Rule.cpp
Labels: bug, changelog:omit

#4158 Remove unused code
  launcher/CMakeLists.txt
  launcher/InstancePageProvider.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/minecraft/gameoptions/GameOptions.cpp
  launcher/minecraft/gameoptions/GameOptions.h
  launcher/ui/pages/instance/GameOptionsPage.cpp
  launcher/ui/pages/instance/GameOptionsPage.ui
  launcher/ui/setupwizard/ThemeWizardPage.cpp
Labels: changelog:omit

#4167 Avoid `pull_request_target` in Nix workflow, always use upstream Nix
  .github/actions/get-merge-commit/action.yml
  .github/workflows/nix.yml
Labels: actions, packaging, changelog:omit
