Repository PrismLauncher/PrismLauncher, pull requests merged in 2025-08, with the labels that each got.

#4030 Explicitly install Java for Windows in CI
  .github/actions/setup-dependencies/windows/action.yml
Labels: actions, Windows, changelog:omit

#4033 A few tweaks to new ui
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
  launcher/ui/widgets/AppearanceWidget.ui
Labels: enhancement, changelog:merged

#4084 Fix resourcepack parsing
  launcher/minecraft/mod/DataPack.h
  launcher/minecraft/mod/ResourcePack.h
  launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp
  tests/ResourcePackParse_test.cpp
Labels: bug, changelog:fixed
