Repository PrismLauncher/PrismLauncher, pull requests merged in 2025-03, with the labels that each got.

#3256 Improve profile setup error messages
  launcher/ui/dialogs/ProfileSetupDialog.cpp
Labels: enhancement, simple change, changelog:changed

#3283 Add skin preview
  .github/workflows/codeql.yml
  CMakeLists.txt
  launcher/CMakeLists.txt
  launcher/main.cpp
  launcher/minecraft/skins/SkinList.cpp
  launcher/minecraft/skins/SkinList.h
  launcher/minecraft/skins/SkinModel.cpp
  launcher/minecraft/skins/SkinModel.h
  launcher/resources/shaders/fshader.glsl
  launcher/resources/shaders/shaders.qrc
  launcher/resources/shaders/vshader.glsl
  launcher/ui/dialogs/skins/SkinManageDialog.cpp
  launcher/ui/dialogs/skins/SkinManageDialog.h
  launcher/ui/dialogs/skins/SkinManageDialog.ui
  launcher/ui/dialogs/skins/draw/BoxGeometry.cpp
  launcher/ui/dialogs/skins/draw/BoxGeometry.h
  launcher/ui/dialogs/skins/draw/Scene.cpp
  launcher/ui/dialogs/skins/draw/Scene.h
  launcher/ui/dialogs/skins/draw/SkinOpenGLWindow.cpp
  launcher/ui/dialogs/skins/draw/SkinOpenGLWindow.h
Labels: enhancement, changelog:added

#3295 implement packignore for curseforge/modrinth export
  launcher/FileIgnoreProxy.cpp
  launcher/FileIgnoreProxy.h
  launcher/ui/dialogs/ExportInstanceDialog.cpp
  launcher/ui/dialogs/ExportInstanceDialog.h
  launcher/ui/dialogs/ExportPackDialog.cpp
  launcher/ui/dialogs/ExportPackDialog.h
Labels: enhancement, simple change, changelog:added

#3452 Default to Fusion based Dark/Bright themes on Windows
  launcher/Application.cpp
Labels: enhancement, changelog:changed, backport release-9.x

#3461 chore: Update year range
  COPYING.md
  program_info/CMakeLists.txt
Labels: simple change, changelog:omit, backport release-9.x

#3464 fix null mainwindow in case of login on setup
  launcher/Application.cpp
  launcher/Application.h
  launcher/minecraft/auth/steps/MSAStep.cpp
  launcher/minecraft/auth/steps/MSAStep.h
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3470 fix beginResetModel called before endResetModel
  launcher/VersionProxyModel.cpp
Labels: bug, simple change, changelog:omit, backport release-9.x

#3475 fix duplicate optional mods dialog appearing when updating a modpack
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
Labels: bug, simple change, changelog:fixed

#3480 Qt app ID fix
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/ui/MainWindow.cpp
  program_info/CMakeLists.txt
  program_info/genicons.sh
  program_info/org.prismlauncher.PrismLauncher.metainfo.xml.in
  program_info/prismlauncher.qrc.in
Labels: simple change

#3496 Fix crash with invalid quilt mod info
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3466 Make account checks more on-par with MultiMC
  launcher/LaunchController.cpp
  launcher/LaunchController.h
Labels: enhancement, simple change, changelog:omit

#3112 Show online players on servers screen
  launcher/CMakeLists.txt
  launcher/tasks/ConcurrentTask.h
  launcher/tasks/Task.h
  launcher/ui/pages/instance/McClient.cpp
  launcher/ui/pages/instance/McClient.h
  launcher/ui/pages/instance/McResolver.cpp
  launcher/ui/pages/instance/McResolver.h
  launcher/ui/pages/instance/ServerPingTask.cpp
  launcher/ui/pages/instance/ServerPingTask.h
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/instance/ServersPage.h
  launcher/ui/pages/instance/ServersPage.ui
Labels: enhancement, changelog:added

#3511 fix no cape select
  launcher/ui/dialogs/skins/SkinManageDialog.cpp
Labels: bug, simple change, changelog:fixed

#3046 refactor FlameCheckUpdate to remove qEventLoop
  launcher/minecraft/auth/AuthFlow.cpp
  launcher/minecraft/auth/AuthSession.h
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FileResolvingTask.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/modplatform/flame/FlameCheckUpdate.h
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/flame/FlameModIndex.h
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.h
  launcher/ui/pages/modplatform/flame/FlameResourceModels.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthResourceModels.cpp
Labels: simple change, changelog:omit

#3526 Improve clangd support (in Nix development shell)
  .gitignore
  CMakeLists.txt
  flake.nix
Labels: changelog:omit

#3530 Use correct colours for all system themes
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/SystemTheme.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
Labels: bug

#3529 fix account help link
  launcher/ui/pages/global/AccountListPage.h
Labels: bug, simple change, changelog:omit, backport release-9.x

#3528 Fix crash with low disk space
  launcher/net/FileSink.cpp
  launcher/net/FileSink.h
  launcher/net/MetaCacheSink.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#2616 Refactor ResourcePack
  launcher/minecraft/mod/DataPack.h
  launcher/minecraft/mod/ResourcePack.cpp
  launcher/minecraft/mod/ResourcePack.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalDataPackParseTask.h
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.h
  launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp
  tests/DataPackParse_test.cpp
  tests/ResourcePackParse_test.cpp
Labels: changelog:omit

#3543 Pin AppImage tooling in CI, drop libfuse2
  .github/workflows/build.yml
Labels: actions, packaging, Linux, changelog:omit, backport release-9.x

#1679 chore:fixed some codeql warnings
  launcher/DataMigrationTask.cpp
  launcher/FileSystem.h
  launcher/InstanceCopyTask.cpp
  launcher/InstanceCopyTask.h
  launcher/JavaCommon.h
  launcher/VersionProxyModel.cpp
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/WorldList.cpp
  launcher/minecraft/auth/AccountList.cpp
  launcher/minecraft/gameoptions/GameOptions.cpp
  launcher/minecraft/mod/DataPack.cpp
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.h
  launcher/modplatform/legacy_ftb/PackFetchTask.h
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.h
  launcher/pathmatcher/MultiMatcher.h
  launcher/pathmatcher/RegexpMatcher.h
  launcher/ui/dialogs/ProgressDialog.cpp
  launcher/ui/dialogs/ProgressDialog.h
  launcher/ui/dialogs/ResourceUpdateDialog.cpp
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/instance/WorldListPage.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.h
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.h
  launcher/ui/pages/modplatform/import_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.h
  launcher/ui/pages/modplatform/legacy_ftb/Page.cpp
  launcher/ui/pages/modplatform/legacy_ftb/Page.h
  launcher/ui/widgets/FocusLineEdit.h
  tests/FileSystem_test.cpp
Labels: simple change, changelog:omit

#3555 fix themes leak
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/SystemTheme.h
Labels: bug, simple change, changelog:omit, backport release-9.x

#3561 Fix typo in NetRequest.cpp
  launcher/net/NetRequest.cpp
Labels: changelog:fixed, backport release-9.x
