Repository PrismLauncher/PrismLauncher, pull requests merged in 2025-01, with the labels that each got.

#3277 fix drop file on resource page
  launcher/ui/pages/instance/ExternalResourcesPage.ui
Labels: bug, simple change, changelog:omit

#3278 remove drop label
  launcher/CMakeLists.txt
  launcher/ui/widgets/DropLabel.cpp
  launcher/ui/widgets/DropLabel.h
Labels: simple change, changelog:omit

#3255 propagate load component error
  launcher/minecraft/MinecraftLoadAndCheck.cpp
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile.h
  launcher/ui/pages/instance/VersionPage.cpp
Labels: enhancement, simple change, changelog:changed, backport release-9.x

#3228 Add settings to control the if prism should move the downloaded mods
  launcher/Application.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement, simple change, changelog:added

#1555 Correctly expand environment variables for pre/post launch and wrapper commands
  launcher/launch/LaunchTask.cpp
  launcher/launch/LaunchTask.h
  launcher/launch/steps/PostLaunchCommand.cpp
  launcher/launch/steps/PreLaunchCommand.cpp
  launcher/minecraft/launch/LauncherPartLaunch.cpp
Labels: bug, simple change, changelog:fixed

#3179 Fix $INST_JAVA not being set for auto download java
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, changelog:fixed, backport release-9.x

#3292 Update Modrinth API authentication link
  launcher/ui/pages/global/APIPage.ui
Labels: bug, simple change, changelog:fixed, backport release-9.x

#2737 Truncate logs for mclo.gs to fit 25k line limit
  launcher/ui/GuiUtil.cpp
Labels: enhancement, simple change, changelog:added, backport release-9.x

#3254 remove EditAccountDialog
  launcher/CMakeLists.txt
  launcher/ui/dialogs/EditAccountDialog.cpp
  launcher/ui/dialogs/EditAccountDialog.h
  launcher/ui/dialogs/EditAccountDialog.ui
Labels: simple change, changelog:omit, backport release-9.x

#1689 Added mouse interactions for labels in ProgressDialog
  launcher/ui/dialogs/ProfileSetupDialog.ui
  launcher/ui/widgets/SubTaskProgressBar.ui
Labels: enhancement, simple change, needs-testing, changelog:changed, backport release-9.x

#3309 bump to 9.3
  CMakeLists.txt
Labels: simple change, changelog:omit

#3318 Build Nix packages for aarch64-linux
  .github/workflows/build.yml
Labels: simple change, actions, packaging, Linux, changelog:added, backport release-9.x

#3319 Build Flatpaks for ARM
  .github/workflows/build.yml
Labels: simple change, actions, packaging, Linux, changelog:added, backport release-9.x

#2895 chore: update to qt 6.8.x
  .github/workflows/build.yml
Labels: simple change, packaging, changelog:omit, backport release-9.x

#3299 Use Ubuntu 22.04 for Linux builds
  .github/workflows/build.yml
Labels: simple change, packaging, Linux, changelog:fixed, backport release-9.x

#3329 [Backport release-9.x] chore: update to qt 6.8.x
  .github/workflows/build.yml
Labels: manual backport

#3331 [Backport release-9.x] Use Ubuntu 22.04 for Linux builds
  .github/workflows/build.yml
Labels: manual backport

#3330 Use better compile flags for MINGW
  CMakeLists.txt
Labels: simple change, Windows, changelog:changed, backport release-9.x

#1413 feat: updated flame mod resolution
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.h
  launcher/modplatform/flame/PackManifest.h
Labels: enhancement, simple change, changelog:changed

#3294 Fix updating Curseforge mods with missing mod loader
  launcher/modplatform/flame/FlameAPI.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3332 Update Modrinth Client/Server Filters to match Modrinth website & launcher.
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/ui/widgets/ModFilterWidget.cpp
Labels: enhancement, simple change, changelog:changed

#3360 Split Flatpak and Nix CI jobs from main build workflow
  .github/workflows/build.yml
  .github/workflows/flatpak.yml
  .github/workflows/nix.yml
  .github/workflows/trigger_builds.yml
  .github/workflows/trigger_release.yml
Labels: actions, changelog:omit, backport release-9.x

#3362 ci: use flakehub cache
  .github/workflows/nix.yml
Labels: simple change, actions, changelog:omit, backport release-9.x

#3359 Publish on FlakeHub
  .github/workflows/publish.yml
  .github/workflows/winget.yml
Labels: simple change, actions, macOS, packaging, Linux, changelog:added

#3368 Add Nix out paths to job summary
  .github/workflows/nix.yml
Labels: simple change, actions, changelog:omit, backport release-9.x

#3260 Map Minecraft snapshots to Modrinth
  launcher/modplatform/ResourceAPI.h
  launcher/modplatform/modrinth/ModrinthAPI.cpp
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x
