Repository PrismLauncher/PrismLauncher, pull requests merged in 2025-02, with the labels that each got.

#3374 Fix Nix workflow
  .github/workflows/nix.yml
Labels: simple change, actions, changelog:omit

#3381 Add PackageManager category
  program_info/org.prismlauncher.PrismLauncher.desktop.in
Labels: packaging, changelog:omit

#3389 Add stale workflow
  .github/workflows/stale.yml
Labels: actions, changelog:omit

#3392 Fixed when game crashes, it doesn't log any time played
  launcher/minecraft/launch/LauncherPartLaunch.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3407 Fix some undefined behaviour
  CMakeLists.txt
  launcher/launch/LogModel.h
  launcher/ui/widgets/CheckComboBox.cpp
  launcher/ui/widgets/CheckComboBox.h
Labels: bug, simple change, changelog:omit, backport release-9.x

#3412 remove some unused files
  launcher/ui/pages/global/MinecraftPage.h
  launcher/ui/pages/global/MinecraftPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.ui
Labels: simple change, changelog:omit

#3414 make sure if user changes java path also disable java management
  launcher/ui/widgets/JavaSettingsWidget.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3413 add libMangoHud_shim.so to mangohub preloadlist
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change, changelog:fixed, backport release-9.x

#3425 Recognize riscv64 as a 64-bit platform
  launcher/java/JavaChecker.cpp
Labels: enhancement, simple change, changelog:added, backport release-9.x

#3433 ci: always run nix workflow on push
  .github/workflows/nix.yml
Labels: changelog:omit
