Repository PrismLauncher/PrismLauncher, pull requests merged in 2025-07, with the labels that each got.

#3933 Correct Corruption in CustomCommands
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/flatpak.yml
  .github/workflows/nix.yml
  launcher/ui/widgets/CustomCommands.ui
Labels: bug, simple change, Windows, changelog:omit

#3940 Don't bundle Qt with the Linux Portable build
  .github/actions/package/linux/action.yml
Labels: simple change, actions, packaging, Linux, changelog:changed

#3934 Update to Qt 6.9
  .github/actions/setup-dependencies/action.yml
  CMakeLists.txt
Labels: simple change, changelog:changed

#3544 propagate side as enum instead of Qstring
  launcher/minecraft/mod/MetadataHandler.h
  launcher/minecraft/mod/Mod.cpp
  launcher/modplatform/ModIndex.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/ResourceAPI.h
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
  launcher/modplatform/modrinth/ModrinthPackExportTask.h
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/packwiz/Packwiz.cpp
  launcher/modplatform/packwiz/Packwiz.h
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.h
  tests/Packwiz_test.cpp
Labels: enhancement, simple change, changelog:omit, blocking

#3742 Add support for vcpkg
  .github/actions/setup-dependencies/windows/action.yml
  .github/workflows/build.yml
  CMakeLists.txt
  launcher/CMakeLists.txt
  vcpkg-configuration.json
  vcpkg.json
Labels: actions, Windows, packaging, changelog:merged

#3961 Add "Babric" and "BTA (Babric)" filters as shown on Modrinth
  launcher/modplatform/ModIndex.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/import_ftb/PackInstallTask.cpp
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.h
  launcher/ui/widgets/ModFilterWidget.ui
Labels: changelog:added

#4017 update ftb import to consider meta folder
  launcher/modplatform/import_ftb/PackHelpers.cpp
  launcher/ui/pages/modplatform/import_ftb/ImportFTBPage.cpp
  launcher/ui/pages/modplatform/import_ftb/ListModel.cpp
Labels: changelog:fixed

#4006 ensure that both cape and skin are downloaded via https
  launcher/minecraft/auth/AccountData.cpp
  launcher/minecraft/auth/Parsers.cpp
Labels: needs-testing, changelog:fixed

#3977 ci(macos): use vcpkg
  .github/actions/setup-dependencies/action.yml
  .github/actions/setup-dependencies/macos/action.yml
  .github/actions/setup-dependencies/windows/action.yml
  COPYING.md
  cmake/macosPreset.json
  cmake/vcpkg-ports/vcpkg-tool-meson/README.md
  cmake/vcpkg-ports/vcpkg-tool-meson/adjust-args.patch
  cmake/vcpkg-ports/vcpkg-tool-meson/adjust-python-dep.patch
  cmake/vcpkg-ports/vcpkg-tool-meson/fix-libcpp-enable-assertions.patch
  cmake/vcpkg-ports/vcpkg-tool-meson/install.cmake
  cmake/vcpkg-ports/vcpkg-tool-meson/meson-intl.patch
  cmake/vcpkg-ports/vcpkg-tool-meson/meson.template.in
  cmake/vcpkg-ports/vcpkg-tool-meson/portfile.cmake
  cmake/vcpkg-ports/vcpkg-tool-meson/remove-freebsd-pcfile-specialization.patch
  cmake/vcpkg-ports/vcpkg-tool-meson/universal-osx.patch
  cmake/vcpkg-ports/vcpkg-tool-meson/vcpkg-port-config.cmake
  cmake/vcpkg-ports/vcpkg-tool-meson/vcpkg.json
  cmake/vcpkg-ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake
  cmake/vcpkg-ports/vcpkg-tool-meson/vcpkg_install_meson.cmake
  cmake/vcpkg-triplets/universal-osx.cmake
  vcpkg-configuration.json
Labels: actions, macOS, packaging, needs-testing, changelog:omit, blocking
