Repository PrismLauncher/PrismLauncher, pull requests merged in 2025-04, with the labels that each got.

#3454 feat: add updater dialogues
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/instance/ManagedPackPage.h
Labels: changelog:fixed, backport release-9.x

#3550 Rename instance's physical dir when renaming instances
  launcher/Application.cpp
  launcher/BaseInstance.cpp
  launcher/BaseInstance.h
  launcher/CMakeLists.txt
  launcher/InstanceDirUpdate.cpp
  launcher/InstanceDirUpdate.h
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/CustomMessageBox.cpp
  launcher/ui/dialogs/CustomMessageBox.h
  launcher/ui/instanceview/InstanceDelegate.cpp
  launcher/ui/instanceview/InstanceDelegate.h
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: changelog:added

#3497 ci: add a workflow to detect and check dependencies for blocked pull requests
  .github/workflows/blocked-prs.yml
  .github/workflows/merge-blocking-pr.yml
Labels: actions, changelog:omit

#3571 (blocked-pr): push json expansion into env
  .github/workflows/blocked-prs.yml
Labels: actions, changelog:omit

#3572 Add checkbox for LiteLoader in mod filter
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.ui
Labels: bug, simple change, changelog:fixed

#3560 Nix Flake spring cleaning
  .gitignore
  default.nix
  flake.lock
  flake.nix
  nix/README.md
  nix/checks.nix
  nix/unwrapped.nix
Labels: macOS, packaging, Linux, changelog:omit

#3576 [Backport release-9.x] Nix Flake spring cleaning
  .gitignore
  default.nix
  flake.lock
  flake.nix
  nix/README.md
  nix/checks.nix
  nix/unwrapped.nix
Labels: manual backport, changelog:omit

#3584 Use default palette on all system themes
  launcher/ui/themes/SystemTheme.cpp
  launcher/ui/themes/SystemTheme.h
  launcher/ui/themes/ThemeManager.cpp
  launcher/ui/themes/ThemeManager.h
Labels: bug, simple change, changelog:omit, backport release-9.x

#3594 Fix Nix release CI
  .github/workflows/nix.yml
  .github/workflows/publish.yml
Labels: simple change, actions, macOS, packaging, Linux, changelog:omit, backport release-9.x

#3587 Use ninja with MSVC on x64
  .github/workflows/build.yml
Labels: simple change, actions, Windows, changelog:omit, backport release-9.x

#3595 Fix compatibility with macOS 11
  .github/workflows/build.yml
Labels: bug, simple change, actions, macOS, changelog:fixed

#3598 chore: bump to 9.4
  CMakeLists.txt
Labels: changelog:omit

#3612 [Linux] Bump Ubuntu requirement to 22.04
  .github/workflows/build.yml
Labels: simple change, actions, packaging, Linux, changelog:changed

#3607 Remove macOS Legacy build
  .github/workflows/build.yml
Labels: simple change, actions, macOS, packaging, changelog:removed, blocking

#3619 chore: remove release macos Legacy reference
  .github/workflows/trigger_release.yml
Labels: bug, actions, macOS, packaging, changelog:merged

#3605 Start using patch versioning for launcher
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/updater/prismupdater/PrismUpdater.cpp
  launcher/updater/prismupdater/PrismUpdater.h
  program_info/win_install.nsi.in
Labels: simple change, changelog:changed

#3630 Shorten LocalPeer socket names to fix CLI not working if an instance of the launcher is already running
  launcher/Application.cpp
  libraries/LocalPeer/src/LocalPeer.cpp
Labels: bug, simple change, macOS, Linux, changelog:fixed

#3638 Harmonizing "Other Log" page with "Minecraft Log"
  launcher/InstancePageProvider.h
  launcher/launch/LogModel.cpp
  launcher/launch/LogModel.h
  launcher/ui/pages/instance/LogPage.cpp
  launcher/ui/pages/instance/LogPage.h
  launcher/ui/pages/instance/LogPage.ui
  launcher/ui/pages/instance/OtherLogsPage.cpp
  launcher/ui/pages/instance/OtherLogsPage.h
  launcher/ui/pages/instance/OtherLogsPage.ui
  launcher/ui/widgets/LogView.cpp
  launcher/ui/widgets/LogView.h
Labels: enhancement, changelog:added

#3614 fix: crash when the instance window is closed before download dialog is open
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ResourcePackPage.cpp
  launcher/ui/pages/instance/ShaderPackPage.cpp
  launcher/ui/pages/instance/TexturePackPage.cpp
  launcher/ui/widgets/ModFilterWidget.cpp
Labels: bug, simple change, changelog:fixed

#3644 chore: sync cmake version with the one used in the launcher
  libraries/LocalPeer/CMakeLists.txt
  libraries/gamemode/CMakeLists.txt
  libraries/javacheck/CMakeLists.txt
  libraries/launcher/CMakeLists.txt
  libraries/murmur2/CMakeLists.txt
  libraries/qdcss/CMakeLists.txt
  libraries/rainbow/CMakeLists.txt
Labels: simple change, actions, packaging, changelog:omit

#3657 fix: beginResetModel called before endResetModel
  launcher/VersionProxyModel.cpp
Labels: bug, simple change, changelog:fixed

#3660 chore: add getOrRegisterSetting function
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/settings/SettingsObject.cpp
  launcher/settings/SettingsObject.h
  launcher/ui/MainWindow.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ScreenshotsPage.cpp
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/WorldListPage.cpp
Labels: simple change, changelog:omit

#3658 chore: improve log display
  launcher/GZip.cpp
  launcher/GZip.h
  launcher/launch/LogModel.cpp
  launcher/launch/LogModel.h
  launcher/ui/pages/instance/OtherLogsPage.cpp
  launcher/ui/widgets/LogView.cpp
Labels: enhancement, simple change, changelog:added

#3641 Optimise log colourisation
  launcher/minecraft/MinecraftInstance.cpp
Labels: enhancement

#2174 Remove support for Qt 5
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/trigger_release.yml
  CMakeLists.txt
  COPYING.md
  launcher/DataMigrationTask.cpp
  launcher/FileIgnoreProxy.cpp
  launcher/FileSystem.cpp
  launcher/InstanceList.cpp
  launcher/StringUtils.cpp
  launcher/Version.h
  launcher/icons/IconList.cpp
  launcher/java/JavaChecker.cpp
  launcher/launch/steps/PostLaunchCommand.cpp
  launcher/launch/steps/PreLaunchCommand.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/WorldList.cpp
  launcher/minecraft/auth/MinecraftAccount.cpp
  launcher/minecraft/auth/Parsers.cpp
  launcher/minecraft/auth/steps/MSAStep.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/legacy_ftb/PackFetchTask.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/legacy_ftb/PrivatePackManager.cpp
  launcher/net/NetRequest.cpp
  launcher/net/PasteUpload.cpp
  launcher/translations/TranslationsModel.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/dialogs/skins/draw/SkinOpenGLWindow.cpp
  launcher/ui/instanceview/InstanceView.cpp
  launcher/ui/instanceview/VisualGroup.cpp
  launcher/ui/pages/instance/ServersPage.cpp
  libraries/LocalPeer/CMakeLists.txt
  libraries/LocalPeer/src/LocalPeer.cpp
  libraries/qdcss/CMakeLists.txt
  libraries/rainbow/CMakeLists.txt
  libraries/systeminfo/CMakeLists.txt
  libraries/systeminfo/src/distroutils.cpp
  nix/unwrapped.nix
Labels: changelog:removed, blocking

#3654 Console colors and log invocation location
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/InstanceList.cpp
  launcher/console/Console.h
  launcher/console/WindowsConsole.cpp
  launcher/console/WindowsConsole.h
  launcher/filelink/FileLink.cpp
  launcher/updater/prismupdater/PrismUpdater.cpp
Labels: enhancement, changelog:added

#3665 blocked-prs workflow fixes
  .github/workflows/merge-blocking-pr.yml
Labels: actions, changelog:omit

#3678 Ensure Nix workflows are actually running on PRs
  .github/actions/get-merge-commit.yml
  .github/workflows/nix.yml
Labels: actions, changelog:omit, backport release-9.x

#3634 Use nix-shell over nix develop in .envrc
  .envrc
  flake.nix
  shell.nix
Labels: changelog:omit

#3696 Improve CI path filtering
  .github/workflows/codeql.yml
  .github/workflows/flatpak.yml
  .github/workflows/nix.yml
  .github/workflows/trigger_builds.yml
Labels: simple change, actions, changelog:omit

#3697 ci(nix): fix get-merge-commit action call
  .github/actions/get-merge-commit/action.yml
  .github/workflows/nix.yml
Labels: simple change, actions, changelog:omit

#3692 Pass mainclass and gameargs to the main game via system properties
  libraries/launcher/org/prismlauncher/launcher/impl/StandardLauncher.java
Labels: simple change, changelog:added

#3669 Fix catastrophic regex mistake
  launcher/minecraft/MinecraftInstance.cpp
Labels: changelog:omit

#3690 fix: nullptr access
  launcher/ui/themes/SystemTheme.cpp
Labels: bug, simple change, changelog:fixed

#3670 Fix: Use after free collecting tasks from ResourceDownloadDialogs
  launcher/Application.cpp
  launcher/qtlogging.ini
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  launcher/ui/pages/instance/ResourcePackPage.cpp
  launcher/ui/pages/instance/ResourcePackPage.h
  launcher/ui/pages/instance/ShaderPackPage.cpp
  launcher/ui/pages/instance/ShaderPackPage.h
  launcher/ui/pages/instance/TexturePackPage.cpp
  launcher/ui/pages/instance/TexturePackPage.h
Labels: bug, changelog:fixed, blocking

#3642 Parse log4j xml events in logs
  launcher/BaseInstance.h
  launcher/CMakeLists.txt
  launcher/MessageLevel.cpp
  launcher/MessageLevel.h
  launcher/launch/LaunchTask.cpp
  launcher/launch/LaunchTask.h
  launcher/launch/LogModel.cpp
  launcher/launch/LogModel.h
  launcher/logs/LogParser.cpp
  launcher/logs/LogParser.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/ui/pages/instance/OtherLogsPage.cpp
  tests/CMakeLists.txt
  tests/XmlLogs_test.cpp
  tests/testdata/TestLogs/TerraFirmaGreg-Modern-forge.text.log
  tests/testdata/TestLogs/TerraFirmaGreg-Modern-forge.xml.log
  tests/testdata/TestLogs/TerraFirmaGreg-Modern-levels.txt
  tests/testdata/TestLogs/TerraFirmaGreg-Modern-xml-levels.txt
  tests/testdata/TestLogs/vanilla-1.21.5-levels.txt
  tests/testdata/TestLogs/vanilla-1.21.5.text.log
  tests/testdata/TestLogs/vanilla-1.21.5.xml.log
Labels: needs-testing, changelog:added

#3700 ci(nix): add github token for gh cli
  .github/workflows/nix.yml
Labels: changelog:omit

#3519 replace qvector with qlist
  launcher/Json.h
  launcher/icons/IconList.h
  launcher/launch/LogModel.cpp
  launcher/launch/LogModel.h
  launcher/meta/Index.cpp
  launcher/meta/Index.h
  launcher/meta/JsonFormat.cpp
  launcher/meta/Version.h
  launcher/meta/VersionList.cpp
  launcher/meta/VersionList.h
  launcher/minecraft/auth/AccountData.h
  launcher/minecraft/auth/AuthFlow.h
  launcher/minecraft/skins/SkinList.cpp
  launcher/minecraft/skins/SkinList.h
  launcher/modplatform/ModIndex.h
  launcher/modplatform/atlauncher/ATLPackIndex.h
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.h
  launcher/modplatform/atlauncher/ATLPackManifest.h
  launcher/modplatform/atlauncher/ATLShareCode.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/flame/FlamePackIndex.cpp
  launcher/modplatform/flame/FlamePackIndex.h
  launcher/modplatform/flame/PackManifest.h
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.h
  launcher/modplatform/technic/SolderPackManifest.h
  launcher/translations/TranslationsModel.cpp
  launcher/translations/TranslationsModel.h
  launcher/ui/dialogs/skins/draw/BoxGeometry.cpp
  launcher/ui/dialogs/skins/draw/Scene.h
  launcher/ui/instanceview/InstanceView.cpp
  launcher/ui/instanceview/InstanceView.h
  launcher/ui/instanceview/VisualGroup.cpp
  launcher/ui/instanceview/VisualGroup.h
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.h
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlUserInteractionSupportImpl.h
  launcher/ui/pages/modplatform/flame/FlameResourceModels.cpp
  launcher/ui/pages/modplatform/technic/TechnicData.h
  libraries/LocalPeer/src/LockedFile.h
Labels: simple change, changelog:omit

#3647 chore: make all the regexes static const
  launcher/BaseInstance.cpp
  launcher/InstanceImportTask.cpp
  launcher/JavaCommon.cpp
  launcher/LaunchController.cpp
  launcher/RecursiveFileSystemWatcher.cpp
  launcher/StringUtils.cpp
  launcher/Version.cpp
  launcher/java/JavaVersion.cpp
  launcher/launch/LaunchTask.cpp
  launcher/minecraft/GradleSpecifier.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/OneSixVersionFormat.cpp
  launcher/minecraft/ProfileUtils.cpp
  launcher/minecraft/auth/AccountData.cpp
  launcher/minecraft/auth/MinecraftAccount.cpp
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  launcher/minecraft/mod/Resource.cpp
  launcher/minecraft/mod/ResourcePack.cpp
  launcher/minecraft/mod/ShaderPack.cpp
  launcher/minecraft/mod/TexturePack.cpp
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/modplatform/atlauncher/ATLPackIndex.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/net/MetaCacheSink.cpp
  launcher/pathmatcher/FSTreeMatcher.h
  launcher/pathmatcher/MultiMatcher.h
  launcher/pathmatcher/RegexpMatcher.h
  launcher/pathmatcher/SimplePrefixMatcher.h
  launcher/ui/dialogs/NewComponentDialog.cpp
  launcher/ui/dialogs/ProfileSetupDialog.cpp
  launcher/ui/pages/global/APIPage.cpp
  launcher/ui/pages/instance/ScreenshotsPage.cpp
  launcher/updater/prismupdater/PrismUpdater.cpp
  libraries/LocalPeer/src/LocalPeer.cpp
  libraries/qdcss/src/qdcss.cpp
  libraries/systeminfo/src/distroutils.cpp
Labels: enhancement, changelog:omit

#3379 change java on modpack update
  launcher/BaseInstance.cpp
Labels: bug, simple change, changelog:fixed, inactive

#3516 Add checkboxes to resource downloader
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/ResourceModel.cpp
  launcher/ui/pages/modplatform/ResourceModel.h
  launcher/ui/pages/modplatform/ResourcePackModel.cpp
  launcher/ui/pages/modplatform/ResourcePackModel.h
  launcher/ui/pages/modplatform/ResourcePackPage.cpp
  launcher/ui/pages/modplatform/ResourcePackPage.h
  launcher/ui/pages/modplatform/ResourcePage.cpp
  launcher/ui/pages/modplatform/ResourcePage.h
  launcher/ui/pages/modplatform/ShaderPackModel.cpp
  launcher/ui/pages/modplatform/ShaderPackModel.h
  launcher/ui/pages/modplatform/ShaderPackPage.cpp
  launcher/ui/pages/modplatform/ShaderPackPage.h
  launcher/ui/pages/modplatform/TexturePackModel.cpp
  launcher/ui/pages/modplatform/TexturePackModel.h
  launcher/ui/pages/modplatform/TexturePackPage.h
  launcher/ui/pages/modplatform/atlauncher/AtlListModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.cpp
  launcher/ui/pages/modplatform/flame/FlameResourceModels.h
  launcher/ui/pages/modplatform/import_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
  launcher/ui/themes/HintOverrideProxyStyle.cpp
  launcher/ui/themes/HintOverrideProxyStyle.h
  launcher/ui/widgets/ProjectItem.cpp
  launcher/ui/widgets/ProjectItem.h
  tests/ResourceModel_test.cpp
Labels: enhancement, changelog:changed

#3703 ci(nix): fix the PR number
  .github/workflows/nix.yml
Labels: changelog:omit

#3708 fix: build error introduced in #3516
  launcher/ui/widgets/ProjectItem.cpp
Labels: changelog:omit

#3677 chore: format some of the project files
  .git-blame-ignore-revs
  launcher/Application.cpp
  launcher/launch/LogModel.cpp
  launcher/logs/LogParser.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/mod/Mod.h
  launcher/minecraft/mod/TexturePackFolderModel.cpp
  launcher/net/HttpMetaCache.cpp
  launcher/tasks/Task.h
  launcher/ui/MainWindow.cpp
  launcher/ui/pages/global/JavaPage.cpp
  launcher/ui/pages/global/JavaPage.h
  launcher/ui/pages/instance/InstanceSettingsPage.h
  launcher/ui/pages/instance/ManagedPackPage.cpp
  launcher/ui/pages/instance/McClient.cpp
  launcher/ui/pages/instance/McClient.h
  launcher/ui/pages/instance/McResolver.cpp
  launcher/ui/pages/instance/McResolver.h
  launcher/ui/pages/instance/ServerPingTask.cpp
  launcher/ui/pages/instance/ServerPingTask.h
  launcher/ui/themes/HintOverrideProxyStyle.cpp
Labels: changelog:omit

#3710 fix: file filtering on modpack export
  launcher/FileIgnoreProxy.cpp
  launcher/FileIgnoreProxy.h
  launcher/MMCZip.cpp
  launcher/MMCZip.h
  launcher/modplatform/flame/FlamePackExportTask.cpp
  launcher/modplatform/flame/FlamePackExportTask.h
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
  launcher/modplatform/modrinth/ModrinthPackExportTask.h
Labels: bug, changelog:fixed

#3702 Add support for CMake presets and workflows
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .gitignore
  CMakePresets.json
  cmake/commonPresets.json
  cmake/linuxPreset.json
  cmake/macosPreset.json
  cmake/windowsMSVCPreset.json
  cmake/windowsMinGWPreset.json
Labels: actions, changelog:merged, blocking

#3712 fix: crash when task was canceled and abort signal was fired early
  launcher/InstanceImportTask.cpp
  launcher/java/download/ArchiveDownloadTask.cpp
  launcher/modplatform/flame/FlamePackExportTask.cpp
  launcher/modplatform/modrinth/ModrinthPackExportTask.cpp
Labels: bug, changelog:fixed

#3717 ci: only run on specific paths
  .github/workflows/codeql.yml
  .github/workflows/flatpak.yml
  .github/workflows/nix.yml
  .github/workflows/trigger_builds.yml
Labels: simple change, actions, changelog:omit

#3718 fix: task typo in flame export task
  launcher/modplatform/flame/FlamePackExportTask.cpp
Labels: changelog:omit
